### ISSUE TITLE
Ruby EOL Version

### ISSUE THREAD

**Issue by RobbieMcKinstry** [autolab/Autolab#1000]
The current required Ruby version `2.2.2` has reached end of life and is unsupported (as of June 20, 2018). This issue is to bump the required version to something supported so that Autolab receives patches for security vulnerabilities as they are discovered upstream.

**Comment by scottmcampbell** [comment]
To continue this issue, I am trying to install Autolab via the install script on Ubuntu Server 18.04 LTS. I had to update one of the packages installed in the setup.sh (line 105) from libgdbm3 to libgdbm5. I get the following error and the install never completes:

Installing ruby-2.2.2...

WARNING: ruby-2.2.2 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.

I tried updating the .ruby-version from 2.2.2 to 2.5.1 but I get lost in the rbenv section. I also tried this on Ubuntu 14.04 and it got further but never finished. I would be happy to help in any way, hoping to implement this for our programming courses next fall.

**Comment by scottmcampbell** [comment]
Ubuntu Server 14.04, no upgrades before running the setup script. Note I ran the script over the previous version to get this text. The installer fails with this error message:

Fetching: bundler-2.0.1.gem (100%)
ERROR:  Error installing bundler:
	bundler requires Ruby version >= 2.3.0.
Failed command: gem install bundler

Entire text of install below.
```
Upgrading system packages and installing prerequisites...
Cloning Autolab repo from Github to ~/Autolab...
Directoy ~/Autolab already exists... Do you want to overwrite it? [y/N] y
Cloning into '/home/sclient/Autolab'...
remote: Enumerating objects: 258, done.
remote: Counting objects: 100% (258/258), done.
remote: Compressing objects: 100% (187/187), done.
remote: Total 13896 (delta 140), reused 140 (delta 69), pack-reused 13638
Receiving objects: 100% (13896/13896), 4.36 MiB | 0 bytes/s, done.
Resolving deltas: 100% (9633/9633), done.
Checking connectivity... done.
Cloning Rbenv repo from Github to ~/.rbenv...
Directoy ~/.rbenv already exists... Do you want to overwrite it? [y/N] y
Cloning into '/home/sclient/.rbenv'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 2752 (delta 2), reused 5 (delta 0), pack-reused 2744
Receiving objects: 100% (2752/2752), 526.22 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1722/1722), done.
Checking connectivity... done.
Setting up Rbenv...
Cloning ruby-build repo from Github to ~/.rbenv/plugins/ruby-build...
Cloning into '/home/sclient/.rbenv/plugins/ruby-build'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 9691 (delta 16), reused 39 (delta 10), pack-reused 9646
Receiving objects: 100% (9691/9691), 2.05 MiB | 0 bytes/s, done.
Resolving deltas: 100% (6310/6310), done.
Checking connectivity... done.
Installing Ruby 2.2.2 for Autolab...
Downloading ruby-2.2.2.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.2.tar.bz2
Installing ruby-2.2.2...

WARNING: ruby-2.2.2 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.

Installed ruby-2.2.2 to /home/sclient/.rbenv/versions/2.2.2

Installing SQLite with apt-get...
Installing MySQL Server...
\nIt appears that MySQL Server already exists on your system. Want to skip to configuration? [Y/n] n
Attempting to install MySQL Server on top of existing one...
Your randomly-generated root password for MySQL server is: XXXXXXXXXXXXXXXXXXXXXXXXXXXX. Please keep the password in a safe place for future use.
Press any key to continue the installation...
Installing necessary gems for Autolab...
Fetching: bundler-2.0.1.gem (100%)
ERROR:  Error installing bundler:
	bundler requires Ruby version >= 2.3.0.
Failed command: gem install bundler

ERROR: Line 177 of script has return value 1. The log file is saved at /tmp/tmp.5ovqKDYHrL.

Thank you for trying out Autolab! For questions and comments, email us at autolab-dev@andrew.cmu.edu.

As a final reminder, your MySQL root password is: XXXXXXXXXXXXXXXXXXXXXXXXXXXX.
```

**Comment by bsantraigi** [comment]
@scottmcampbell I was able to go past this checkpoint by mentioning the version for bundler gem to be installed. Clone Autolab locally, change the following line in `setup.sh-> rails_setup()` function definition, 
`gem install bundler -v 1.17.3`

Then execute this local version of setup.sh.

**Comment by oliverli** [comment]
As part of our migration to Rails 5, Ruby has been upgraded to version `2.6.3`. This release is now available in `master`
