### ISSUE TITLE
Submission is not graded when uploaded; requires manual trigger

### ISSUE THREAD

**Issue by datamove** [autolab/Autolab#1014]
Dear Developers,
I installed one-click, setup a homework, and can trigger grading manually via the admin interface. However I don't understand how can a submission be queued for grading as soon as it's uploaded by a student. 
Could you please advise?
Thanks!

**Comment by TheodorJ** [comment]
Hi @datamove, Autolab uses an autograding backend called Tango (https://github.com/autolab/Tango) that receives the submission from the Autolab frontend when a student submits an assignment. I'm not sure why the frontend needs manual triggering -- does the frontend have a connection to Tango?

**Comment by datamove** [comment]
Ok, this is related to

https://github.com/autolab/Autolab/issues/995

During "local" one click install, autograde.rb is overwritten by the version in the cover folder, in which sendJob_AddHtml... is replaced with autogradeSubmissions.

Hence, handin is saved to the server, but autograding is not triggered (instead a user gets 500 error).

handin.rb requires a trivial patch to replace above function calls.

**Comment by victorhuangwq** [comment]
One click is deprecated, and will be replaced by a docker based implementation in the future. closing this issue soon.
