### ISSUE TITLE
Checkboxes aren't visible (rails-5-upgrade)

### ISSUE THREAD

**Issue by bernstdh** [autolab/Autolab#1038]
Except for the submission page, no checkboxes are visible. This includes the checkboxes for "Disable Handins", "Unofficial Submissions", "Exam in Progress", and "Enroll Users".

**Comment by fanpu-asana** [comment]
Can I check that this is for the master branch?

**Comment by fanpu** [comment]
Could I check which branch you are facing this on? There were some UI breakages from upgrading Material for the `rails-5-upgrade` branch that is a WIP but if it broke on `master` this would warrant more attention.

**Comment by bernstdh** [comment]
It was broken on the rails-5-upgrade branch. We know it's a WIP,

**Comment by oliverli** [comment]
I believe the issues have been fixed as `rails-5-upgrade` has been merged to master

Let me know/open another issue if it isn't
