### ISSUE TITLE
Strange behavior of tabs on "Edit Assessment" page (rails-5-upgrade)

### ISSUE THREAD

**Issue by bernstdh** [autolab/Autolab#1039]
This may be a feature, not a bug, but the tabs on the "Edit Assessment" page are no longer distinct pages. This makes the [Save] buttons (that used to be at the bottom of each page) difficult to find and difficult to interpret.

**Comment by fanpu** [comment]
This is a bug, we are planning to fix it

**Comment by XtrKiL** [comment]
We have fixed the tab issue in the rails-5-upgrade branch. So I am going to close this.
