### ISSUE TITLE
One-click install fails on Docker 19/20

### ISSUE THREAD

**Issue by tmayberry** [autolab/Autolab#1043]
Hi, I am trying to install Autolab and I get the following error consistently on step 19/20 of initializing Docker containers.  Some googling suggests that this is a common problem with UglifyJS when trying to parse ES6 but I don't know why I am getting it here.

Step 19/20 : RUN RAILS_ENV=production bundle exec rake assets:precompile
 ---> Running in 32c5de21357d
I, [2019-08-04T17:51:22.699122 #6]  INFO -- : Writing /home/app/webapp/public/assets/animate-01b874b4bcbe82b29ae58740fea5d3ee62a96424eb7a8edd56184ee9caaa2de8.css
I, [2019-08-04T17:51:22.720156 #6]  INFO -- : Writing /home/app/webapp/public/assets/animate-01b874b4bcbe82b29ae58740fea5d3ee62a96424eb7a8edd56184ee9caaa2de8.css.gz
I, [2019-08-04T17:51:23.591893 #6]  INFO -- : Writing /home/app/webapp/public/assets/style-4ab6f8ee306fd42c925d48c3022f52171bc3edb934b14bf4b27047eb64145f96.css
I, [2019-08-04T17:51:23.592159 #6]  INFO -- : Writing /home/app/webapp/public/assets/style-4ab6f8ee306fd42c925d48c3022f52171bc3edb934b14bf4b27047eb64145f96.css.gz
I, [2019-08-04T17:51:23.595143 #6]  INFO -- : Writing /home/app/webapp/public/assets/1-09cf5b4871b59e1590804793977c5576e4949bc2b91c8b6152fed57701a6cdd6.gif
I, [2019-08-04T17:51:23.597805 #6]  INFO -- : Writing /home/app/webapp/public/assets/AUTOLAB-95849830cff8a21c14f0af570966783d7f878051e73055ad25da542651932a81.png
I, [2019-08-04T17:51:23.600410 #6]  INFO -- : Writing /home/app/webapp/public/assets/AUTOLAB@2x-df4fd023ed256b3d2a1cbb5373e378d1c0dec6ea2adbe1511ac73385155c5bc8.png
I, [2019-08-04T17:51:23.603702 #6]  INFO -- : Writing /home/app/webapp/public/assets/DonkeyKong-fc077b5d5666de64ecfe17328dfdc9deec1adf23d9a3d15a180f6b6b0ce80a58.jpg
I, [2019-08-04T17:51:23.606166 #6]  INFO -- : Writing /home/app/webapp/public/assets/arrow-c2cfa8d10e2e64d5afc3ca18508b074cd12a9744e32a1836392ed8daddd01b5b.png
I, [2019-08-04T17:51:23.608496 #6]  INFO -- : Writing /home/app/webapp/public/assets/arrowDown-9d284c405e115dbee790e766f527573538b8b089e55c04f28d81b45a6ed979aa.png
I, [2019-08-04T17:51:23.610929 #6]  INFO -- : Writing /home/app/webapp/public/assets/arrowRight-f554ed828754d3e51d6803ee9724d8f1bf587fba9371048c85fb1e52168c8285.png
I, [2019-08-04T17:51:23.613615 #6]  INFO -- : Writing /home/app/webapp/public/assets/autolab-c2c852cd48ec091632c43939af5af27b0f774cff3c541e54750163d84fd6b59c.ico
I, [2019-08-04T17:51:23.614049 #6]  INFO -- : Writing /home/app/webapp/public/assets/autolab-c2c852cd48ec091632c43939af5af27b0f774cff3c541e54750163d84fd6b59c.ico.gz
I, [2019-08-04T17:51:23.616772 #6]  INFO -- : Writing /home/app/webapp/public/assets/back-7f2a6b442b9bfbb8eb46a177e69d5cb651d853f105ecb2fa51ac17b770cfd913.png
I, [2019-08-04T17:51:23.619372 #6]  INFO -- : Writing /home/app/webapp/public/assets/check_spelling-367b16e5dbc0c57af7c5287477f4072bc3bf27631d3d51b1e5379bd7c9e293e7.png
I, [2019-08-04T17:51:23.621932 #6]  INFO -- : Writing /home/app/webapp/public/assets/chosen-sprite-8aa69ee6b2376505578d758bfbbc52aec88fa5e591f1a7cabd8adfa80a7b613a.png
I, [2019-08-04T17:51:23.624322 #6]  INFO -- : Writing /home/app/webapp/public/assets/chosen-sprite@2x-1e349b80fba8c23b63656925fda8dfe3c5927b5d0d8a1672143416caacf460fb.png
I, [2019-08-04T17:51:23.626702 #6]  INFO -- : Writing /home/app/webapp/public/assets/cmu-header-3e06bb9a3ad8883d1ec03a3e211ffd844e9ff4ce1bd517b15817fd473c27b3e8.gif
I, [2019-08-04T17:51:23.629758 #6]  INFO -- : Writing /home/app/webapp/public/assets/donkeyKongTheBuilder-e55359ef7d367a9205dba18c7df1f18c069fde7815b598108957c1ec7dcfd90b.png
I, [2019-08-04T17:51:23.641782 #6]  INFO -- : Writing /home/app/webapp/public/assets/donkey_kong_lost-21eed42bd5dcaae39937ab6b8cea2fe57e5ee5df08a93e39349431df2484b827.jpg
I, [2019-08-04T17:51:23.644280 #6]  INFO -- : Writing /home/app/webapp/public/assets/download-eea664cd518c39762d4da91bb6faa3ca2366d89acc5ddbe8f1eea72214a5d305.png
I, [2019-08-04T17:51:23.646624 #6]  INFO -- : Writing /home/app/webapp/public/assets/downloadUp-f0237102003d2d65d9aa577f50861eac8d5887c924183e80707a08f506c38efc.png
I, [2019-08-04T17:51:23.649017 #6]  INFO -- : Writing /home/app/webapp/public/assets/function_icon-de5a8d12284a16db81a7586aeaa15af53f95d98a89789f177a9a5708654e25ae.svg
I, [2019-08-04T17:51:23.649223 #6]  INFO -- : Writing /home/app/webapp/public/assets/function_icon-de5a8d12284a16db81a7586aeaa15af53f95d98a89789f177a9a5708654e25ae.svg.gz
I, [2019-08-04T17:51:23.652382 #6]  INFO -- : Writing /home/app/webapp/public/assets/glyphicons-halflings-aaa-e917f0cf959d5979df1ad34b8f23bdcf8f2fe5eb5f1cea9680c940c86497b0ae.png
I, [2019-08-04T17:51:23.654726 #6]  INFO -- : Writing /home/app/webapp/public/assets/glyphicons-halflings-white-f0e0d95a9c8abcdfabf46348e2d4285829bb0491f5f6af0e05af52bffb6324c4.png
I, [2019-08-04T17:51:23.657305 #6]  INFO -- : Writing /home/app/webapp/public/assets/glyphicons-halflings-d99e3fa32c641032f08149914b28c2dc6acf2ec62f70987f2259eabbfa7fc0de.png
I, [2019-08-04T17:51:23.659605 #6]  INFO -- : Writing /home/app/webapp/public/assets/go-new-5803cb6e45a959622aaeee4911bd9c27c367491a245c21cc9069c3b7ac483a22.png
I, [2019-08-04T17:51:23.661850 #6]  INFO -- : Writing /home/app/webapp/public/assets/go-new_hightlighted-b3907278831d33cd4998c78fdfc41bed26b8169c45f9d1267303d8e1a2abd37b.png
I, [2019-08-04T17:51:23.664154 #6]  INFO -- : Writing /home/app/webapp/public/assets/go-5803cb6e45a959622aaeee4911bd9c27c367491a245c21cc9069c3b7ac483a22.png
I, [2019-08-04T17:51:23.666369 #6]  INFO -- : Writing /home/app/webapp/public/assets/go_hightlighted-b3907278831d33cd4998c78fdfc41bed26b8169c45f9d1267303d8e1a2abd37b.png
I, [2019-08-04T17:51:23.668594 #6]  INFO -- : Writing /home/app/webapp/public/assets/keyboard-99a38b5fb17ddabd9c32f720fe0443b48181ea426f5551eaf0f5d0599811e0e8.png
I, [2019-08-04T17:51:23.670838 #6]  INFO -- : Writing /home/app/webapp/public/assets/logo-796af9525ec60e1eae65d66b7e59718b0b32a9f34fcfc5b90ed36a0176e623d7.svg
I, [2019-08-04T17:51:23.671108 #6]  INFO -- : Writing /home/app/webapp/public/assets/logo-796af9525ec60e1eae65d66b7e59718b0b32a9f34fcfc5b90ed36a0176e623d7.svg.gz
I, [2019-08-04T17:51:23.673612 #6]  INFO -- : Writing /home/app/webapp/public/assets/popover-arrow-35697ce6806b9e904322ab1d000843584285ec02bb2ef6b7e341bd60654088be.png
I, [2019-08-04T17:51:23.675859 #6]  INFO -- : Writing /home/app/webapp/public/assets/rails-5ad6d454af23f597c4c39dbe4ec6e12784f8e382997a4bc04944ab8547d48881.png
I, [2019-08-04T17:51:23.678124 #6]  INFO -- : Writing /home/app/webapp/public/assets/score_error-759d01707be50510d211f865e7c36303a603fb6331d8ba2faf3887b2b27bce8b.png
I, [2019-08-04T17:51:23.680388 #6]  INFO -- : Writing /home/app/webapp/public/assets/spinner-41efb233cba0cfc5fb3f22f3838722ae301f1523a5e1b8009f8839ca7d71a6bb.gif
I, [2019-08-04T17:51:23.680825 #6]  INFO -- : Writing /home/app/webapp/public/assets/upload-4f8218f23d02a1573084cdbfe7ca6c8a64365e1da3bb9f633c7df3b9810e72bb.png
I, [2019-08-04T17:51:23.681350 #6]  INFO -- : Writing /home/app/webapp/public/assets/upload_highlighted-af60b86351c63bc3d5131bafa367f4e16601b20391382bf9dd506d59fbfc58c2.png
I, [2019-08-04T17:51:23.683951 #6]  INFO -- : Writing /home/app/webapp/public/assets/x-d46c0a1fd715a3b29ac80d94880915058f3504348c20b6839607a78b2b3312b3.png
I, [2019-08-04T17:51:23.837013 #6]  INFO -- : Writing /home/app/webapp/public/assets/SlickGrid/2.02/controls/slick.columnpicker-bd5ae6b3c61041bde9c541794adabf22f9b8136cc2bc884b6dbc21679dc01ac3.js
I, [2019-08-04T17:51:23.837189 #6]  INFO -- : Writing /home/app/webapp/public/assets/SlickGrid/2.02/controls/slick.columnpicker-bd5ae6b3c61041bde9c541794adabf22f9b8136cc2bc884b6dbc21679dc01ac3.js.gz
I, [2019-08-04T17:51:23.910306 #6]  INFO -- : Writing /home/app/webapp/public/assets/SlickGrid/2.02/slick.core-7bf48b446f60f00eab1c89999e6bd6a2555cd4a5f69ba1d3fe57a7b8ffa979c6.js
I, [2019-08-04T17:51:23.910477 #6]  INFO -- : Writing /home/app/webapp/public/assets/SlickGrid/2.02/slick.core-7bf48b446f60f00eab1c89999e6bd6a2555cd4a5f69ba1d3fe57a7b8ffa979c6.js.gz
I, [2019-08-04T17:51:24.148490 #6]  INFO -- : Writing /home/app/webapp/public/assets/SlickGrid/2.02/slick.dataview-a32a87e95b5dd33b2a8ad2e87b665792fddec58d2686293d9648edfb85e41e06.js
I, [2019-08-04T17:51:24.148649 #6]  INFO -- : Writing /home/app/webapp/public/assets/SlickGrid/2.02/slick.dataview-a32a87e95b5dd33b2a8ad2e87b665792fddec58d2686293d9648edfb85e41e06.js.gz
I, [2019-08-04T17:51:24.971599 #6]  INFO -- : Writing /home/app/webapp/public/assets/SlickGrid/2.02/slick.grid-53e48a2b87db969223f2a5bcc06b54f94d3e7136beb8650bfca0ce18748a3a6e.js
I, [2019-08-04T17:51:24.971758 #6]  INFO -- : Writing /home/app/webapp/public/assets/SlickGrid/2.02/slick.grid-53e48a2b87db969223f2a5bcc06b54f94d3e7136beb8650bfca0ce18748a3a6e.js.gz
rake aborted!
ExecJS::ProgramError: SyntaxError: Unexpected token: name (el) (line: 208, col: 6, pos: 6153)

Error
    at new JS_Parse_Error (<eval>:3623:11948)
    at js_error (<eval>:3623:12167)
    at croak (<eval>:3623:22038)
    at token_error (<eval>:3623:22175)
    at unexpected (<eval>:3623:22263)
    at semicolon (<eval>:3623:22781)
    at simple_statement (<eval>:3623:25959)
    at <eval>:3623:23747
    at <eval>:3623:22954
    at block_ (<eval>:3623:28083)
new JS_Parse_Error ((execjs):3623:11948)
js_error ((execjs):3623:12167)
croak ((execjs):3623:22038)
token_error ((execjs):3623:22175)
unexpected ((execjs):3623:22263)
semicolon ((execjs):3623:22781)
simple_statement ((execjs):3623:25959)
(execjs):3623:23747
(execjs):3623:22954
block_ ((execjs):3623:28083)
/var/lib/gems/2.2.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:47:in `rescue in block in call'
/var/lib/gems/2.2.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:44:in `block in call'
/var/lib/gems/2.2.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:75:in `block in lock'
/var/lib/gems/2.2.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:73:in `call'
/var/lib/gems/2.2.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:73:in `Locker'
/var/lib/gems/2.2.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:73:in `lock'
/var/lib/gems/2.2.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:43:in `call'
/var/lib/gems/2.2.0/gems/uglifier-3.0.4/lib/uglifier.rb:184:in `run_uglifyjs'
/var/lib/gems/2.2.0/gems/uglifier-3.0.4/lib/uglifier.rb:146:in `compile'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/uglifier_compressor.rb:53:in `call'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/uglifier_compressor.rb:28:in `call'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `yield'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:142:in `block in find'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `each'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `each'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `logical_paths'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:140:in `find'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
/var/lib/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/var/lib/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/var/lib/gems/2.2.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
V8::Error: SyntaxError: Unexpected token: name (el)
at js_error (<eval>:3623:12167)
at croak (<eval>:3623:22038)
at token_error (<eval>:3623:22175)
at unexpected (<eval>:3623:22263)
at semicolon (<eval>:3623:22781)
at simple_statement (<eval>:3623:25959)
at <eval>:3623:23747
at <eval>:3623:22954
at block_ (<eval>:3623:28083)
at ctor.body (<eval>:3623:27686)
at function_ (<eval>:3623:27782)
at <eval>:3623:24469
at <eval>:3623:22954
at <eval>:3624:3759
at parse (<eval>:3624:3999)
at parse (<eval>:3958:22)
at uglifier (<eval>:4003:13)
/var/lib/gems/2.2.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:45:in `block in call'
/var/lib/gems/2.2.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:75:in `block in lock'
/var/lib/gems/2.2.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:73:in `call'
/var/lib/gems/2.2.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:73:in `Locker'
/var/lib/gems/2.2.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:73:in `lock'
/var/lib/gems/2.2.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:43:in `call'
/var/lib/gems/2.2.0/gems/uglifier-3.0.4/lib/uglifier.rb:184:in `run_uglifyjs'
/var/lib/gems/2.2.0/gems/uglifier-3.0.4/lib/uglifier.rb:146:in `compile'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/uglifier_compressor.rb:53:in `call'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/uglifier_compressor.rb:28:in `call'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `yield'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:142:in `block in find'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `each'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `each'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `logical_paths'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:140:in `find'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
/var/lib/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/var/lib/gems/2.2.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/var/lib/gems/2.2.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
ERROR: Service 'web' failed to build: The command '/bin/sh -c RAILS_ENV=production bundle exec rake assets:precompile' returned a non-zero code: 1
Failed command: congrats() {

ERROR: Line 180 of script has return value 1. The log file is saved at /tmp/tmp.rDgGGtGHXk.

**Comment by mtoupsUNO** [comment]
I was able to fix this problem with this patch:

https://github.com/mtoupsUNO/Autolab/commit/dbec095ebd7daa231915c897e94e7ea3c81f7fa9

I think this may also be fixed in the `rails-5-upgrade` branch (which also has some outstanding UI bugs, but may be more likely to finish installation on a current OS version)

**Comment by fanpu** [comment]
Fixed with new Docker Compose install, see https://docs.autolabproject.com/docker-compose/
