### ISSUE TITLE
documentation clarification

### ISSUE THREAD

**Issue by dar326** [autolab/Autolab#1045]
Hello,

I just completed the process of installing Autolab on macOS. I ran into an issue in the process due to an issue with the formatting of the instructions. In step 11 of the "Mac OSX 10.11+" instructions, the second command to run is `bundle exec rake db:migrate`. However, this command is not highlighted and looks like normal text which makes it easy to overlook. Wanted to suggest highlighting the command like the db:create command above it to ensure it is noticed by others attempting to install Autolab.

Best,
Darryl

**Comment by fanpu** [comment]
Fixed in https://github.com/autolab/docs/pull/21 thanks to @oliverli
