### ISSUE TITLE
Uglifier 3.0.4 cannot compress slickgrid properly (in production mode)

### ISSUE THREAD

**Issue by wlnirvana** [autolab/Autolab#1046]
It seems the slickgrid js library uses some ES6 syntax, causing uglifier to throw the following error
 during assets precompiling.

```
SyntaxError: Unexpected token: name (el)
```

Upgrading to 3.2.0 resolved the issue.

**Comment by wlnirvana** [comment]
Yeah I forgot to mention exactly that. Thanks for the update @travers-rhodes :+1:

**Comment by copperx** [comment]
> It seems the slickgrid js library uses some ES6 syntax, causing uglifier to throw the following error
> during assets precompiling.
> 
> ```
> SyntaxError: Unexpected token: name (el)
> ```
> 
> Upgrading to 3.2.0 resolved the issue.

Do you mind explaining how to tell the Docker image to run bundle install after changing Gemfile.lock to update uglifier?

**Comment by wlnirvana** [comment]
@copperx Sorry I was using a manual installation of Autolab, not the docker version.

**Comment by wlnirvana** [comment]
Closed by #1144
