### ISSUE TITLE
Emojis in group name gives a 500 error

### ISSUE THREAD

**Issue by RyChrome** [autolab/Autolab#1061]
Tried to make the name of a group "🅱️ig 🅱️ois" and it gave me a 500. Sad!

**Comment by XtrKiL** [comment]
May I know what group are you referring to? If possible, could you point out the specific page that you are seeing this error?

**Comment by cg2v** [comment]
This is caused by using the utf8/utf8mb3 character encoding in mysql as opposed to utf8mb4.
https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb3.html

https://stackoverflow.com/questions/10957238/incorrect-string-value-when-trying-to-insert-utf-8-into-mysql-via-jdbc

**Comment by cg2v** [comment]
https://railsmachine.com/articles/2017/05/19/converting-a-rails-database-to-utf8mb4.html

**Comment by RyChrome** [comment]
@XtrKiL group names

**Comment by victorhuangwq** [comment]
Closing issue as it is more of a user database issue.
