### ISSUE TITLE
Scoreboards should be sortable

### ISSUE THREAD

**Issue by ymzong** [autolab/Autolab#108]
Scoreboards should be sortable by columns (including submission timestamp, and points).

See old Autolab scoreboard for example.

**Comment by Z1MM32M4N** [comment]
I think I have a fix for this, but I can't test it. Is there a way to have the auto-populated local data include an assessment with a scoreboard?

**Comment by dlbucci** [comment]
Can't you just enable scoreboards in the edit assessment page?

**Comment by dlbucci** [comment]
Also, I don't think this necessarily refers to clicking the TH and having the table get resorted.  Rather, instructors want to be able to define how the table is always sorted (like, first by highest score, then first submission.  Or for datalab, fewest instructions, then first submission).
