### ISSUE TITLE
Time defaulting to UTC on Firefox

### ISSUE THREAD

**Issue by ThePfaffanater** [autolab/Autolab#1091]
While only on Firefox(v72.0.2) deadlines are displayed in UTC. In chromium(v79.0.3945.130) the proper EST deadline is displayed. This is not an issue with extensions or Firefox versioning as the issue persists on multiple versions of Firefox in and out of safe mode. The Host OS is Linux but as far as I know that should not impact this. 

I found this file that seems to be causing it. 
https://github.com/autolab/Autolab/blob/63a9f8699b6cabeac5812f0156ee60350759154f/app/assets/javascripts/app-level.js

It seems to grab the un-formatted date, format it with moment.js, and send it to all "moment-date-time" classes. From what I can tell this seem to do the trick for local time on chromium. But since moment.js is already being used, moment.js can take the raw format and convert it to local to ensure it works everywhere. I am unsure if this is a problem with Firefox itself but either way; Using: 
`var formattedDate = moment(unformattedDate, "YYYY-MM-DD hh:mm:ss ZZ").local().format(format);`
instead of just: 
`var formattedDate = moment(unformattedDate, "YYYY-MM-DD hh:mm:ss ZZ").format(format);`
Should fix this.

**Comment by fanpu** [comment]
Hey @ThePfaffanater, thank you for flagging this issue to us! We will be looking into it shortly.

**Comment by ThePfaffanater** [comment]
Issue seems to be that Firefox had privacy.resistFingerprinting set to True by default. Setting that to false appears to fix the issue. I have no Idea why this was set true by default. It could not have been an extension since they no longer have access to about:config. Perhaps a method of localizing timezones that works despite privacy.resistFingerprinting  being set to true should be pursued if it is going to become default. Its also weird that this also happened in safe mode. 

I also had a problem with understanding how the timezone was being formated in the first place. The only place it can be formatted is in [app-level.js](https://github.com/autolab/Autolab/blob/63a9f8699b6cabeac5812f0156ee60350759154f/app/assets/javascripts/app-level.js) who is only mentioned in [application.js](https://github.com/autolab/Autolab/blob/63a9f8699b6cabeac5812f0156ee60350759154f/app/assets/javascripts/application.js) . But that file is completely commented out. Also even app-level.js is looking for an attribute of "format" that is not on anything and thus making moment fall back to an invalid format that should result in the return of "Invalid date." 
If that code block gets run on those spans it would look like this: moment("May 8th 2020, 11:59 pm", "YYYY-MM-DD hh:mm:ss ZZ").format("YYYY-MM-DD HH:mm:ss") which returns "Invalid date" since "May 8th 2020, 11:59 pm" is not in the format "YYYY-MM-DD hh:mm:ss ZZ"

So where is the date being changed? Since this code in app-level.js is the only .js that references the class "moment-date-time" and it is not even valid code?

**Comment by fanpu** [comment]
We will KIV this issue and take a look at it again in the future as we are currently focusing on bug fixing for the rails-5-upgrade branch. Thank you @ThePfaffanater and @amartinez116 for investigating this!
