### ISSUE TITLE
Frequently experiences "*** [run] Segmentation fault (core dumped)"

### ISSUE THREAD

**Issue by gadusing** [autolab/Autolab#1098]
Issue arises without explanation during .c file testing. Files may execute correctly and without memory leaks on ux server, yet Autolab cannot.

**Comment by gadusing** [comment]
Issue arises without explanation during .c file testing.  Files may execute correctly and without memory leaks on ux server, yet Autolab cannot.

**Comment by victorhuangwq** [comment]
Context not clear. Will close this issue. If you still face the issue that you have mentioned, do file the issue again using our new bug report template so we can understand the context better :)
