### ISSUE TITLE
undefined local variable or method `tango' for main:Object

### ISSUE THREAD

**Issue by Mat2095** [autolab/Autolab#1136]
I'm trying to setup Autolab with Docker as described in the documentation "Docker (Development) (rails-5-docker-dev)"

I'm using a VM with Ubuntu 18.04.4, install the latest updates plus git, docker.io and docker-compose.
After the setup as per documentation I run `docker exec <CONTAINER-ID> bundle exec rake autolab:populate`.
I log in with admin@foo.bar via dev-login.
The site looks fine, but if I try to go to the autopopulated course, I get this error:

> undefined local variable or method `tango' for main:Object
> Rails.root: /home/app/autolab
> 
> config/autogradeConfig.rb:6:in \`<top (required)>'
> lib/tango_client.rb:3:in \`<top (required)>'
> app/controllers/assessment/autograde.rb:2:in \`<top (required)>'
> app/controllers/application_controller.rb:50:in \`autolab_require'
> app/controllers/assessments_controller.rb:24:in \`<class:AssessmentsController>'
> app/controllers/assessments_controller.rb:8:in \`<top (required)>'

This happens for the course-page and the assessment-pages, but the grade-section does work fine.
Did I mess up something with the setup?

**Comment by oliverli** [comment]
Yep, I can replicate the issue.

Seems that `tango` in line 6 of `config/autogradeConfig.docker-dev.rb` is undefined. I'm not fully sure where that was supposed to be defined - I think it's a WIP that was stopped halfway through. In the meantime I'm going to remove the docker instructions from the documentation to avoid more confusion.

For some context, the work on Docker is part of an overall effort to bring the infrastructure up to date. Right now the focus has shifted towards bringing Rails (and gem dependencies) up to date, as well as bringing Tango from Python 2 to Python 3. Once that has settled down, we will resume work on Docker again, with the goal of Dockerising all aspects of the infrastructure

**Comment by fanpu** [comment]
Fixed with new Docker Compose install, see https://docs.autolabproject.com/docker-compose/
