### ISSUE TITLE
SlickGrid was not declared to be precompiled

### ISSUE THREAD

**Issue by Mat2095** [autolab/Autolab#1137]
I'm still trying to get an Autolab instance running.
I've tried the manual setup (not using Docker) on a fresh Ubuntu 18.04.4 VM as described in the documentation.

There were two minor problems during the setup:
- the documentation says you should install prerequisites with `sudo apt-get install build-essential git libffi-dev zlib1g-dev autoconf bison build-essential libssl1.0-dev libyaml-dev libreadline6-dev libncurses5-dev libgdbm5 libgdbm-dev libmysqlclient-dev libjansson-dev ctags`; this resulted in this error:
  > The following packages have unmet dependencies:
  > libmysqlclient-dev : Depends: libssl-dev (>= 1.1.1-1ubuntu2.1\~18.04.5\~) but it is not going to be installed

  therefore I changed `libssl1.0-dev` to `libssl-dev`
- the YAML config is missing indentation, so I couldn't just copy-paste it

When everything was running, I logged in as admin@foo.bar with the dev-login.
Then I went to the grade-section of the auto-populated course and got this error:
> Sprockets::Rails::Helper::AssetNotPrecompiled at /courses/AutoPopulated/course_user_data/1/gradebook/view
> 
> Asset `SlickGrid/2.02/slick.grid.css` was not declared to be precompiled in production.
> Declare links to your assets in `app/assets/config/manifest.js`.
> 
>   //= link SlickGrid/2.02/slick.grid.css
> and restart your server

![ClipboarderTemp-24b0e6d](https://user-images.githubusercontent.com/11258252/80407447-efb87700-88c5-11ea-987d-8af0884fe73f.png)

**Comment by oliverli** [comment]
Thanks for bringing this up! This was an issue we overlooked when we upgraded our gem dependencies a week ago. It has been fixed with a new PR (#1130) that has just been merged into `master`. Could you try pulling the latest version of `master` and viewing the gradebook again?

**Comment by oliverli** [comment]
Thanks for the feedback on the documentation - it's been updated!

**Comment by Mat2095** [comment]
Thank you for your quick help, I can confirm that all problems are gone!
