### ISSUE TITLE
Bulk Upload Grades gives 404 upon upload

### ISSUE THREAD

**Issue by ymzong** [autolab/Autolab#114]
Ben:

> I am trying to bulk upload grades from a CSV file. I select the bulk import option, select my file, and then click the "Start" button. This results in a 404 for the url https://autolab.cs.cmu.edu/courses/xx/assessments/yy/bulkGrade. Repeating the same steps on a different assignment also 404s.

**Comment by dlbucci** [comment]
This is probably just because the 'bulkGrade' route only accepts GET requests and the upload is a POST.  You can fix it in config/routes.rb.

**Comment by ymzong** [comment]
@dlbucci That's the issue on the surface, and actually the underlying code needs to be changed too because of the `user` -> `cud` migration we had before.
