### ISSUE TITLE
production.rb.template requires some updates

### ISSUE THREAD

**Issue by cg2v** [autolab/Autolab#1142]
1. config.assets.js_compressor = :uglifier
doesn't work for some of the new syntax. As mentioned in #1046, Uglifier.new(harmony: true) is required
1. config.assets.precompile << /(^[^_\/]|\/[^_])[^\/]*$/
is not supported in sprockets v4. See https://github.com/rails/sprockets-rails/issues/269

**Comment by fanpu** [comment]
Hey @cg2v, thanks for bringing this up! I've created a fix on https://github.com/autolab/Autolab/pull/1144, if it's alright with you could I assign you as the reviewer?

**Comment by fanpu** [comment]
Fixed in https://github.com/autolab/Autolab/pull/1144
