### ISSUE TITLE
Student Job Status page broken

### ISSUE THREAD

**Issue by ymzong** [autolab/Autolab#116]
(Possible issue: `jobs_controller.rb:156-157`)

To reproduce the bug:
- Go to any course like: https://milkshark.ics.cs.cmu.edu/courses/14/jobs;
- Sudo as a student with submission and go back to the `jobs` page above;
- Click on a job status link to view feedback.

But oops,
```
--- !ruby/exception:ActionController::UrlGenerationError
message: No route matches {:action=>"viewFeedback", :controller=>"49", :course_id=>"14",
  :feedback=>1, :id=>"380", :submission=>"864"}
```

**Comment by dlbucci** [comment]
Is this a duplicate of #41?

**Comment by ymzong** [comment]
@dlbucci That's right. Closing this.
