### ISSUE TITLE
Checkbox hidden

### ISSUE THREAD

**Issue by wlnirvana** [autolab/Autolab#1168]
Not sure if checkboxes on other pages are intentionally hidden, but the first column of the table on page http://autolab.ml/courses/AutoPopulated/assessments/lab0/submissions is invisible checkboxes. Sort of inconvenient.

Possible root cause: https://github.com/mkhairi/materialize-sass/blob/ebb0543d72fee08053a7df2d24fd4c1f15542fb2/assets/stylesheets/materialize/components/forms/_checkboxes.scss#L8

**Comment by wlnirvana** [comment]
According to their doc/demo https://materializecss.com/checkboxes.html it seems a `<span>` is needed after the `<input>`.

**Comment by victorhuangwq** [comment]
Hi @wlnirvana. Thank you for pointing this out. This is an issue caused by our materialise upgrade, and we tried to fix all of the checkbox, but it seems like we have missed this one. We know how to address this so leave this to us.

**Comment by victorhuangwq** [comment]
Hi just a quick update, fixing the checkbox is easy, but it doesn't seem as if the checkbox is serving any purpose. Will have to take a look closer again.
