### ISSUE TITLE
Regrade button not working

### ISSUE THREAD

**Issue by wlnirvana** [autolab/Autolab#1169]
**Please note that this issue does not occur to the public demo site, which seems using an old version (prior to [this commit](https://github.com/autolab/Autolab/commit/82972aa0b69dae32eca07d2971bd314998bca295)) of Autolab shadowing this issue with another bug.**

For autograded assignment, the regrade button on `your.autolab.domain/courses/AutoPopulated/assessments/hello/submissions` page sends http get request instead post request, causing a routing error.

This might be a regression introduced in #845 and further #856

**Comment by wlnirvana** [comment]
Autolab relies on jquery-ujs to support http post request based on`data-method` attribute of `<a>` elements, which [internally uses](https://github.com/rails/jquery-ujs/blob/9e805c90c8cfc57b39967052e1e9013ccb318cf8/src/rails.js#L430) jQuery's `on` method to attach handlers to `<a>` listening for clicks.

Quoting from [jQuery doc](https://api.jquery.com/on/):

> When a selector is provided, the event handler is referred to as delegated. The handler is not called when the event occurs directly on the bound element, but only for descendants (inner elements) that match the selector. jQuery bubbles the event from the event target up to the element where the handler is attached (i.e., innermost to outermost element) and runs the handler for any elements along that path matching the selector.

To summarize, the jquery-ujs handler is not directly attached to `<a>` but to the document and then delegated to `<a>`. However, changes in #845 will prevent the event from bubbling up.

**Comment by victorhuangwq** [comment]
Hi @wlnirvana I am currently doing a sweep of all the issues we are having, and there was actually an issue a while back that mentioned the same issue, and it comes with a patch at https://github.com/autolab/Autolab/issues/936. 

I am looking into it right now.

**Comment by victorhuangwq** [comment]
It should be resolved by the linked PR.
