### ISSUE TITLE
Marking students as "dropped" does not work

### ISSUE THREAD

**Issue by icanberk** [autolab/Autolab#117]

**Comment by dlbucci** [comment]
Oddly enough, this does work on my dev environment...

**Comment by icanberk** [comment]
Yeah. Same with changing the name of the of the student. Works on my dev but not prod.

**Comment by dlbucci** [comment]
Found it: course_user_data#update redirects people to edit if the nickname is blank, so editing doesn't work if there's no nickname.  You want to fix this or should I?
