### ISSUE TITLE
Materialize imported multiple times

### ISSUE THREAD

**Issue by wlnirvana** [autolab/Autolab#1174]
Encountered Dogfalo/materialize/issues/2667 while playing with Autolab, which is caused by materialized being [imported multiple times](https://github.com/Dogfalo/materialize/issues/2667#issuecomment-185546091):

https://github.com/autolab/Autolab/blob/ff1740dfdd7541c02756ebde211e5da89d51f4bb/app/assets/javascripts/application.js#L18-L19

The [doc](https://github.com/mkhairi/materialize-sass#b-javascript) actually suggests only one be used.

**Comment by oliverli** [comment]
Thanks for the heads up! I'll put in a PR very soon to address that. Could you provide an example of the button that is affected by this issue for us to replicate as well?

**Comment by wlnirvana** [comment]
@oliverli I was doing some customization to the Autolab UI and found that issue. I will try and see if any similar problem can be found on the demo site.
