### ISSUE TITLE
Assessment edit page JS error

### ISSUE THREAD

**Issue by wlnirvana** [autolab/Autolab#1182]
http://autolab.ml/courses/AutoPopulated/assessments/homework1/edit

`edit:480 Uncaught TypeError: Cannot set property 'onclick' of null`

**Comment by xinyis991105** [comment]
Hi! It seems to be working fine for me. Can you provide more details on the context that you load this page?

**Comment by wlnirvana** [comment]
If you open developer tools and then visit the link, you should see from the console an error message like aforementioned.

This can be reproduced with Firefox 76.0.1 and Chrome 81.0.4044.122 on my mac.

**Comment by xinyis991105** [comment]
Hi there! I believe a recent PR of ours has fixed this issue since the code that is causing the problem is now removed altogether. You can reference it at #1203. Thank you for reporting!
