### ISSUE TITLE
Annotate Submission view + Announcement

### ISSUE THREAD

**Issue by wallaceswsu** [autolab/Autolab#1199]
**Your environment**
 - ubuntu 18
 - Autolab commit 2ac3b7c (master as of July 28, 2020) 
 - Firefox 78 (mac)

**Steps To Reproduce**
1. Add the new "HelloCat" assessment (this probably works for all/most assessments)
2. Submit something > ~20 lines
3. Navigate to the "Annotate Submission" page for the recent submission. You can scroll down to see the entire submission (note there is no footer on the page, so the text box holding the student's code extends to the bottom of the browser frame)
4. Click "Manage Course"
5. Click "Admin Course" -> "Manage Announcements"
6. Create a *persistent* announcement
7. Navigate to the "Annotate Submission" page for the recent submission. Now the scroll box won't show all the submitted code.

**Current behavior**

Not all student code can be seen -- i.e., the view does not scroll sufficiently far. (scroll bar extent is hard to capture in a mac osx screenshot, but in both I'm scrolled as far toward the bottom as possible)

**Expected behavior**

Scroll bars have sufficient range to show all content

**Screenshots**

No Announcement (scrolled to bottom of page at step 3 above)

<img width="1181" alt="No Annoucement" src="https://user-images.githubusercontent.com/57271110/88740619-84fc1f00-d0f2-11ea-9050-f219e68e6339.png">

With Announcement (scrolled to bottom of page at step 7 above)

<img width="1181" alt="With Announcement" src="https://user-images.githubusercontent.com/57271110/88740555-5da55200-d0f2-11ea-9cd6-99457e06957e.png">

**Comment by victorhuangwq** [comment]
Hi @wallaceswsu. Thank you for the clear bug report and screenshots. It seems the code viewer does not play nice with the announcement bar. We will look into this shortly

**Comment by wallaceswsu** [comment]
@victorhuangwq Thanks for all the effort your team (and past teams) have put into Autolab!  It's really been a great tool all around.

**Comment by victorhuangwq** [comment]
@wallaceswsu I have made a quick bugfix PR to address the issue mention. Lmk if it works for you.

**Comment by mtoupsUNO** [comment]
I tested the branch `fix-announcement-codebox` and it does fix the specific issue here - the code box can now scroll to the bottom.

However I see a similar problem with the box on the far right with the scores for each problem. This only occurs with a relatively large number of problems, which is why it might not be noticed in common cases. But I have an example which may be familiar to students at CMU: 15-213's datalab (which has many puzzles within one assessment)

![image](https://user-images.githubusercontent.com/7971228/89434312-03674b00-d709-11ea-8d95-b00e6f936746.png)

We should be able to scroll down the problem list to see `logicalShift` but cannot, due to the announcement above.

**Comment by mtoupsUNO** [comment]
I added a line to `resizeCodeTable()` to deal with this, it seems to work:

` $('.problemGrades').css("max-height", $(window).height() - $(".annoucement.gray-box").height() - 262);`

I determined 262 worked using some trial and error. It doesn't seem any more arbitrary than the 250 above it.

**Comment by mtoupsUNO** [comment]
Using the additional line in `annotations.js` as mentioned above:

![image](https://user-images.githubusercontent.com/7971228/89436061-4fb38a80-d70b-11ea-9bd7-d844fa820cec.png)

**Comment by victorhuangwq** [comment]
@mtoupsUNO I have addressed the issue that you have mentioned. I realized that it isn't just the problemGrades div that needed the resizing, but the whole right hand section (annotationPane). I have made the changes in https://github.com/autolab/Autolab/pull/1200. Do take a look, add some annotations and let me know if it works out for you

**Comment by mtoupsUNO** [comment]
Yes, this fix works for me and I agree fixing the whole annotationPane div is the right thing to do here. Thanks!
