### ISSUE TITLE
Dead code in assessments/edit.html.erb

### ISSUE THREAD

**Issue by wlnirvana** [autolab/Autolab#1201]
https://github.com/autolab/Autolab/blob/2ac3b7cf763c445e4bf8bf5efd5c0daccec129c4/app/views/assessments/edit.html.erb#L11-L30

There seems no element with id `assessment_has_custom_form`. But the function call to `validate` will cause error at line 21 since the checkbox variable is empty.

**Comment by oliverli** [comment]
Thank you so much for reporting! It seems to be leftover crud from years back, committed in 4 years ago (#782) but with the form removed 3 years ago (#803). Please do keep reporting dead code or other such silliness as you find them, and on our part I'll also dedicate more time working on the rigor of our codebase
