### ISSUE TITLE
Put "Disabled" Courses below "Current" Courses

### ISSUE THREAD

**Issue by beetosu** [autolab/Autolab#1281]
I enrolled in CSE331 last Spring, and the autograder for that class is currently disabled (which I totally understand, assuming the class is structured similarly now as it was last year)

However, it is kinda annoying to have to scroll past CSE331 every time I go on Autograder just to get to my active classes.

**Comment by xinyis991105** [comment]
Hi! I'm not sure I understand your issue but is this regarding the placement of active VS inactive courses on a student's dashboard? We have an issue template available when you create a new issue. It would be of great help to us if you could offer more details, for example, in this case, a screenshot. Thanks for the feedback! Please let us know if you can offer more information.

**Comment by beetosu** [comment]
Oh hi! Thanks for getting back to me!
Sorry I didn't use the bug report template, but it's less of a technical issue and more of a design issue, so I thought it would have been inappropriate.

![Screenshot_2021-02-18 Autolab Home(1)](https://user-images.githubusercontent.com/29612529/108386098-52bf2580-71da-11eb-9069-251c39b912f9.png)


This screenshot sort of portrays the issue a little better, my apologies for not including it in the initial report. It's less an issue of active vs. inactive, as "completed" courses have always been below "active" courses. Rather, the spring 2019 iteration of CSE331 has been "disabled", and the creation of that new category has put that course above the active courses

**Comment by xinyis991105** [comment]
Thanks for your visual feedback! We'll add this to one of our future tasks!

**Comment by victorhuangwq** [comment]
Addressed by https://github.com/autolab/Autolab/pull/1318
