### ISSUE TITLE
User Sign-Up Password Length Warning

### ISSUE THREAD

**Issue by madhathacker** [autolab/Autolab#1286]
**Your environment**
Let us know details such as 
- Self-hosted Autolab instance
- Ubuntu 20.04
![image](https://user-images.githubusercontent.com/21959742/110030981-5b4c4b80-7d04-11eb-8359-4a9b10ae2265.png)

**Steps To Reproduce**
1. Go to `https://autolab.0x00.host/auth/users/sign_up`
2. Type in user details and a p**assword less than 8 characters**
3. See BIG error

**Current behavior**
Big warning message only after attempt.

![image](https://user-images.githubusercontent.com/21959742/110031254-aa927c00-7d04-11eb-8bde-3d645aa0b879.png)
![image](https://user-images.githubusercontent.com/21959742/110031206-9d758d00-7d04-11eb-95d0-dcdb739ad17a.png)

**Expected behavior**
Should warn before, and smaller warning after.

![image](https://user-images.githubusercontent.com/21959742/110031269-afefc680-7d04-11eb-9aaa-e19975320a76.png)
![image](https://user-images.githubusercontent.com/21959742/110031275-b2eab700-7d04-11eb-965e-ab02efc8fd3a.png)

**Comment by damianhxy** [comment]
Could probably be done with a mixture of `help-blocks`, `pattern` attribute (e.g. `.{8,}`), and using the [hashes](https://stackoverflow.com/questions/53088609/how-to-show-devise-error-messages-one-by-one) to display corresponding errors for each field.
