### ISSUE TITLE
Dropping via import roster doesn't work

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#130]
BUG REPORT
- - - - -
User: tcortina@andrew.cmu.edu
Course: 15-292: Special Topic: History of Computing (s15)
- - - - -
I submitted a new roster for my 15-292 course, and one student had dropped. I had checked the box that said that missing students from uploaded roster would be marked as dropped, but the student was not. ()  -Tom Cortina

**Comment by ymzong** [comment]
@icanberk Did you have a chance to look at #117? I think these two issues might have the same root cause, so you might as well fix both at the same time.

**Comment by andrewwuan** [comment]
@ymzong I see that you are an instructor in the course. Is this the reason why you can't be dropped?

**Comment by ymzong** [comment]
@andrewwuan That's true, but it might also be related to #117. You can try remove me from instructors list then drop me with the roster, and see if this works. :)

**Comment by andrewwuan** [comment]
User won't be dropped if he's an instructor/TA/admin. We Autolab admins gets an instructor account automatically when we go into a course, so that's why we cannot be dropped :)
