### ISSUE TITLE
Annotate Submission doesn't properly display fractional grades.

### ISSUE THREAD

**Issue by MilesConn** [autolab/Autolab#1314]
This is CMU's Autolab I'm a TA.  

**Steps To Reproduce**
1. Go to Annotate a Submission
2. Assign a non integer grade ie -.5 to Style.

**Current behavior**
Style gets marked as an integer rounded down in the UI but the fraction correctly shows when I go to edit and in the final grade. 

**Expected behavior**
The number should be correct. 

**Screenshots**
![Screenshot_20210405_005625](https://user-images.githubusercontent.com/8140002/113538688-dfb31800-95a9-11eb-9166-cd54c028a5e2.png)
![Screenshot_20210405_005600](https://user-images.githubusercontent.com/8140002/113538689-e04bae80-95a9-11eb-9725-b4ab52175a2b.png)
![Screenshot_20210405_005543](https://user-images.githubusercontent.com/8140002/113538690-e04bae80-95a9-11eb-9fdd-3bcc027f851b.png)

**Comment by oliverli** [comment]
Hi Miles, thanks for reporting the bug! I have verified and replicated it, and am now looking into the issue and looking to push a fix

**Comment by oliverli** [comment]
Just checking in again since I remember you verbally told me the issue hasn't yet been fully resolved - where does the issue still persist?

**Comment by MilesConn** [comment]
Yeah the issue is still there I believe. As you can see in the top right.

![image](https://user-images.githubusercontent.com/8140002/122803886-34a32800-d295-11eb-8fec-b4f227de76bd.png)

**Comment by xinyis991105** [comment]
Hi! I was able to replicate this issue. The interesting thing is that when you make a change to your annotation, it displays incorrectly. But if you refresh the page, it displays ok. I will soon attach a PR to fix this. Thanks for confirming with us.
