### ISSUE TITLE
createVm return status not checked

### ISSUE THREAD

**Issue by mihirpandya** [autolab/Autolab#132]
createVm returns a -3 whenever there is an exception in that function. This return value is not checked in multiple places.

**Comment by ymzong** [comment]
@mihirpandya Will work on this after we settle down with the current fix. :smile:

**Comment by dlbucci** [comment]
Remind me to close this after the feature_groups branch is pulled in to master.

**Comment by jez** [comment]
You could always just tag on a nearly empty commit with the text "fixes
#132" to the feature_groups branch and it will automatically close.

Either way.
