### ISSUE TITLE
Timezone fields rely on vague acronyms

### ISSUE THREAD

**Issue by MilesConn** [autolab/Autolab#1369]
**Your environment**
CMU's Autolab configuration

**Steps To Reproduce**
1. Go to an assignment 
2. Look at the Date Fields

Note this issue is difficult to reproduce because I believe Autolab uses your computer's local time. I tried using a Chinese VPN but I couldn't coerce autolab to reproduce it. Instead I'm including a screenshot.

**Current behavior**
Uses time zone abbreviations. These are vague. I had a student report recently they submitted ans assignment late because they thought that the timezone was central standard time. CST can also be Cuban Standard Time. In reality it was Chinese Standard Time. 

**Expected behavior**
UTC +- a number

**Screenshots**
![image](https://user-images.githubusercontent.com/8140002/122965279-03d6f780-d356-11eb-8d55-46de2babd8dd.png)

**Comment by xinyis991105** [comment]
Hi! Thanks for bringing this up! We'll add this to our backlog and let you know when we make a change!
