### ISSUE TITLE
The Gemfile is contradicting

### ISSUE THREAD

**Issue by ugogon** [autolab/Autolab#1379]
The Gemfile is contradicting. I stumbled upon that after I tried to install another gem. 

This is due to the mimemagic update https://github.com/autolab/Autolab/pull/1347 to make installing mimemagic compliant to MIT license again. But mimemagic 0.4.2 breaks rails 5.2.0. On the otherhand mimemagic 0.3.7. is also compliant to MIT license and does not break rails 5.2.0 so I fixed it for me by inserting `gem 'mimemagic', '>= 0.3.7'` in my Gemfile. 

**Steps To Reproduce**
1. Delete Gemfile.lock
2. Run `bundle install`

**Current behavior**
```
Bundler could not find compatible versions for gem "mimemagic":
  In Gemfile:
    mimemagic (>= 0.4.2)

    rails (= 5.2.0) was resolved to 5.2.0, which depends on
      activestorage (= 5.2.0) was resolved to 5.2.0, which depends on
        marcel (~> 0.3.1) was resolved to 0.3.3, which depends on
          mimemagic (~> 0.3.2)
```

**Expected behavior**
It installs all gems and creates a Gemfile.lock.

**Comment by xinyis991105** [comment]
Hi Ugo! The Gemfile works fine for building images through Docker. We need to take a closer look before further changes. Thank you for reporting the bug and providing the PR!
