### ISSUE TITLE
Students have no option to change their nicknames

### ISSUE THREAD

**Issue by Z1MM32M4N** [autolab/Autolab#139]
Currently, the only way a student can change their nickname is by having a TA or Admin change it.

The route is there, but you have to go to Course Admin > Manage Accounts and then click on the email of one of the students > Edit Information. Notice that that whole workflow assumes you're a Course Admin.

If this is by design, then go ahead and close the issue. In the past though, people have always been able to change their nicknames at any time.

**Comment by droh** [comment]
Yes, it's very important that students should be able to change their
nicknames.

On Monday, January 19, 2015, Jake Zimmerman <notifications@github.com>
wrote:

> Currently, the only way a student can change their nickname is by having a
> TA or Admin change it.
>
> The route is there, but you have to go to Course Admin > Manage Accounts
> and then click on the email of one of the students > Edit Information.
> Notice that that whole workflow assumes you're a Course Admin.
>
> If this is by design, then go ahead and close the issue. In the past
> though, people have always been able to change their nicknames at any time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autolab/Autolab/issues/139>.
>


-- 
Sent from my iPhone.

**Comment by iCrown** [comment]
I just leave my true name there and I do really wanna to change it. Hope somebody fix it

**Comment by droh** [comment]
This is a pretty serious privacy issue.

Jake: could you take a crack at it?

-- David O'Hallaron
-- Prof of CS and ECE, Carnegie Mellon University
-- GHC 7517, x8-8199
-- http://www.cs.cmu.edu/~droh

**Comment by Z1MM32M4N** [comment]
I think I have a fix, see the associated pull request: #145.
