### ISSUE TITLE
assessment names and assessment config modules

### ISSUE THREAD

**Issue by cg2v** [autolab/Autolab#1393]
Autolab allows the creation of assessment names without many restrictions. Unlike course names, the only limit on assessment names is that they cannot begin with numbers. However, the assessment's name is used to form file names and ruby identifiers, so needs to have some more limitations. 
If an assessment with an inappropriate name is created, it triggers an exception whenever anyone tries to view it.
Based on https://stackoverflow.com/questions/3648551/regex-that-matches-valid-ruby-local-variable-names, you should limit assessment names to letters, numbers and _ (keeping the restriction that they cannot begin with numbers). 

It appears that some effort was put in to allow dots (".") in assessment names, which are stripped out before forming identifiers. If you want to keep that feature, then "." should also be allowed (except perhaps in the leading position).

Related to the "." stripping, construct_default_config_file should presumably refer to sanitized_name instead of name, to allow "." to be used when no ruby config file is provided with a newly installed assessment.

Lastly, given that various case conversions are applied to the name, the uniqueness validation for assessment names should presumably be case insensitive.

**Comment by damianhxy** [comment]
15-122 has requested for dashes to be allowed in assessment names
