### ISSUE TITLE
Use more compact method for obtaining archive

### ISSUE THREAD

**Issue by fanpu** [autolab/Autolab#1435]
Update git clone + tar method to use either git archive, or https://docs.github.com/en/rest/reference/repos#download-a-repository-archive-tar aka https://github.com/octokit/octokit.rb/blob/d1628ebd3e71aeb1534b3115c8bf37e8fb42068f/lib/octokit/client/contents.rb#L158

Thanks to @cg2v for suggesting this

**Comment by damianhxy** [comment]
Both methods require a ref, which makes them unsuitable compared to git clone + tar.

https://confluence.atlassian.com/bitbucketserverkb/git-upload-archive-archiver-died-with-error-779171761.html
