### ISSUE TITLE
Hard-coded email configuration information

### ISSUE THREAD

**Issue by parno** [autolab/Autolab#1459]
**Your environment**
Most recent commit of AutoLab `master` (7677e55).  

**Steps To Reproduce**
One of the Ruby initializers has the mail_sender setting defaulting to 'creds@<YOUR_WEBSITE>'.  See:

https://github.com/autolab/Autolab/blob/0192fa505248afda856441fb3d423b884d4b471c/config/initializers/devise.rb#L13

As a result, when using a custom mail host like SendGrid, the emails have a reply-to of 'creds@<YOUR_WEBSITE>'.

Configure a custom mail server in the `.env` file.  Send an email.

**Current behavior**
The emails have a reply-to of 'creds@<YOUR_WEBSITE>'.

**Expected behavior**
The emails should have a proper reply-to.

**Proposed Fix**
Changing the line above to:
```
config.mailer_sender = ENV['SMTP_DEFAULT_FROM']
```
seems to address the issue.

**Comment by ashleyzhang** [comment]
Thanks for catching that!
