### ISSUE TITLE
Unable to create an extension

### ISSUE THREAD

**Issue by parno** [autolab/Autolab#1466]
**Your environment**

We're using AutoLab with the Docker-based installation at commit `b98f28d254036d9ffc6d349ca27191cf37ddd687`.

If I go into the "Manage Students" area of the course, we have 30 students listed, each with a number, first name, last name, email, dropped=False, and type=Student.  The lecture and section fields are blank (not sure if that's related).

**Steps To Reproduce**
I'm trying to create an extension for a student.  I type in their email address and specify the number of days to add.

Suspiciously, as I'm typing in the StudentName/Email field, I don't see the usual auto-complete dropdown.

**Current behavior**
I receive a red error message saying `No student with id was found for this course.`

**Expected behavior**

An extension should be created.

**Comment by xinyis991105** [comment]
Hi Bryan! We'll shortly look into this and let you know if we find out what's going on! Thanks for reporting the bug!

**Comment by parno** [comment]
Thanks very much!  I'm happy to hop onto Zoom if that's helpful.

**Comment by xinyis991105** [comment]
Hi Bryan! I don't think the issue has to do with the lecture and section being blank. The error message indicates that a course user datum entry cannot be found corresponding to the student's course user datum id in the database. Is it possible for you to manually check the parameters of the extension creation call, find the course user datum id in the parameters, and look it up in the database?

**Comment by parno** [comment]
I don't speak Ruby, unfortunately, but it seems like this line:
https://github.com/autolab/Autolab/blob/6cad6d1f4cd638c470ed373c34c5908dec5ebd09/app/controllers/extensions_controller.rb#L31
should have included the course user datum ID in the error message, no?  I can update the code to print other info if you can suggest which bits to grab.

**Comment by cg2v** [comment]
I am pretty sure this is one of the issues from #1443. I believe that either https://github.com/autolab/Autolab/pull/1443/commits/8d76c19173975c69991e4a961f7e0c1bafe63632 or the combination of https://github.com/cg2v/Autolab/commit/057493b3e518376d54fa62dc74b4ac7ba46353a5 and https://github.com/cg2v/Autolab/commit/752a44f942fe65168de0de003060d073c09817ea should fix this issue

**Comment by parno** [comment]
I applied https://github.com/cg2v/Autolab/commit/057493b3e518376d54fa62dc74b4ac7ba46353a5 and https://github.com/cg2v/Autolab/commit/752a44f942fe65168de0de003060d073c09817ea, and that seems to have done the trick.  Thanks for the pointers @cg2v!

**Comment by why-in-Shanghaitech** [comment]
There are still errors if the first name and last name of the users are written in non-English characters (say, Chinese)...
My current solution is to change the user name, make an extension, and then change the user name back.

**Comment by damianhxy** [comment]
Thanks for reporting this, we will take a look into the issue!
