### ISSUE TITLE
`bundle install` fails because `overcommit` is undefined

### ISSUE THREAD

**Issue by toolcreator** [autolab/Autolab#1471]
**Your environment**
Let us know details such as 
- Which institution's Autolab you are using (e.g. Carnegie Mellon's Autolab at https://autolab.andrew.cmu.edu/ etc)
  - local installation via docker-compose
- Operating system
  - Manjaro Linux
- Commit hash (if relevant)
  - cb62c99ffecb46d12014ff8de2c85a1b00b26d69
- Ruby version (if relevant)
- Rails version (if relevant)

**Steps To Reproduce**
1. Follow the [docker-compose install instructions](https://docs.autolabproject.com/installation/docker-compose/) until step 5

**Current behavior**
`docker-compose build` fails with
```
Step 15/25 : RUN bundle install
 ---> Running in 2bd74b88d9e4

[!] There was an error parsing `Gemfile`: Undefined local variable or method `overcommit' for Gemfile. Bundler cannot continue.

 #  from /tmp/Gemfile:125
 #  -------------------------------------------
 #    # pre-commit hook for rubocop
 >    gem overcommit 
 #  
 #  -------------------------------------------
1 error occurred:
        * Status: The command '/bin/sh -c bundle install' returned a non-zero code: 29, Code: 29
```

**Expected behavior**
It does not fail.

**Screenshots**

**Probable cause**
The above mentioned commit added to following lines to the Gemfile:
```
  # pre-commit hook for rubocop
  gem overcommit
```

Looking at the file, it turns out the gems are usually in single-quotes, e.g.,
```
  # documentation generator
  gem 'yard'
```

So writing `gem 'overcommit'` instead of the above will probably fix the problem.

**Workaround for docker-compose installation**
Skip step 3 in the instructions (`make update`), this way the mentioned commit is not pulled.

**Comment by xinyis991105** [comment]
Hi there! Thanks for bringing that up! PR #1472 has been submitted to address this issue.
