### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by scarroll32** [autolab/Autolab#1482]
**Steps To Reproduce**
1. Go to https://nightly.autolabproject.com as instructed [here](https://docs.autolabproject.com/#demonstration-website)
4. See error5. 

<img width="1089" alt="Screenshot 2022-03-11 at 12 29 02" src="https://user-images.githubusercontent.com/11340230/157858738-15d09883-b2d0-4a49-a6b8-5c1b7b0c10fd.png">

**Comment by fanpu** [comment]
Hi @scarroll32, thanks for flagging this, this was an issue with our TLS config. We have resolved the issue, could you try again?

**Comment by scarroll32** [comment]
Thank you @fanpu it is working now. 😄
