### ISSUE TITLE
Export submissions along with their metadata on Manage Submissions page

### ISSUE THREAD

**Issue by ymzong** [autolab/Autolab#149]

**Comment by dlbucci** [comment]
What did this one mean again? What was the submission metadata?

**Comment by TheodorJ** [comment]
Currently we have a bunch of options ("Download all submissions", "Download final submissions", etc.). We can turn this into a separate page with all of these options as checkboxes and allow the user to download a rigidly defined subset of the submissions (along with metadata, maybe in a .csv). I'll leave this one open.

**Comment by victorhuangwq** [comment]
Issue seems abandoned. Closing it now

**Comment by mtoupsUNO** [comment]
I'll just point out that #1099 would set the downloaded zip file metadata correctly. The date of submission is an important bit of metadata that is lost currently when downloading a zip file of submissions.
