### ISSUE TITLE
Invalid assessment config SyntaxError not caught on create

### ISSUE THREAD

**Issue by michellexliu** [autolab/Autolab#1529]
**Steps To Reproduce**
1. Create a lab with a .rb config file that has a syntax error
2. Create a tarfile of the lab
3. Click install assessment
4. Click "browse" under "Import from tarball"
5. Select the tarfile for the lab

**Current behavior**
An error page is shown on the deployed version, locally this is shown:
![image](https://user-images.githubusercontent.com/50491000/168681838-60f3d7b3-d6fd-4ffd-852c-bf02a396f449.png)
The assignment is also created but shows an error whenever you try to access it.

**Expected behavior**
Similar behavior to when you edit an existing config and click reload config (see #1522). No assignment should be created.
![image](https://user-images.githubusercontent.com/50491000/168682246-53b45dc3-4c10-46d3-92e4-3ef268d30664.png)

**Comment by damianhxy** [comment]
Also not caught on import from file system. But this can only occur if a user that has an assessment with invalid config directly navigates to the edit assessment page and deletes the assessment. And ultimately, other errors such as `NameError` and `ArgumentError` would not be caught, so it might be pointless trying to preempt this.

**Comment by damianhxy** [comment]
If we aren't too concerned with generating an error page, the following patch would probably suffice:

```
diff --git a/app/controllers/assessments_controller.rb b/app/controllers/assessments_controller.rb
index 8988bba0..96ba0c9f 100755
--- a/app/controllers/assessments_controller.rb
+++ b/app/controllers/assessments_controller.rb
@@ -145,7 +145,7 @@ class AssessmentsController < ApplicationController
         redirect_to(action: "install_assessment")
         return
       end
-    rescue StandardError => e
+    rescue StandardError, SyntaxError => e
       flash[:error] = "Error while reading the tarball -- #{e.message}."
       redirect_to(action: "install_assessment")
       return
@@ -850,7 +850,11 @@ private
       else
         return false unless asmt_name
 
-        asmt_rb_exists = true if pathname == "#{asmt_name}/#{asmt_name}.rb"
+        if pathname == "#{asmt_name}/#{asmt_name}.rb"
+          config_source = entry.read
+          RubyVM::InstructionSequence.compile(config_source)
+          asmt_rb_exists = true
+        end
         asmt_yml_exists = true if pathname == "#{asmt_name}/#{asmt_name}.yml"
       end
     end

```

Giving us an error that looks like
<img width="720" alt="Screen Shot 2022-06-07 at 00 32 15" src="https://user-images.githubusercontent.com/9074856/172296493-b865a501-7597-4704-9d35-b597e6009e40.png">

**Comment by damianhxy** [comment]
If we really wanted to handle import from file system too, one option is something like

```ruby
def importAssessment
    @assessment = @course.assessments.new(name: params[:assessment_name])
    begin
      @assessment.load_config_file # only call this on saved assessments
    rescue SyntaxError => e
      flash[:error] = "Error while importing assessment -- #{e.message}"
      redirect_to(action: "install_assessment") && return
    end
    @assessment.load_yaml # this will save the assessment
    @assessment.load_embedded_quiz # this will check and load embedded quiz
    @assessment.construct_folder # make sure there's a handin folder, just in case
    redirect_to([@course, @assessment])
  end
```
