### ISSUE TITLE
Course roster import shouldn't reject students with no first name (or no last name).

### ISSUE THREAD

**Issue by zackw** [autolab/Autolab#1536]
**Your environment**
- Carnegie Mellon's Autolab (https://autolab.andrew.cmu.edu/)

**Steps To Reproduce**
1. Go to "upload roster"
2. Attempt to upload a roster containing a student whose "preferred/first name" field is blank.

**Current behavior**

Autolab rejects the upload with an error like this (information identifying the student in question has been redacted; redactions marked by [square brackets])

> There was an error uploading the roster file. Please fix the following error(s) and try again:
>
>Validation failed: First name can't be blank at line 2 of the CSV</p>
>
> № | First Name | Last Name | Email | Lecture | section | School | Major | Year | Nickname | Dropped? | Type
> -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
> 2 |   | [Mononym] | [mononym@andrew.cmu.edu] | 15513 | A | [xxx] | AII | [xxx] |   |   | Student

**Expected behavior**

Autolab should accept this roster.  The student should be identified by the contents of the "last name" field, whatever that is.
Symmetrically, Autolab should also accept rosters where the student has no _last_ name.  People don't necessarily have more than one name, and when this happens, I have no control over how the registrar chooses to fit that into their database schema.

**Comment by fanpu** [comment]
Hi @zackw, thanks for raising this, this will definitely be something that we will look into

**Comment by damianhxy** [comment]
Seems easy enough to implement

```diff
diff --git a/app/models/user.rb b/app/models/user.rb
index 48af212e..b265f0c0 100755
--- a/app/models/user.rb
+++ b/app/models/user.rb
@@ -17,7 +17,9 @@ class User < ApplicationRecord
   has_one :github_integration
 
   trim_field :school
-  validates :first_name, :last_name, :email, presence: true
+  validates :first_name, presence: true, :unless => :last_name?
+  validates :last_name, presence: true, :unless => :first_name?
+  validates :email, presence: true
 
   # check if user is instructor in any course
   def instructor?

```

**Comment by 20wildmanj** [comment]
> Seems easy enough to implement
> 
> ```diff
> diff --git a/app/models/user.rb b/app/models/user.rb
> index 48af212e..b265f0c0 100755
> --- a/app/models/user.rb
> +++ b/app/models/user.rb
> @@ -17,7 +17,9 @@ class User < ApplicationRecord
>    has_one :github_integration
>  
>    trim_field :school
> -  validates :first_name, :last_name, :email, presence: true
> +  validates :first_name, presence: true, :unless => :last_name?
> +  validates :last_name, presence: true, :unless => :first_name?
> +  validates :email, presence: true
>  
>    # check if user is instructor in any course
>    def instructor?
> ```

I guess the only thing to be careful of here is how viewing any pages that include users' first and last name will now be rendered (won't cause errors but might look weird)
