### ISSUE TITLE
Universal-ctags and ubuntu 22.04 support

### ISSUE THREAD

**Issue by tuhe** [autolab/Autolab#1543]
I recently installed Autolab on ubuntu 22.04. The installation instructions for 18.04 in the current version of the documentation are nearly sufficient, however, the package 'ctags' should be replaced with 'universal-ctags' in order to get the symbol tree in the annotate submission view to work (current package is just 'ctags').
 
I am adding this issue after request from Victor Huang on Slack.

**Comment by damianhxy** [comment]
Same issue on macOS 12.4 

```
/Library/Developer/CommandLineTools/usr/bin/ctags: illegal option -- -
usage: ctags [-BFadtuwvx] [-f tagsfile] file ...
```

It appears that macOS' default ctags differs from universal-ctags. Can be remedied by installing from homebrew via `brew install --HEAD universal-ctags/universal-ctags/universal-ctags` and ensuring its ctags takes precedence.
