### ISSUE TITLE
Improvements to Edit Assessment

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#157]
Requests from Iliano:
(1)  (at the very minimum) After adding a problem, go back to the
   "Problem" tab (rather than the "Basic" tab) since 9 times
   out 10 the next thing I need to do is add another problem.

(2)  (much much better) Add/edit/delete problems without changing
   page by using Ajax.  Clicking on "add problem" would simply
   add a row of text boxes that would be saved the moment the
   user goes to a different row or presses a "save" button.

(3) Also, having all the fields needed to edit an assessment on one page
(like in the old version) was more convenient than the current 4-page
view.  If what you want is quick navigation, you may consider some fancy
in-page navigation like, say, Piazza's "Manage Class" page.

**Comment by Z1MM32M4N** [comment]
Summary:
(1): Fixed via #154
(2): See standalone issue #179 
(3): See standalone issue #180
