### ISSUE TITLE
C0 syntax highlighting highlights some annotations as syntax errors

### ISSUE THREAD

**Issue by robsimmons** [autolab/Autolab#162]
Getting some weird boxes in some of our annotations (which should just be parsed as comments), indicating a probable bug in whatever syntax highlighting package y'all are using.

![untitled](https://cloud.githubusercontent.com/assets/442315/5854577/54ceeeae-a1fd-11e4-905e-b9125c051a34.png)

**Comment by dlbucci** [comment]
https://highlightjs.org/
We can try switching to this instead of using pygments.

**Comment by dlbucci** [comment]
Looks like this was fixed by #307
