### ISSUE TITLE
Autolab 500 error as a student

### ISSUE THREAD

**Issue by stephenlearnscode** [autolab/Autolab#1632]
Hi, I'm a student a Carnegie Mellon, using Carnegie Mellon's Autolab on Windows 11.

Go to Autolab Home (where the courses are listed).
Clicking on the course page icon, course page link, hw8 link, and gradebook link all give "500 - Internal Error"

Clicking on each of those is supposed to open the corresponding pages for each of them correctly.

<img width="889" alt="image" src="https://user-images.githubusercontent.com/107706037/198471035-5373fbcc-fcf8-4f1f-99ea-70cf6fee9d1e.png">
Clicking on any of the blue circled clickables lead to:

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/107706037/198471250-4d21f3f4-27d1-4134-ad9c-15db65c320c8.png">

It's also relevant that I have submitted hw8 and have not submitted a fix-it-friday

**Comment by damianhxy** [comment]
Hi! We've been reporting numerous reports about this tonight.

Unfortunately, it appears that the servers have run out of space. This is an issue that will have to be remedied by Computing Services.

**Comment by stephenlearnscode** [comment]
Thanks!
