### ISSUE TITLE
Cannot make manual annotations on a submission that got zero points from the autograder

### ISSUE THREAD

**Issue by zackw** [autolab/Autolab#1641]
**Your environment**
Carnegie Mellon's Autolab at https://autolab.andrew.cmu.edu/

**Steps To Reproduce**

1. Have an assessment that is partially autograded and partially manually graded.
2. Go to `/gradesheet` for that assignment.
3. Find a student who submitted something that the autograder gave zero points to.  (Note: The bug _might_ only happen for students who submitted something that the autograder script didn't print a JSON score report for, e.g. because it timed out.)
4. Click on the little arrow for that student, taking you to the "annotate submission" screen for their submission.
5. Click on any line of code, bringing up the "add annotation" pop-up.
6. Type some text in the "comment" field and push the "add annotation" button.

**Current behavior**

At Step 6, you get the nonsensical error message "There are no non-autograded problems. Create a new one at Edit Assessment > Problems"

**Expected behavior**

It should be possible to annotate the submission normally.

**Screenshots**

![Screenshot of the error from Step 6](https://user-images.githubusercontent.com/325899/201368094-4c08e019-5cd2-4689-aaf6-aeda79de91ac.png)

**Comment by najclark** [comment]
It seems like this error occurs when there aren't any non-autograded problems for the assessment, regardless of the autograded score. As a workaround for now, I would suggest changing scores on the gradesheet page. 

![Screen Shot 2022-11-12 at 6 20 41 PM](https://user-images.githubusercontent.com/11011325/201498401-08f01f54-66e0-42f0-8298-6c4ef91e00cd.png)

Or alternatively, by adding a problem to the assessment, you should be able to annotate the student's submissions and the total score should reflect the student's actual score.

**Comment by damianhxy** [comment]
@zackw I was able to reproduce the issue: it appears to occur when the JSON score report is not printed, as you suspected (it does not, however, have to do with a score of zero).

![Screenshot 2022-11-12 at 18 46 27](https://user-images.githubusercontent.com/9074856/201499004-ffff68cc-651d-46b2-8b28-c027c6a24e85.png)

There appears to be a bug where all problems become "autograded" as a result, preventing you from annotating them. I will investigate this further, but as a workaround I would suggest annotating the scores for the problems directly on the gradesheet, as mentioned above.

Thank you for reporting this!

**Comment by zackw** [comment]
Yes, we were already aware of this workaround.  Thanks for looking into it!
