### ISSUE TITLE
"Errors" field on Handin History

### ISSUE THREAD

**Issue by brandonfranzke** [autolab/Autolab#1646]
I see "Errors" field on Handin History page for autograde assignments (can provide screenshot on request).  Can the the assignment autograder provide content and populate this through the autoresult response?  Or is is restricted to some internal error reporting?

I didn't see the field mentioned on the docs:
https://docs.autolabproject.com/lab/

**Comment by 20wildmanj** [comment]
Hi, could you provide a screenshot of the "errors" field so I can get a better idea of what is going on?

**Comment by brandonfranzke** [comment]
Attached.  Shows the "Errors" column on the far right.  This is the "Manage Submissions" popup when selecting an individual student.

![autolab-errors-column](https://user-images.githubusercontent.com/25208791/202836028-4ef5e670-789c-4d60-88f9-174e0894293d.png)

**Comment by 20wildmanj** [comment]
According to our investigations, it seems as though this field gets populated by the frontend app, but for what exact purpose we're not exactly sure since it's been years since this field was last updated. This field is not used or set by the autograder. We will likely need to do some more digging.
