### ISSUE TITLE
Annotations Frontend Issues

### ISSUE THREAD

**Issue by 20wildmanj** [autolab/Autolab#1665]
**Your environment**
v 2.9.0

## Summary of issues

This issue compiles multiple issues with the frontend of the Annotations feature, found by @20wildmanj and @damianhxy.

## 1. Annotation closing unexpectedly

Clicking "update annotation" on an existing annotation when another annotation is also open removes the other open annotation

![image](https://user-images.githubusercontent.com/25730111/205388218-a1473ce0-06ca-43ca-8f71-fd94f7ee67cd.png)

### Context

Known issue, it's because of how `annotations.js` liberally calls `displayAnnotations()` after some events (change file,  cancel, update), which basically rerenders all the annotation boxes and thus closes the existing ones.

### Possible Solution

We need a more targeted approach of only editing the required annotation.

## 2. Duplicating Autofilled comments

When autofilling, you can add the same comment that got autofilled back to the shared comment pool, and it'll become a new shared comment.

### Context
Given the current design of shared comments (`shared_comment` flag on annotations), there isn't really a way around this atm.

### Possible Solution
Have a table of shared annotations where each annotation points to the shared annotation it is utilizing and perhaps the shared annotation can store a refcount. This could be a little complicated though.

## 3. Multi-line comments

Multi-line comments don't seem to open all the way when you re-open / autofill

![image](https://user-images.githubusercontent.com/25730111/205389715-33a6239d-fc9d-4e84-aaa7-b5a6b77119b8.png)

### Context

Known issue, some previous observations:
![Screenshot 2022-12-02 at 15 52 44](https://user-images.githubusercontent.com/9074856/205384317-ae4d9695-2870-4f30-8d2b-2804f04c5303.png)

## 4. Shared comments drop-down

adding newlines to an annotation makes the shared comments drop-down get misaligned

![image](https://user-images.githubusercontent.com/25730111/205389964-835aae8b-cbff-4171-a399-2cda5daf9b99.png)

## 5. Scrolling to an Annotation from Sidebar

When we click on an annotation on the right side bar, we start scrolling from the top of the code viewer each time, even if the annotation is already in view. This can result in janky animation.

## 6. Autofilling score from shared comment

**Feedback from 122:** Point values should stay with a shared comment added to the pool. In the screenshot below, "A1: Has contract”’s point values when I created it, +1.0, should be automatically applied when I choose this comment from the shared pool. This issue comes up not only when I attach it to another Problem, but within the same Problem as well.

### Possible solution

It would necessitate the writing of custom code (see https://jqueryui.com/autocomplete/#custom-data) to attach extra attributes to each dropdown element (i.e. the score) and to fill in the score fields when we select a value.

## 7. Initialization of problem scores

A problem doesn't get a score until we make an annotation for it. We should see if it's possible to automatically initialize a score for each problem for new submissions, to reduce the risk of calling undefined methods on `nil`.

**Comment by damianhxy** [comment]
[Rubric Mockup.pdf](https://github.com/autolab/Autolab/files/10417001/Rubric.Mockup.pdf)

Rubric Mockup by Amanda

**Comment by michellexliu** [comment]
Split into #1702, #1703, #1704, #1705, #1706, #1707, #1708 for easier assignment in GH Project board
