### ISSUE TITLE
User doesn't get dropped when deactivated on Canvas, if originally added via roster upload

### ISSUE THREAD

**Issue by michellexliu** [autolab/Autolab#1686]
**Your environment**
Autolab 2.10.0

**Steps To Reproduce**
1. Upload roster CSV with a given user
2. On a Canvas course where the user is a member, sync the Canvas course to Autolab
3. Deactivate the user on Canvas
4. Refresh the roster on Autolab

**Current behavior**
De-activated user doesn't get dropped.

**Expected behavior**
De-activated user should get dropped

**Comment by najclark** [comment]
Closing as the dropping behavior works as expected with the 'auto drop' LTI setting enabled

![Image](https://user-images.githubusercontent.com/11011325/217078849-7b6361f8-02ae-4cae-b649-1a5d65b7440d.png)
