### ISSUE TITLE
Metrics page navbar has smaller font

### ISSUE THREAD

**Issue by 20wildmanj** [autolab/Autolab#1695]
Metrics:
![Screen Shot 2023-01-23 at 22 55 35](https://user-images.githubusercontent.com/25730111/214209318-bc97ab98-82c7-4cb8-b98c-b45badacadbd.png)

Normal:
![Screen Shot 2023-01-23 at 22 57 22](https://user-images.githubusercontent.com/25730111/214209374-b8fa78d0-8500-4f3d-b21f-c6717547534f.png)

**Comment by kushalnl7** [comment]
I will work on this.

**Comment by kushalnl7** [comment]
I have raised a PR for this - #1738. Please review it.
