### ISSUE TITLE
Hide deadline warning for non-submittable assignments

### ISSUE THREAD

**Issue by michellexliu** [autolab/Autolab#1696]
From Iliano: would it be possible not to display the deadline notification (see screenshot) for assessments for which submission is disabled?  This confuses students.  (Besides for proper assessments, we are using Autolab to release other material on specific dates/times.)
![image](https://user-images.githubusercontent.com/50491000/214383692-3123f418-e06c-472e-a47a-d1f0ddcae1a8.png)

**Comment by kushalnl7** [comment]
Hi, can I work on this?

**Comment by michellexliu** [comment]
That would be great! I'll assign it to you :)

**Comment by kushalnl7** [comment]
Hi, I have raised a PR - #1701 for this issue. Please review it.
