### ISSUE TITLE
Editing student submission returns Instructor to their own submission history

### ISSUE THREAD

**Issue by 20wildmanj** [autolab/Autolab#1699]
**Steps To Reproduce**
1. Go to 'Manage Submissions' for a course as an instructor
2. Click on the Edit button for a student's submission
3. Click "Update Submission"
4. See that you are redirected to courses/${course}/assessments/${assessment_name}/history and not back to  courses/${course}/assessments/${assessment_name}/submissions

**Expected behavior**
The instructor should be returned to /submissions

**Comment by wafcio** [comment]
Hi, can I work on this?

**Comment by damianhxy** [comment]
@wafcio Sure, that would be great!

**Comment by wafcio** [comment]
Sorry, but I need to skip this issue. I don't use MySQL locally (prefer PostgreSQL), but with PostgreSQL loading initial data failing and almost everything doesn't work

**Comment by damianhxy** [comment]
No worries, thanks for offering to help!
