### ISSUE TITLE
Duplicating Autofilled comments

### ISSUE THREAD

**Issue by michellexliu** [autolab/Autolab#1706]
When autofilling, you can add the same comment that got autofilled back to the shared comment pool, and it'll become a new shared comment.

### Context
Given the current design of shared comments (`shared_comment` flag on annotations), there isn't really a way around this atm.

### Possible Solution
Have a table of shared annotations where each annotation points to the shared annotation it is utilizing and perhaps the shared annotation can store a refcount. This could be a little complicated though.

**Comment by damianhxy** [comment]
Closing this as a won't fix. This isn't really an issue, TAs should avoid using the shared comments feature unnecessarily. Currently, 122 makes dummy submissions and labels all the shared comments on it.

For a long term solution, we should consider the rubric system described in #1716. This might supersede the shared comment feature, by having the shared comments only be defined in the rubrics. In this case, there will be a single source of shared comments, preventing this issue.
