### ISSUE TITLE
Autolab admins should belong to a separate Lecture/Section

### ISSUE THREAD

**Issue by ymzong** [autolab/Autolab#171]
Professor Simmons:

> Could ya'll create a practice of adding yourselves to courses in the lecture ALAB or something, or maybe more long term create a separate Type of "Autolab" distinct from "Instructor"? Because right now I just see all these users that I can't identify listed as instructors, and I don't know whether that's because I accidentally clicked "instructor" somewhere or because they are just all Autolab people.

**Comment by devanshk** [comment]
Addressed by #820 which is an updated version of this.
