### ISSUE TITLE
Extra padding around autofill comment selection when hovered

### ISSUE THREAD

**Issue by michellexliu** [autolab/Autolab#1711]
When annotating a submission, there's extra space above and below a comment when a user hovers over it.
![Image](https://user-images.githubusercontent.com/50491000/215333472-9e7df251-8b6d-4e27-a66a-2f856d7dc2bd.png)

**Comment by epicseven-cup** [comment]
Hi, I want to know whats the steps for reproducing this issue.

**Comment by coder6583** [comment]
Thank you for your comment!

When you annotate a submission, you can choose to add the comment to the shared comment pool, as you can see in this screenshot.
![image](https://github.com/autolab/Autolab/assets/38949473/dedd63eb-a9c5-414c-bebd-761bb2eaf9a8)
If you choose this option, the written comment will appear as a suggestion below the comment input field. You will be able to see that there's extra space above and below the suggestion as written in the issue. 

If you have any more questions, feel free to ask them!

**Comment by epicseven-cup** [comment]
sorry wasn't looking at github for the past few days, I made the pr
