### ISSUE TITLE
Uploading an image make the page un-loadable in the Speedgrader

### ISSUE THREAD

**Issue by victorhuangwq** [autolab/Autolab#1720]
I uploaded a 1.1MB gif and it was a mistake

When the page does finally loads the image it renders the image data in plaintext so nothing is readable

Speedgrader in production will display "Sorry, we could not parse your file because it contains non-ASCII characters. Please  download the file  to view the source."

I think the migration to rails 5 broke this test/safeguard?

**Comment by damianhxy** [comment]
Can't repro
