### ISSUE TITLE
In CSV grade export, move the 'total' column to be after email instead of the last column

### ISSUE THREAD

**Issue by victorhuangwq** [autolab/Autolab#1728]

**Comment by damianhxy** [comment]
Is this to make it easier to visually scan the grades?

**Comment by damianhxy** [comment]
Discussed offline -- not a worthwhile breaking change

**Comment by damianhxy** [comment]
Request from Iliano

> Also, a recommendation if you ever update the format of the exported spreadsheet: put the total column in a fixed place, like after the andrew id.  Right now, it depends on the number of problems, which means that we cannot process it uniformly when importing it in our own grading infrastructure.
