### ISSUE TITLE
File-based versioning for dropdown version selection

### ISSUE THREAD

**Issue by michellexliu** [autolab/Autolab#1729]
When switching versions of a submission via the dropdown, "lock" it to the same file (if the file exists in the other submission), similar to how the file stays when switching versions with the arrow. Possibly add some way of indicating which submission versions contain the file

**Comment by damianhxy** [comment]
@michellexliu I believe this is the current functionality?

For reference: #1503
My code determines the submission versions containing the current file and the arrow buttons jump to the correct `header_position`.

**Comment by michellexliu** [comment]
Oh hmm good catch; I just checked and the selected file persists with the arrows. However, if you select a different file & select the new version with the dropdown (even if it has the same file available), the file gets switched to the default one.

I'll update the issue to reflect this.

**Comment by damianhxy** [comment]
Hmm, that was something I considered implementing. It shouldn't be too hard to lock it to the same file when switching, although the drop-down might not have space to indicate versions with the file.
