### ISSUE TITLE
No syntax highlighting for multiple line comments

### ISSUE THREAD

**Issue by victorhuangwq** [autolab/Autolab#1732]
The comment on lines 2 and 3 is black instead of green

Issue has been around for a while (including on prod!) but for some reason no one quite attended to it

Incorrect syntax highlighting physically hurts my eyes 😢 - Oliver

![Image](https://user-images.githubusercontent.com/5773562/215351983-9c0bd1ab-1851-4c09-91ef-c6bd82039e3f.png)

**Comment by damianhxy** [comment]
On second thoughts, it's probably because of this code in `annotations.js`
```js
    // Add syntax highlighting to the new code viewer
    $('pre code').each(function () {
      hljs.highlightBlock(this);
    });
```

I think oliver had a wip branch `speedgrader-syntax-fix`, it might be worth further investigation

**Comment by victorhuangwq** [comment]
It's mainly because the syntax highlighting is done line by line instead of the whole file

**Comment by damianhxy** [comment]
Could consider using https://github.com/wcoder/highlightjs-line-numbers.js
