### ISSUE TITLE
[Design Doc] Display / consider number of extensions in metrics

### ISSUE THREAD

**Issue by michellexliu** [autolab/Autolab#1737]
Currently, instructors must manually track:
* how many total extension requests students have made across assignments
* how many unique users have made requests
* users with only 1 request, multiple requests etc.

The metrics feature should display this info + have an option to factor number of extensions when deciding if a student is at-risk

**Comment by damianhxy** [comment]
Doc: https://docs.google.com/document/d/1dNltRSNxOsaOH9lbgE7x5kdEEZXPTR7B5o-G80u9-jk/edit
