### ISSUE TITLE
Click into submissions from gradebook score

### ISSUE THREAD

**Issue by michellexliu** [autolab/Autolab#1742]
Currently on the gradebook, you have to click on the student email and then the score that shows up for a grade in order to get to the submissions for that assignment. Usability would be improved if you could click directly on a score in the grade book to go to the student's submission.

![Image](https://user-images.githubusercontent.com/50491000/215609243-69b3ce64-1d2a-4d73-823e-a0695d83a250.png)

**Comment by anoosh96** [comment]
Hey @michellexliu, I can work on this, can you please assign me this issue?

**Comment by damianhxy** [comment]
@anoosh96 Assigned!

**Comment by damianhxy** [comment]
Relevant line is `gradebook.js#L72`, we should make use of something along the lines of `history_url(@_cud, asmt)`

**Comment by damianhxy** [comment]
@KesterTan 
Closed by #1998
