### ISSUE TITLE
Course Attachment UI differs from Assessment

### ISSUE THREAD

**Issue by michellexliu** [autolab/Autolab#1744]
## Course Attachment UI
![Image](https://user-images.githubusercontent.com/50491000/215333607-18a32988-7582-48e3-99a4-c5913dd53554.png)

## Assessment UI
![Image](https://user-images.githubusercontent.com/50491000/215333613-58104a82-06df-4f20-aaba-e3cb21d9828a.png)

**Comment by damianhxy** [comment]
This was fixed in #1682
