### ISSUE TITLE
Gray out the annotations sidebar and add a loading spinner until its contents refresh

### ISSUE THREAD

**Issue by michellexliu** [autolab/Autolab#1771]
**Your environment**
v2.10.0
Bug found by TA on Autolab production, also reproduce-able on local installation; for some reason load times for new annotation creation are a lot faster on autolab-dev and nightly, so this doesn't show up there.

**Steps To Reproduce**
1. Create a new annotation
2. Before the new annotation loads in the annotations panel, start creating a new global annotation

**Current behavior**
When you create a new annotation, it takes some time to load— if you try to create a new global annotation before it finishes loading, the form will close when the first annotation finally loads in the annotations panel.

https://user-images.githubusercontent.com/50491000/216812083-059f3ab5-b925-4a2e-abd1-fab7aa96ebdd.mov

**Expected behavior**
While an annotation is being added, the annotations sidebar should be grayed out (with a loading spinner), until the annotation has been loaded

**Comment by damianhxy** [comment]
Unavoidable due to current approach of replacing entire html contents of element.

One mitigation might be to gray out the sidebar and add a loading spinner until the contents refresh
