### ISSUE TITLE
Create New Problems Asynchronously

### ISSUE THREAD

**Issue by jez** [autolab/Autolab#179]
Rather than jumping out to a separate page (i.e., /courses/:course/assessments/:assessment/problems/new), new problems would be created and removed from the Edit Assessment > Problems page (i.e., courses/:course/assessments/:assessment/edit/problems).

The ideal workflow would be to dynamically add and remove fields to the page that would control the various problems by having something along the lines of an "add problem" button. The problems would either be saved periodically in the background or every time the user presses a "save" button.

**Comment by Z1MM32M4N** [comment]
Originally #157, point (2).

**Comment by victorhuangwq** [comment]
This issue is still present in the current version of Autolab, and it is relevant.

**Comment by damianhxy** [comment]
Closing as a won't fix. Realistically this wouldn't save much time, and presumably, instructors would import old assessment tarballs that already have the problems defined.
