### ISSUE TITLE
[Tests] attachments

### ISSUE THREAD

**Issue by michellexliu** [autolab/Autolab#1796]
spec/controllers/attachments_controller_spec.rb

- [Functionality test] create
- [Functionality test] update
- [Functionality test] destroy

**Comment by damianhxy** [comment]
Need to test:
- index / new / edit / show for assessment attachments (not just course attachments)
- Make sure that :released works as expected

**Comment by damianhxy** [comment]
Completed with #1810 and #1826, but they are in the develop branch
