### ISSUE TITLE
Condense Edit Assessment Tabs into Single Page

### ISSUE THREAD

**Issue by jez** [autolab/Autolab#180]
Rather than having the various parts of an assessment spread across four distinct pages (linked to with active/inactive tabs), place all the constituent parts required to edit an assessment on the same page.

Navigation between the logical units can be accomplished using something similar to a scroll spy with in-page anchors. For inspiration, see the Piazza "Manage Class" interface.

**Comment by Z1MM32M4N** [comment]
Originally #157, point (3).

**Comment by icanberk** [comment]
Hi @droh , What do you think about this?

I feel like the page might become too intimidating to the instructors if we merge into one. They are pretty used to the tabs right now.

**Comment by jez** [comment]
I think the tabs work pretty well, and the interface got a nice redesign with the new FormBuilder, so I'm closing this for now.

**Comment by icanberk** [comment]
I'm contemplating on putting those tabs to left side like menu items, but not an urgency.

**Comment by dlbucci** [comment]
It's probably more important to have the tabs function on the same page, more than anything (i.e. clicking a tab shouldn't take you to a new form/make you lose your data).

**Comment by jez** [comment]
We actually have an issue for that specifically that I've been meaning to
get around to.

**Comment by jez** [comment]
After discussing this in the team meeting today, we agreed to reopen this today to
- reduce complexity in the codebase
- simplify the process for ensuring that all the properties get saved to the correct places

/cc @dlbucci @droh

**Comment by remzr7** [comment]
Closed as irrelevant
