### ISSUE TITLE
Need a more powerful raw_score hook

### ISSUE THREAD

**Issue by zackw** [autolab/Autolab#1806]
**Your environment**
- Carnegie Mellon's Autolab at https://autolab.andrew.cmu.edu/ 
- which says "v2.10.0" in the lower right hand corner

**Current behavior**

As documented, the only thing the `raw_score` hook can do is adjust the calculation of the *total score* for an assessment.  CMU's 15-213 has two labs ("bomblab" and "attacklab") that could benefit from being able to do more at the point where this hook is executed, i.e. in between when Ruby parses the JSON score report coming back from the autograder, and when anything gets written to the database.  (Note: I recognize that the behavior of the existing hook probably needs to be preserved for compatibility, so I might really be asking for a _new_ hook or four.  When I say "`raw_score`" below, I mean "`raw_score` or whatever the new mechanism ends up being.")

I have workarounds for the absence of all of these features. My preferred delivery date for them would be "no later than the beginning of summer term" but it isn't any more urgent than that.

**Desired behavior**

In decreasing order of priority:

1. Allow `raw_score` to adjust scores for each _problem_ and not just the total.  Hypothetically this could look something like this:

    ```
    # The autograder returns scores in [0, 1] for each problem.  Scale them to the desired point totals.
    def raw_score(score)
        score["phase1"] *= 10
        score["phase2"] *= 25
        score["phase3"] *= 25
        score["phase4"] *= 35
        score["phase5"] *= 5
        return score.values.sum
    end
    ```

1. Give `raw_score` a documented mechanism for accessing the scores for _previous submissions_ by the same student for the same assessment.  This _may_ currently be possible by mucking around with `assessment_user_data` but I haven't actually tried it and it seems like it involves knowing too much about Autolab's guts.

    I need this because grading for both bomblab and attacklab is cumulative over all submissions.  For attack lab, each submission is only for one problem, so it's necessary to find the most recent submission that touched each problem in order to pull together a complete grade.  For bomb lab, there's a count of "explosions" that should never go down.

1. Allow `raw_score` to generate the scoreboard array.

    Right now the scoreboard array has to come from the autograder itself, but, as described above, the raw score for these labs is incomplete and therefore the scoreboard array is also.  To do the job right, I would need to calculate the scoreboard array _after_ computing the complete cumulative grade, which means in `raw_score` or later. It would also, IMNSHO, be better separation of concerns if the autograder just emitted scores and it was assessment.rb's job to calculate the scoreboard array.

**Comment by damianhxy** [comment]
Resolved in #1832
