### ISSUE TITLE
Upgrade Datetime Pickers

### ISSUE THREAD

**Issue by jez** [autolab/Autolab#181]
### Required Features
- [x] Linked datepickers (start time can never come after end time)
- [x] Cross browser support
- [x] Option to cut/copy/paste dates in plain text
- [x] Upgrade all current interfaces which use dropdowns
- [x] Include a "now" or "today" button
- [x] Easy to grok times (from a user's perspective)
- [x] Allow arbitrary precision for picking dates (to the minute)

This will likely be implemented using [Bootstrap 3 Datepicker][1], which includes support for all of these date and time options.

[1]: http://eonasdan.github.io/bootstrap-datetimepicker/

**Comment by icanberk** [comment]
@Z1MM32M4N how's this going?

**Comment by jez** [comment]
I've been stuck on how to get this to work with Rail's custom form builders. I'd like to be able to just write `f.datetime` and have it include all the necessary HTML. For whatever reason, when I try to modify the existing `FormBuilderWithDateInput` class, it raises a method not found exception.

**Comment by dlbucci** [comment]
Good idea. I think changing FormBuilders requires a server restart, so you know.

**Comment by Z1MM32M4N** [comment]
@dlbucci Rather, when I try to add the field `builder: FormBuilderWithDateInput` to the appropriate form (without changing the form builder) is when I get errors.

**Comment by dlbucci** [comment]
What's the method it's not finding?  Are you modeling the form after the assessments#edit form (which might be the only place we use that builder)?

**Comment by Z1MM32M4N** [comment]
pm'ed you with a lengthy explanation.

**Comment by Z1MM32M4N** [comment]
So turns out that a server restart did the trick (as referenced in the above pull request!).

**Comment by Z1MM32M4N** [comment]
The next issue is more of a design decision, so I'm wondering what people's thoughts are.

There's a project that serves the assets through the [Rails asset pipeline][1], but it's [out of date][2] right now (1 version behind).

We could very easily download the required assets (Bootstrap 3 DatePicker + Moment.js) and manage installation and updating manually, or we could load the assets through our Gemfile. I'm in favor of the second, but there's no guarantee that this will happen any time soon.

Thoughts? Our options are:

1. Manage all static assets manually
1. Download manually now and patch up Gemfile later
1. Don't do extra work now and install through Gemfile when it becomes available

[1]: https://github.com/TrevorS/bootstrap3-datetimepicker-rails
[2]: https://github.com/TrevorS/bootstrap3-datetimepicker-rails/issues/23

**Comment by icanberk** [comment]
I'd say just do it manually (at least for now). I think we shouldn't be dependent on another party for this sort of simple stuff.

**Comment by Z1MM32M4N** [comment]
I made an initial stab at upgrading the datetime pickers. You can see my progress in #226. I strongly suggest breaking it down by the individual commits, as I removed a lot of cruft as a part of the process.

**Comment by dlbucci** [comment]
Hey @jez, your PR #255 sort of broke check boxes in forms, or at least the check boxes for modules in the assessment edit form.  Each box is now the checkbox, followed by "Has module", a new line, then "module".

**Comment by jez** [comment]
Good catch, I'll take a look when I wake up.

**Comment by icanberk** [comment]
@jez reminder (i know you've been busy over the weekend)

**Comment by dlbucci** [comment]
Can this be closed now?

**Comment by jez** [comment]
It hasn't hit the master branch yet
