### ISSUE TITLE
[Manage Submissions] Integrate gradesheet with annotations

### ISSUE THREAD

**Issue by lykimchee** [autolab/Autolab#1850]
Clicking on the score (pencil for the redesign) for a non-autograded problem will show [this](https://www.figma.com/proto/XbxY3zscou3HAcc9maC8sl/%5BAutolab%5D-Final-Manage-Submissions-UI?node-id=502-2310&scaling=contain&page-id=0%3A1&starting-point-node-id=319%3A1619&hotspot-hints=0) popup, which should be integrated with annotations

**Comment by damianhxy** [comment]
Closed with #1992
