### ISSUE TITLE
Allow lab directory names to contain safe punctuation (at least: hyphen, underscore)

### ISSUE THREAD

**Issue by zackw** [autolab/Autolab#1943]
`>` create a lab directory named "malloc-calibration" (for example)
`>` go to your course's "install assessment" page
`>` see banner: "An error occurred while trying to display an existing assessment on file directory malloc-calibration: assessment file names must only contain lowercase letters and digits with no spaces"
`>` sadface dot gif

I don't see any good reason not to allow '-' and '_' in lab directory names (and maybe also '.')

**Comment by damianhxy** [comment]
> I don't see any good reason not to allow '-' and '_' in lab directory names (and maybe also '.')

The main difficulty is that assessment names are used to form ruby identifiers in the assessment config file, and identifiers have strict naming requirements (alphanumeric + underscore).

A possibility is to strip them from the identifiers, but we have to do so in a way that avoids name collisions.

This was also requested by 15-122 recently (I was planning to track progress in #1393)

**Comment by zackw** [comment]
You could map '-' to '_' internally, as well as folding upper to lower case, and document that after that the assessment name must be a valid Ruby identifier and unique within the course? That would satisfy my needs, at least.  I don't know what 15-122's situation is.

**Comment by zackw** [comment]
(In the documentation, please spell out what it means to be a "valid Ruby identifier".  I don't know Ruby well enough to know the exact rules and I suspect lots of faculty are in the same boat. :-) )
