### ISSUE TITLE
Assessment directory deleted as side effect of "Error loading yaml: Name in yaml doesn't match"

### ISSUE THREAD

**Issue by zackw** [autolab/Autolab#1944]
**Your environment**
CMU's Autolab (v2.10.0)

**Steps To Reproduce**

1. Create an assessment from scratch
2. Have something slightly wrong with the assessment .yml file: I saw this happen because I'd given the wrong name for the assessment *inside* the .yml file, but I wouldn't be surprised if there are other ways to trigger it.
3. Attempt to install the assessment
4. You get an error (good)
5. The entire assessment directory is deleted (VERY BAD)

**Current behavior**

At least some errors in parsing the assessment .yml file will cause the entire assessment directory to be deleted. There is no notification that this has happened.

**Expected behavior**

Autolab should *never* delete the entire assessment directory, no matter what. Why is it even *capable* of doing this? Someone must've written actual code to make it do this. What were they thinking?

(yes I'm a little grumpy right now, I just lost an hour of work and I'm lucky it wasn't *days* of work)

**Comment by 20wildmanj** [comment]
Hi Zack, I'm really sorry your assessment directory was deleted, this was not at all our intention. The deletion is meant only for cleaning up incorrect tar-based imports, but unfortunately it seems to apply to file-system based imports as well as you've experienced. We'll work on a fix ASAP.
