### ISSUE TITLE
hitbox for annotations scrollbars is incorrect

### ISSUE THREAD

**Issue by cg2v** [autolab/Autolab#1946]
**Your environment**
Let us know details such as 
- This appears on both prod and dev autolab at Carnegie Mellon
- I am using chrome on linux

**Steps To Reproduce**

1. Have a submission in assessment with 6 or more problems (or be willing to make your window short if you have 3-4 problems).
2. open the course  & assessment, and click Grade submissions
3. Click "View Source"
4. Reduce the height of the window until a scrollbar appears in the Annotations or Grades subwindow
5. Try to scroll the Annotations or Grades

**Current behavior**
You must click and drag just to the left of the scrollbar in order to make it scroll

**Expected behavior**
You should be able click on the actual scrollbar to scroll it.

**Screenshots**
I can't capture a screenshot of this showing the mouse in the appropriate positions, but we can do a zoom if you would like to see it.

**Comment by damianhxy** [comment]
Reproduced locally, I suspect that this is due to the scrollbar hitbox overlapping with that of the scrollbar for the entire page. Scrolling works as expected if subwindows are placed on the left side of the screen instead.
