### ISSUE TITLE
Orphaned annotations are still broken.

### ISSUE THREAD

**Issue by cg2v** [autolab/Autolab#1949]
**Your environment**
Let us know details such as 
-  Carnegie Mellon's Autolab at https://autolab.andrew.cmu.edu/ 

**Steps To Reproduce**
I'm not sure how you get an annotation with no problem, but at least half the annotations in CMU's database have no problem_id
Identify an assessment with a problem-less-annotation
go to its feedback page

**Current behavior**
Donkey kong

**Expected behavior**
page should render

This was supposed to be fixed in #1658, but when the remarks partial was introduced in #1645, it did not include the relevant change to the annotation grouping loop

**Comment by damianhxy** [comment]
The fix should be to replace `<%= problem.name %>` with `<%= problem.nil? ? "Deleted Problem(s)" : problem.name %>` in `_remarks_panel.html.erb`
