### ISSUE TITLE
Creating submissions rapidly causes duplicate version numbers

### ISSUE THREAD

**Issue by NicholasMy** [autolab/Autolab#1954]
**Your environment**
UB Autolab (https://autolab.cse.buffalo.edu)
Modified variant of Autolab v2.11.0; our modifications (prior to my temporary fix discussed below) should not impact this bug
Forked from your repo after this commit: fa6a5f8aeb10db250ad870613ea2d4e84500d0a2

**Steps To Reproduce**
1. Create a submission to an assessment with your browser devtools open (so that you can capture the network traffic)
2. Copy the POST request to `/courses/<course>/assessments/<assessment>/handin` as a Curl command so we can resubmit it.
  * In Firefox, this is in the "Network" tab of devtools, then right-click the POST request to `handin`, which returned a 302, click `Copy Value > Copy as cURL`
3. Write a Bash script to submit that POST request many times with the Curl command your browser gave you. Note the `&` at the end of the command so that it runs in the background instead of waiting for a response. Here's my example you can adapt:
```bash
#!/bin/bash

for i in {1..100}; do
    curl 'http://localhost:81/courses/AutoPopulated/assessments/homework5/handin' -X POST [...] --\r\n' &
done
```
4. Run your script.
5. Look at the handin history page. (`/courses/<course>/assessments/<assessment>/history`)

**Current behavior**
The handin history page shows multiple submissions with the same version number. Only one of the submissions has the attachment included. Every submission with a duplicate version number counts against the maximum submissions for the assessment. See the screenshots below.

**Expected behavior**
Multiple submissions should not have the same version number. Every submission should have an attachment associated with it (assuming the student attached something). The number of submissions remaining should be  equal to `max submissions - latest version number` (assuming there are no deleted submissions).

**My fix**
We temporarily band-aided this in our implementation by preventing submitting more frequently than once every 5 seconds. I think there should be a better solution, though.

[Temporary fix commit](https://github.com/UB-CSE-IT/Autolab/commit/c0bf5e4ba523d894f9dfb596af5d8bad91135437)

**Screenshots**
![2023-07-25_12_58](https://github.com/autolab/Autolab/assets/32116122/5cef6147-363b-4546-9c4e-ff53d5a80dbd)

![2023-07-18_14_57](https://github.com/autolab/Autolab/assets/32116122/b3a8b80f-43bc-4803-a623-4926aef18c71)
Max submissions is 150, my latest version is 24, yet I only have 48 submissions left.

**Comment by 20wildmanj** [comment]
Thank you for submitting this issue! I'm curious, how prevalent was it for students to rapidly make submissions before your temporary fix?

**Comment by NicholasMy** [comment]
Thanks for replying so quickly. I don't think this will affect many people. This exact issue has never actually been reported to me. I discovered it accidentally while debugging something else: a professor reported that, very rarely, an embedded form submission doesn't get the file attached. I think this may be related, but I'm not certain. If students have run into this in the wild, I'm sure they just submitted again and never told anybody about it. Most professors allow unlimited submissions, so it wouldn't be worth complaining about.

**Comment by 20wildmanj** [comment]
I've attempted to reproduce this issue with the steps given, but did not get the behavior shown in this issue, submission numbers were properly generated and no duplicates appeared, for both an autograded and non-autograded assignment.

**Comment by damianhxy** [comment]
The race condition lies in `submoission.rb#set_version`, where `self.version = 1 + assessment.submissions.where(course_user_datum: course_user_datum).maximum(:version)`

Could consider using locks: https://stackoverflow.com/questions/24587403/rails-activerecord-how-can-i-lock-a-table-for-reading
