### ISSUE TITLE
Mandatory nicknames

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#196]
If a user without a nickname visits the site, they should be forced to give themselves a nickname. This was how the previous autolab system worked, but somehow this behavior disappeared in the new system.

**Comment by dlbucci** [comment]
What is the reason for this?  I removed this check when I rewrote some CUD editing logic, but I don't see why users can't leave their nickname blank.

**Comment by droh** [comment]
If users don't have nicknames, then it messes up the scoreboards.

-- David O'Hallaron
-- Prof of CS and ECE, Carnegie Mellon University
-- GHC 7517, x8-8199
-- http://www.cs.cmu.edu/~droh

**Comment by jez** [comment]
Is this still an issue?

**Comment by icanberk** [comment]
I think so. We should enforce users to have nicknames if the assessment has scoreboard module. Perhaps redirect them to a set nickname page?

**Comment by icanberk** [comment]
At some point we'll also want to collect things like public keys. So maybe we can have a fill your information page where we ask for all the required info?

**Comment by jez** [comment]
We already have that page, and I'm pretty sure we already have this check:

https://github.com/autolab/Autolab/blob/master/app/controllers/application_controller.rb#L217

**Comment by jez** [comment]
If there's an issue, it might just be that we need to check that condition in more places?

**Comment by jez** [comment]
@autolab/developers I think this is fixed now, right?

**Comment by icanberk** [comment]
Yes, it's fixed.
