### ISSUE TITLE
Hide irrelevant fields on edit CUD page for students

### ISSUE THREAD

**Issue by damianhxy** [autolab/Autolab#1981]
Currently, a student without a nickname is shown an edit CUD page when attempting to access the course.

However, there are many irrelevant fields which they are unable to edit, which may confuse the student (they only need to fill in the nickname field).

The other fields should be hidden to reduce confusion.

**Comment by jsobralgitpush** [comment]
Can i work on this one?

**Comment by damianhxy** [comment]
Sure, assigned!
