### ISSUE TITLE
Grade Submissions page: Adding feedback to a score sometime fails

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#201]
When trying to add feedback to a score, the feedback box pops up and then DKs inside the box the first time, and thereafter, clicking the score doesn't pop up any feedback box. This doesn't occur for every course or assessment. To consistently reproduce this, visit 18447-s15, lab1,a*****r@andrew, and try to add feedback to his score (see screenshot below).

The problem only shows up for certain assessments, even in the same course. For example, 15122-s15,Written 1 is fine for all students and all problems. However, for 15122-s15,Quiz 0, it fails for all students. 

![5640038c-a63e-11e4-905a-a355aa6152c2](https://cloud.githubusercontent.com/assets/2977482/5927544/266dc36c-a641-11e4-897f-ea6cf22f5a0d.png)

**Comment by droh** [comment]
I notice that the issue has been closed, but when I try to add feedback for 18447-s15, lab1, it still DKs.

**Comment by icanberk** [comment]
@droh I just pulled to production. Can you try again please?

**Comment by droh** [comment]
Nope, still broken. To reproduce, visit Grade submissions for 18447-s15,
lab1 and try to add feedback to the first student. The first click, it
displays the feedback box, then DKs inside the box. For subsequent clicks,
there is no response.

-- David O'Hallaron
-- Prof of CS and ECE, Carnegie Mellon University
-- GHC 7517, x8-8199
-- http://www.cs.cmu.edu/~droh

**Comment by dlbucci** [comment]
Ilter, please recompile the static assets if you haven't already.

**Comment by dlbucci** [comment]
I recompiled the assets and this appears to be fixed.
