### ISSUE TITLE
Make a global instructor role to be able to create courses

### ISSUE THREAD

**Issue by 20wildmanj** [autolab/Autolab#2025]
There should be a way for instructors to create new courses without needing an administrator to create the course for them. This will allow instructors to make full use of the import course feature. In order to enable this, there needs to be a global role, similar to administrator, that gives users the ability to create courses. Admins would then manage who receives these roles.

**Comment by damianhxy** [comment]
Potentially superseded by #2032 (namely the overwrite feature)
