### ISSUE TITLE
Gradebook slow to update

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#204]
The 15213-s15 gradebook, with only one assessment in the books so far, is taking about 20 seconds to refresh, which seems about 4 times slower than last semester. Are memcached and the association cache working on milkshark?

**Comment by dlbucci** [comment]
I don't think we're using memcache at the moment, but I think we are using the association cache.  That said, I don't know how effective the association cache is with Rails 4.  It was written for Rails 2 and performance has improved a lot since then, so I'm not sure it's necessary at the moment.

**Comment by droh** [comment]
No longer seems to be an issue.
