### ISSUE TITLE
Database migration failure when deploy with docker-compose

### ISSUE THREAD

**Issue by ecwu** [autolab/Autolab#2043]
**Your environment**
Let us know details such as 
- Which institution's Autolab you are using: self-deploy
- Operating system: Ubuntu 22.04
- Commit hash: 5c0a1c60c10fca1ad2d5ffe90a1bbd9343bf473d
- Ruby version: 3.2.2

**Steps To Reproduce**
1. Follow the docker-compose installation guide till step 7 `make set-perms`
2. Run database migrations with `make db-migrate`

**Current behavior**
```
rails aborted!
StandardError: An error has occurred, all later migrations canceled: (StandardError)

wrong number of arguments (given 4, expected 3)
/home/app/webapp/db/migrate/007_add_instructor_to_users.rb:3:in `up'

Caused by:
ArgumentError: wrong number of arguments (given 4, expected 3) (ArgumentError)
/home/app/webapp/db/migrate/007_add_instructor_to_users.rb:3:in `up'
```

**Expected behavior**

**Screenshots**
<img width="502" alt="image" src="https://github.com/autolab/Autolab/assets/21114722/93ce05b5-7455-4f1c-af30-f6988aa31d10">

**Comment by damianhxy** [comment]
@ecwu Thanks for bringing this to our attention, this seems related to the recent upgrade to Ruby 3.x.

We will take a look at this shortly, but you might be able to work around the issue by prepending `:options=>` to the option hash or splatting it (`**{:default=>false}`)

**Comment by ecwu** [comment]
@damianhxy After modifying all rb files indicated in #2044, the db-migration step can run without error in my deployment. Thanks a lot!

<img width="568" alt="image" src="https://github.com/autolab/Autolab/assets/21114722/0161efaf-ec24-4117-a892-f2419a86aed0">
