### ISSUE TITLE
Course creation fails due to invalid value for `enable_starttls_auto`

### ISSUE THREAD

**Issue by parno** [autolab/Autolab#2048]
**Your environment**
Let us know details such as 
- Which institution's Autolab you are using: https://github.com/autolab/docker
- Operating system:  ubuntu:jammy/amd64
- Docker Repo Commit hash: bc55dafa48d95d35d18a6a2749cf61c3ecfdf8a5
- Autolab Repo Commit hash: 27e35829a54e7d7db288f56b1233c9b43b5006c8

**Steps To Reproduce**
1. Install AutoLab using the Docker Compose installation.
2. Login to the web interface as the AutoLab root user
3. Create a new course

**Current behavior**
The course creation fails with the error:
```
Can't create instructor for the course: Unrecognized :enable_startls_auto value "true"; expected true, false, or nil
```
See screenshot below.

Indeed, I think the relevant line of code is here: https://github.com/autolab/Autolab/blob/27e35829a54e7d7db288f56b1233c9b43b5006c8/config/environments/production.rb.template#L91
where it takes the output of `ENV.fetch`, which should be a string and assigns it to a key that expects a boolean.  Updating the line to:
```
 enable_starttls_auto: ENV.fetch('SMTP_SETTINGS_ENABLE_STARTTLS_AUTO',"true") == "true",
```
seems to fix the problem.

**Expected behavior**
Course is created successfully and the new instructor is emailed.

**Screenshots**

![screenshot](https://github.com/autolab/Autolab/assets/1816417/07a2e16d-16e6-4cc6-865c-6c03e39ce57d)

**Comment by damianhxy** [comment]
I am unable to reproduce the issue

By default, `SMTP_SETTINGS_ENABLE_STARTTLS_AUTO` is configured to be `true` (https://github.com/autolab/docker/blob/master/.env.template)

<img width="326" alt="Screenshot 2024-01-12 at 11 06 29" src="https://github.com/autolab/Autolab/assets/9074856/54d0cd19-c552-4fbb-a066-0df08fdc380e">

Even if the line is commented out in `.env`, `ENV.fetch` correctly sets the value as `nil`

<img width="1381" alt="Screenshot 2024-01-12 at 11 07 36" src="https://github.com/autolab/Autolab/assets/9074856/24771419-af86-43d8-8254-da4b5b266482">

Could I check what your `.env` file looks like (inside the autolab-docker directory)?

**Comment by parno** [comment]
This is with the following in my `.env` file (with appropriate values filled in):
```
  SMTP_SETTINGS_ADDRESS=<cmu SMTP server>
  SMTP_SETTINGS_PORT=25
  SMTP_SETTINGS_ENABLE_STARTTLS_AUTO=true
  SMTP_SETTINGS_DOMAIN=<CMU AD domain>
  SMTP_DEFAULT_FROM=<email address>@andrew.cmu.edu
  HOST_PROTOCOL=http
  HOST_DOMAIN=<Host address>
```

**Comment by damianhxy** [comment]
Ah, I've managed to reproduce the issue - it only occurs when the instructor email does not already exist (since it attempts to send a password reset email)

<img width="1016" alt="Screenshot 2024-01-12 at 22 53 52" src="https://github.com/autolab/Autolab/assets/9074856/928ab9aa-d5f9-4e1a-96af-a2f132d122ff">

I'll work on a fix shortly
