### ISSUE TITLE
Sort and condense course page

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#208]
The course page is going to quickly get out of hand for autolab admins who see every course. Can we sort them by course-name and tighten the display up so that more courses are visible on each page?

**Comment by dlbucci** [comment]
Do we want it by name or display name?

**Comment by droh** [comment]
I'm thinking by display name, since that's what's shown on the page.

-- David O'Hallaron
-- Prof of CS and ECE, Carnegie Mellon University
-- GHC 7517, x8-8199
-- http://www.cs.cmu.edu/~droh

**Comment by icanberk** [comment]
I believe this is fixed.
