### ISSUE TITLE
assessmentInitialize is not a valid hook for assessment config rb file but is included in default rb file

### ISSUE THREAD

**Issue by 20wildmanj** [autolab/Autolab#2085]
Currently, the default assessment template (`lib/__defaultAssessment.rb`) includes a method `assessmentInitialize` as follows:

```
def assessmentInitialize(course)
    super("##NAME_LOWER##",course)
    @problems = []
  end
```

This implies that an instructor can define problems via this hook by modifying the config rb file. However `assessmentInitialize` has been deprecated for years, and is not called during assessment creation, but the code still exists, along with `installProblems`, which was used to install the problems defined by `assessmentInitialize`. This code is all deprecated since importing uses the config yml file as the source of truth. The default assessment config file and the `assessmentInitialize` and `installProblems` code should be removed to prevent confusion.

In a similar vein, the course config file should also be updated to not include `gradebookMessage` as it is also not a valid hook.

**Comment by damianhxy** [comment]
Related to #1926
