### ISSUE TITLE
Unable to leave group while a request is pending

### ISSUE THREAD

**Issue by dwang3851** [autolab/Autolab#2115]
After sending an invite for a group to the wrong person, a student is unable to cancel the formation of the group/leave the group.
This occurs at this screen:
![IMG_2856](https://github.com/autolab/Autolab/assets/67977275/28ff9b16-961b-47cd-8568-1c421cb04f72)

Potential fixes may be including a button to cancel the creation of the group altogether, or assigning someone else as the leader of the group.

**Comment by damianhxy** [comment]
After further investigation, the issue is that a student can't leave a group after requesting to join it but before being confirmed
