### ISSUE TITLE
Update SMTP Config documentation and remove old config from env template

### ISSUE THREAD

**Issue by 20wildmanj** [autolab/Autolab#2177]
With Autolab 3.0 changes, SMTP Mailing configurations moved to the config interface, but documentation / env files still reference the old setup method.

There should be updates to the documentation on SMTP config setup using the interface, removal of smtp related `.env` variables in `.env.template`, and removal of smtp related variables in `production.rb.template`

**Comment by damianhxy** [comment]
See #2168 for more context
