### ISSUE TITLE
README issues

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#218]
There are some important problems we encountered while setting up milkshark that need to be addressed in the installation instructions in the README:
- [x]  Permissions, owners, and groups for the autolab directory tree. 
- [x] What user should Apache run as. 
- [x] How to configure Apache. 
- [x] How to add shib support
- [x] How to add ssl support. 
- [x] How to add email support.

**Comment by icanberk** [comment]
7. How to add MOSS support.

**Comment by icanberk** [comment]
@andrewwuan you're more knowledgeable about the first 5. I'm writing a wiki article about 6.

**Comment by andrewwuan** [comment]
https://github.com/autolab/Autolab/wiki/Setup-Production is updated. Let me know if there's any issues!

**Comment by jez** [comment]
@andrewwuan looks like that's a broken link?

**Comment by dlbucci** [comment]
https://github.com/autolab/Autolab/wiki/Setting-up-Production-Environment-on-Ubuntu
