### ISSUE TITLE
yml problem fields are not preserved upon assessment deletion

### ISSUE THREAD

**Issue by 20wildmanj** [autolab/Autolab#2182]
**Steps To Reproduce**
1. Use this assessment yaml file: 
[homework03.yml.txt](https://github.com/user-attachments/files/16721169/homework03.yml.txt)
2. Create a `homework03` folder within a course folder and use the import assessment feature to import the configuration data
3. Delete the assessment
4. See that `problems` turns into an empty array when previously there was a single problem
![Screenshot 2024-08-22 at 10 29 34 PM](https://github.com/user-attachments/assets/1e0982ce-b573-4bfe-a036-6199dbb7061d)

**Expected behavior**
`problems` field should not be wiped on deletion. Instructors might delete an assessment and then re-import it if they wanted to change configuration settings programmatically

This issue may be related to #2053.

EDIT: Additional Issue with yml file: 

yml file does not auto propagate the name field when it does not exist or it is different from name. Seems to be a bug that occurs for every yml file.

**Comment by dwang3851** [comment]
- Difficult to resolve due to the fact that we dump the yaml file on any commits to database
- Ideally, users export their assessments before deleting them to avoid this issue
- Could potentially delete the yml file entirely after an assessment is deleted
