### ISSUE TITLE
Standardize Tables

### ISSUE THREAD

**Issue by Z1MM32M4N** [autolab/Autolab#224]
We're using various libraries to implement our tables. As far as I can see, these are

- SlickGrid
- DataTables
- KeyTables (used in conjunction with DataTables?)
- vanilla JavaScript & HTML

Both for maintainability and UX, we should standardize these to use all one library. What direction should we take? I think we'd want to use some sort of library, but what we end up choosing doesn't necessarily have to be from this list if someone knows of a better solution. Thoughts?

**Comment by dlbucci** [comment]
I should point out that SlickGrid is used for performance on the gradebook.  Displaying tables that large was starting to be noticeably non-performant, which is why Tom switched us.  So I'm not sure I'd recommend changing that, or switching other tables to that either.

**Comment by Z1MM32M4N** [comment]
Hmm, okay. But you're saying you're not sure whether SlickGrid will be too much overhead to load on some of the smaller tables?

**Comment by Z1MM32M4N** [comment]
Side note: SlickGrid hasn't been inactive for about a year: https://github.com/mleibman/SlickGrid

**Comment by icanberk** [comment]
Merged to #231
