### ISSUE TITLE
Standardize Static Assets

### ISSUE THREAD

**Issue by jez** [autolab/Autolab#225]
The static asset discipline is a little unnerving. Here's a short list of things I'd like to see improved:
- [x] One (1) version of jQuery, ideally jQuery 2.x, used throughout the app

Right now, we are loading both jQuery 1 and 2. One is being loaded over a CDN, and I think another is being loaded through the asset pipeline. Which leads me into
- [ ] better usage of Rails' static asset pipeline

If used correctly, it can ease the efforts of minification as well as managing and upgrading dependencies. I don't think that many plans for maintenance or upgrading have been made with respect to this area, so I'd like to make sure that we have
- [x] Up-to-date versions of static assets, to include
  - [x] Bootstrap
  - [x] jQuery

Later, this list will include whatever library we choose for displaying tables (#224), as well as date/time pickers (#181). Keeping assets up to date is like taking your vitamins: you do it so you don't get sick down the road.

This is a pretty broad-sweeping issue, which means it'll be hard to make measured progress towards it. However, I still think it's a good idea to get these ideas out into the open so we can make a good plan going forwards.

**Comment by icanberk** [comment]
I think jQuery stuff is pretty standardized at this point but you should take another look and update this issue.

**Comment by dlbucci** [comment]
It would be nice if #316 was fixed, though.

**Comment by dlbucci** [comment]
What remains to be done for the last check?  If it's substantial, can we make a new issue and close this one?

**Comment by jez** [comment]
I'm working on this for the process of #345. Because this issue is inspiring my solution for that one, we may as well keep it open, but we can close it if you want.

**Comment by icanberk** [comment]
Any progress on this?

**Comment by jez** [comment]
Yes, I have a branch for this and have started working on it, but I won't be able to work on anything related to Autolab until at least Tuesday.

**Comment by remzr7** [comment]
Standardized static assets with recent pull requests
