### ISSUE TITLE
Consistent Form Stylings

### ISSUE THREAD

**Issue by Z1MM32M4N** [autolab/Autolab#230]
We should make forms that look like this

![screen shot 2015-01-31 at 6 22 11 pm](https://cloud.githubusercontent.com/assets/5544532/5990257/91a3421e-a976-11e4-89fe-e6a580bdb4a4.png)

look more like this

![screen shot 2015-01-31 at 6 21 53 pm](https://cloud.githubusercontent.com/assets/5544532/5990260/9bcc605e-a976-11e4-9052-d9fe9eac755e.png)

in my opinion. I could switch this over pretty easily if it's the design direction we want to take. I think it would also work towards #101.

**Comment by icanberk** [comment]
Merged to #231
