### ISSUE TITLE
Design Overhaul

### ISSUE THREAD

**Issue by icanberk** [autolab/Autolab#231]
- [x] Pages should be centered with a max-width
- [x] Font sizes should be more consistent and larger
- [x] Consistent Form Stylings
- [ ] We should allow a serif font for old screens/computers
- [ ] Tables should be standard (@jez)
- [x] Make the footer links  more visible
- [x] On the course home page, the items in the list of assessments seem to be a little too far apart Tighten these up.
- [x] Flash warnings should be styled
- [x] `Download as application/x-gzip + View Source` should become icons
- [ ] There should be a form builder for checkboxes (@jez)
- [x] Should warn you if you quit without saving on grading page

**Comment by jez** [comment]
@ican should we close this now?

**Comment by icanberk** [comment]
When it lands to master
