### ISSUE TITLE
Improve Quiz Feature

### ISSUE THREAD

**Issue by icanb** [autolab/Autolab#244]
- [ ] It's not clear how the instructor picks the "correct answer". We should make it so that there is a light green background color to the option that is picked.
- [ ] We can shuffle the order of options when the student takes a quiz.
- [ ] There should be a feedback page. I think the user should at least be able to see what questions were wrong and which ones were correct.
  *\*  displays the quiz with disabled options boxes
  *\* picks the options that the user has selected in that submission
  *\* put red/green background colors for the correct and incorrect answers

**Comment by devanshk** [comment]
Closing because the quiz feature was removed in #575
