### ISSUE TITLE
Fix implementation of Quiz Feature

### ISSUE THREAD

**Issue by icanberk** [autolab/Autolab#250]
- [ ] `quiz` field in assessments should be `isQuiz`
- [ ] `quizData` should not be a required field
- [ ] There should be a migration that assigns default values for these two new fields. Current migration is not enough and causes problems.
- [x] `autolab:populate` should consider these fields. It is currently broken. Preferably we should add a sample quiz to this script.

**Comment by andrewwuan** [comment]
Just to make sure: is this for https://github.com/autolab/Autolab/pull/47?

**Comment by icanberk** [comment]
Yes, It's merged into `develop` right now.
