### ISSUE TITLE
Destroy submission not working

### ISSUE THREAD

**Issue by robsimmons** [autolab/Autolab#256]
Specific workflow:

go to all submissions -> click on a username to get their list of submissions -> click on "destroy" in the popup window

Instead of going to the confirmation page it just says "error destroying this sumbission"

Clicking "Destroy" on the main all-submissions page works.

**Comment by dlbucci** [comment]
This has to do with params[:yes] now being checked when submissions#destroy is called.  But that only gets set when submissions are destroyed from the 'manage submissions' page.  So we either need to link to the destroyConfirm action on the history page, or we need to add a ?yes=true to the link on the history page.

**Comment by dlbucci** [comment]
PS if you click the destroy link in the actual manage submissions table (not the popup), it will work correctly.
