### ISSUE TITLE
Feedback string is not saved/displayed when there is a problem with autograde_done

### ISSUE THREAD

**Issue by icanberk** [autolab/Autolab#258]

**Comment by icanberk** [comment]
@dlbucci I thought you could address this while dealing with autograde.rb

**Comment by dlbucci** [comment]
@icanberk, oh I'm addressing more than that.  Autograding is getting some changes, brother.

**Comment by dlbucci** [comment]
So is this still an issue?  I kind of forget what this means/if we still want it, given that we now don't want to smoosh feedback on autograder errors?
