### ISSUE TITLE
Tango Polling should be configurable

### ISSUE THREAD

**Issue by dlbucci** [autolab/Autolab#262]
There should be an option in "lib/autoConfig.rb" that lets you easily switch to Tango polling.  Currently, this requires you to change code in 'saveAutograde' and 'autogradeDone'.

**Comment by dlbucci** [comment]
@mihirpandya @yrkumar how does Tango respond to addJob requests that provide a callback_url key that is an empty string?  Will it try to callback to the blank url?

**Comment by mihirpandya** [comment]
Yes if the callback_url key is defined, it will try to make the callback, which will fail since it was blank. However, that doesn't mean you cannot poll Tango.

**Comment by dlbucci** [comment]
Okay, just wondering, because it's easier to change that value to "" than it is to remove the key entirely.  I I think it would be an improvement to check for empty strings, because I'm gonna add a config setting on the front end to enable polling, and that will probably send empty callback_url's to Tango.

**Comment by mihirpandya** [comment]
OK yeah it makes sense to do some basic error-checking on the callback_url. But callback and polling are not mutually exclusive so you should be fine.

**Comment by dlbucci** [comment]
Sure, I just figured you don't need to be making unnecessary HTTP calls.
