### ISSUE TITLE
Grace days used (GDU) has disappeared from the student gradebook (high priority)

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#268]
For some inexplicable reason, the Grace Days Used (GDU) column has disappeared from the student's gradebook view. Thus, students have no idea how many grace days they've used, which is clearly not good. We'll need to fix this ASAP.

**Comment by dlbucci** [comment]
Did this just occur or has it been like this for some time?

**Comment by dlbucci** [comment]
Also, does the course actually have grace days?  If the course has 0 grace days, the column won't show up, but if it has some number of grace days, the column should be there.

**Comment by droh** [comment]
You're right Dan. That column wasn't showing up because the the 213 instructors didn't assign any grace days.
