### ISSUE TITLE
Admins/Instructors cannot use TA assessment options

### ISSUE THREAD

**Issue by RONNCC** [autolab/Autolab#274]
In the past admin/instructor accounts would also have a TA feature set they could do - e.g. release grades for their assigned section whereas now it only shows the default feature set for admins - e.g. bulk release which is problematic

e.g. 
old: http://i.imgur.com/vlz0yQh.png
modern: only the left table is possible

> bug label

**Comment by dlbucci** [comment]
I think instructors can do this, it's just that the CA bit isn't set by default anymore (which it can be by editing your own course user information).  If that's the case, we should set that bit by default again.

**Comment by RONNCC** [comment]
you're right :) - sorry, missed the CA bit part of that. But yup - that should be a quick fix?
