### ISSUE TITLE
Scoreboard DKing

### ISSUE THREAD

**Issue by robsimmons** [autolab/Autolab#281]
Not sure what's going on here...

https://autolab.cs.cmu.edu/courses/14/assessments/303/scoreboard

**Comment by ymzong** [comment]
Hi @robsimmons, we have chosen to adopt a stricter JSON format string for scoreboard, and I have manually fixed it such that your scoreboard now loads here `https://autolab.cs.cmu.edu/courses/14/assessments/303/scoreboard`.

You can view the new format by going to `Admin Scoreboard` under the assessment.

**Comment by robsimmons** [comment]
Ok - any chance that could give a better error message?

**Comment by ymzong** [comment]
@robsimmons Definitely. I will add this to our issues list.
