### ISSUE TITLE
Course Creation Issue on Entering Andrew ID

### ISSUE THREAD

**Issue by sanopa** [autolab/Autolab#29]
When creating a course and using the Andrew ID (without @andrew.cmu.edu), the course is created but throws an error on creation. Here is the error it throws:

```Mysql2::Error: Field 'user_id' doesn't have a default value: INSERT INTO `course_user_data` (`course_id`, `created_at`, `instructor`, `updated_at`) VALUES (3, '2014-11-07 23:10:07', 1, '2014-11-07 23:10:07')```

**Comment by dlbucci** [comment]
Do we know if this is still happening?

**Comment by dlbucci** [comment]
Actually, I believe it is.  When creating courses, we save the course before creating/finding an instructor, and if that fails because there is no valid email given, then we run into this.  At least, that's my guess.

**Comment by jez** [comment]
Closed by #280
