### ISSUE TITLE
80-character length for code view

### ISSUE THREAD

**Issue by robsimmons** [autolab/Autolab#290]
Currently, no matter how much I shrink my font, I cannot get the code view to show 80 characters on a single line, making reasonably formatted code appear terribly formatted.

Example: the line below is 79 characters long.
![bad code wrap example](https://cloud.githubusercontent.com/assets/442315/6232006/63881e6c-b697-11e4-997e-91abc22a8c57.png)

**Comment by dlbucci** [comment]
Is this a style concern or a grading concern?  Either way, we should fix this, but if you're interested in finding lines greater than 80 characters long, there should be a checkbox at the top of the page that will highlight such lines red.

**Comment by robsimmons** [comment]
Right - the checkbox is good for style grading, but we'd actually like to have the code readable while we're grading style.

As far as I'm concerned, the more work Autolab does to showing exactly 80 chars of code the better, because then the ultimate reason that we can give for why people have to respect the 80 char limit is "because that's what Autolab does and it's too hard to read your code on Autolab otherwise." (I'll usually have one student a semester who really doesn't buy the "massive historical precedent" argument :smile:)

**Comment by dlbucci** [comment]
Fixed by #307.
