### ISSUE TITLE
Option to ignore certain files in zipfiles

### ISSUE THREAD

**Issue by RONNCC** [autolab/Autolab#293]
Some students have a habit of turning in x~ the backup file as well as x or also turning in **pycache**/ which are both extraneous

> feature request
> low priority

**Comment by dlbucci** [comment]
Is this for the listArchive page?  I suppose we could have a checkbox that tries to hide backup/hidden files.

**Comment by jez** [comment]
Perhaps you should distribute a Makefile in your handout or provide students with an explicit tar command such that it excludes those files?

**Comment by RONNCC** [comment]
@dlbucci  yup

@jez  they don't know how to use Makefile's that's out of scope.

**Comment by jez** [comment]
The complexity of a tar command exceeds that of a make command. As Dan said though, we can consider a checkbox that hides or removes extraneous files.

**Comment by devanshk** [comment]
As mentioned by @jez, this is something that can be addressed client-side, and doesn't seem to cause any big problems.

**Comment by RONNCC** [comment]
@devanshk hmm I think disagree - it would still (probably) be helpful to allow a .listignore or something (similar to .gitignore)

The use case was CS classes below 122 where they use like right-click zip; the list archive is then scary because they see all these random files they never knew about and get confused
