### ISSUE TITLE
Sort on multiple fields

### ISSUE THREAD

**Issue by RONNCC** [autolab/Autolab#294]
Being able to sort by section and then being able to sort by name would be very useful ....

> Enhancement

**Comment by dlbucci** [comment]
What page would this be on? Gradesheet?

**Comment by ymzong** [comment]
@dlbucci Does our gradesheet use stable sorting on the rows?

**Comment by RONNCC** [comment]
@ymzong i don't think it does _now_ I think it did previously, otherwise I could just click multiple tabs

**Comment by dlbucci** [comment]
Somewhat unrelated, but the gradesheet js appears to be broken at develop HEAD, so we should probably just make sure this works before we merge it to master.

**Comment by dlbucci** [comment]
I think this works again.  If you click name, then section, you get everyone sorted by section, then alphabetically within each section.

**Comment by RONNCC** [comment]
you guys are closing a lot of things today :)
