### ISSUE TITLE
Increase size of - in Gradesheet / Retarget Buttons

### ISSUE THREAD

**Issue by RONNCC** [autolab/Autolab#297]
So when you go to gradesheet/any grade input field and hit the - to enter the grade .. it's kind of small, can we increase that font or retarget the field to the box rather than the - itself?

**Comment by jez** [comment]
You should now be able to click anywhere within the same region bounded by the text box that appears once you click on the `-` sign.

**Comment by RONNCC** [comment]
yay :smile:
