### ISSUE TITLE
Assignment Statistics Page Broken 

### ISSUE THREAD

**Issue by RONNCC** [autolab/Autolab#300]
When you go to a class -> assignment -> view statistics you either get completely nonsensical results, or none at all (though course statistics on top of the gradebook seems? to work).

E.g.

 http://i.imgur.com/855yjbi.png (note, none of them are 110 TAs, I think they're 122?) 
or 
http://i.imgur.com/KlcjFHX.png (this is from a fully-released & graded exam)

**Comment by jez** [comment]
We have a fix for this issue and it will be included in the next release.

**Comment by RONNCC** [comment]
This still doesn't seem to be fixed?

**Comment by dlbucci** [comment]
Statistics now appear on the Manage Course page.  Do they look more reasonable?

**Comment by RONNCC** [comment]
What about per-assignment statistics? Those still seem broken

**Comment by icanberk** [comment]
They seem fine to me. Can you hard-refresh your browser?

**Comment by dlbucci** [comment]
Yeah it just looks like the images failed to load, but the statistics are fine.

**Comment by RONNCC** [comment]
http://i.imgur.com/g7UkOoc.png still even hard refreshing - those are 122 ta's?

**Comment by icanberk** [comment]
Oh I thought you were talking about the broken image links. We need to look into wrong grader issue.

**Comment by RONNCC** [comment]
reopen bump?

**Comment by icanberk** [comment]
Can you make a new issue?

**Comment by RONNCC** [comment]
done @400
