### ISSUE TITLE
Contact Us and Maintenance Pages Need an Update

### ISSUE THREAD

**Issue by jez** [autolab/Autolab#314]
The "Contact" link at the bottom of every page and the "Autolab is down for maintenance page" is outdated with regard to the design updates that have taken place.

- [x] Contact page
- [x] Maintenance page

**Comment by dlbucci** [comment]
Gotta keep that maintenance mode fresh.

**Comment by jez** [comment]
Right now, the "Contact Us" page is in `/public`. but it'd be nice if we could use the same template as `app/layout/application.html.erb`. Is there some way to reconcile this? It seems like we'd have to create a specific route that wasn't attached to any sort of model.

**Comment by jez** [comment]
Jk, figured it out. Yay for learning new things ^.^
