### ISSUE TITLE
Javascript is Broken on submissions#index

### ISSUE THREAD

**Issue by dlbucci** [autolab/Autolab#316]
- [ ] jQuery fails after shortening the table to a useless 10 rows, but before adding the pagination, or the history popup stuff.

**Comment by jez** [comment]
I'll take a look at this in the morning. I don't quite understand what the issue is, but it sounds like it's pretty critical?

**Comment by dlbucci** [comment]
Actually not quite.  It's just that the right jquery doesn't seem to get loaded, so the page doesn't get paginated.  I thought it was shortening the table, but now I don't think so.  That said, we might not even want pagination (at least one professor has complained about it), so we could just add a filter/search, and fix the history popup.

**Comment by robsimmons** [comment]
+1 getting rid of paganiation would be amazing, I dunno if I'm the professor that complained.

**Comment by icanberk** [comment]
Fixed now.
