### ISSUE TITLE
Lab page header should show display name

### ISSUE THREAD

**Issue by namanbharadwaj** [autolab/Autolab#327]
It currently shows the "lab name" from the lab settings, but it should show the "display name" to match the breadcrumbs.

**Comment by icanberk** [comment]
Hi Namen, Do you mind posting the link here? I'm not clear on which page you're talking about.

**Comment by namanbharadwaj** [comment]
For example, on the page for the current 15-210 lab, the top of the content section, just under the breadcrumbs, says "babblelab," while it should say "BabbleLab" (as that's the display name, and what is shown in the breadcrumbs): https://autolab.cs.cmu.edu/courses/19/assessments/372

**Comment by icanberk** [comment]
Got it. Thanks!
