### ISSUE TITLE
Can't view syntax highlighted source

### ISSUE THREAD

**Issue by robsimmons** [autolab/Autolab#328]
Clicking on "View Syntax Highlighted Source" in

https://autolab.cs.cmu.edu/courses/14/assessments/219/submissions/52522/view?header_position=2
Title: Submission Version 3 for Prog 3 - Images (__REDACTED__@andrew.cmu.edu) 

takes me to 
https://autolab.cs.cmu.edu/courses/14/assessments/219/submissions/52522/view?header_position=0
Title: Edit __REDACTED__@andrew.cmu.edu's Submission #3 for Prog 3 - Images

**Comment by dlbucci** [comment]
Sssshhhhhiiii... I can fix this.
