### ISSUE TITLE
Grade should be auto-refreshed

### ISSUE THREAD

**Issue by lxfschr** [autolab/Autolab#33]
When a student submits a file the view handin history page should automatically load the grade once it has been calculated.

**Comment by devanshk** [comment]
We'll probably end up implementing this with WebSockets in Rails 5. Keeping this issue open for when we get there.

**Comment by victorhuangwq** [comment]
Currently being addressed and in progress with a Websocket implementation here. 
https://github.com/autolab/Autolab/pull/1167
