### ISSUE TITLE
Local handin broken

### ISSUE THREAD

**Issue by robsimmons** [autolab/Autolab#335]
Since the update, it seems. After copying hw.tgz to the directory designated by visiting https://autolab.cs.cmu.edu/courses/14/assessments/303/local_submit?user=rjsimmon@andrew.cmu.edu I get this:

```
$ curl -s -k -F submit=hw.tgz 'https://autolab.cs.cmu.edu/courses/14/assessments/303/local_submit?user=rjsimmon@andrew.cmu.edu'                                                                   
There was an error saving your submission. Please contact your course staff
```

**Comment by dlbucci** [comment]
I'll take a look at this today.
