### ISSUE TITLE
Editing code annotations does not correctly assign score

### ISSUE THREAD

**Issue by navignaw** [autolab/Autolab#338]
After editing points allocated to code annotations/comments (and clicking "Save Changes"), the points are appended to the comment as a string rather than updating the numerical value.

![autolab-bug](https://cloud.githubusercontent.com/assets/4044514/6378998/e74b8b9c-bcfc-11e4-9fcf-078e2f331f3d.png)

**Comment by dlbucci** [comment]
Tarnation.  I think an annotations update is in the works that will simplify annotations and fix this issue.
