### ISSUE TITLE
Allow square brackets in annotations

### ISSUE THREAD

**Issue by jez** [autolab/Autolab#347]
Right now, using `[...]` in an annotation is not possible, even though there are many circumstances where this behavior is desirable.

**Comment by dlbucci** [comment]
How was this not possible? We were encoding the text to allow them.

**Comment by icanberk** [comment]
That was why we were doing it?

Idk, but when we called .split("[") it was splitting the comment itself.

**Comment by dlbucci** [comment]
I think this has to do with the bug where changing scores lead to the scores being appended to the comment body, and those comments were getting ill-parsed.
