### ISSUE TITLE
Annotations model and code should be updated

### ISSUE THREAD

**Issue by dlbucci** [autolab/Autolab#359]
Now that we actually use the comment, value, and problem columns, we can simplify a lot of the annotations code.

**Comment by jez** [comment]
Look at Dan closing issues in PRs XD

**Comment by dlbucci** [comment]
Some day long after GitHub is no more, someone will clone this repo and see this message and ask 'what the hell does fixes #359 mean?'

**Comment by icanberk** [comment]
Yeah, Dan's granchildren will have hard time understanding the family
heritage.
