### ISSUE TITLE
Graders themselves use UTC?

### ISSUE THREAD

**Issue by robsimmons** [autolab/Autolab#363]
It's Monday night and I'm seeing this on top of the grading output, not a big deal but a bit out of sync with other timestamps.

```
Autograder [Tue Mar  3 01:05:32 2015]: Received job 15122-s15_editorcheck_3_mili@andrew.cmu.edu:477
Autograder [Tue Mar  3 01:05:39 2015]: Success: Autodriver returned normally
Autograder [Tue Mar  3 01:05:39 2015]: Here is the output from the autograder:
```

**Comment by dlbucci** [comment]
We've had some timing issues on the VMs, where the times have been off.  @mihirpandya or @yrkumar would be able to explain in more detail/fix the problem.

**Comment by devanshk** [comment]
We haven't received any complaints about this since 2015, so closing this issue.
