### ISSUE TITLE
Moss dies on unrecognized archive type

### ISSUE THREAD

**Issue by RONNCC** [autolab/Autolab#367]
Error: http://i.imgur.com/ueo57VQ.png

Could I have some debugging info for what the issue file in question is? Also is there anyway to rechange the file's name in autolab to change it to (presumably) the correct extension?

Also given the isArchive directive - is autolab still able to ignore random single files lying around?

**Comment by dlbucci** [comment]
Autolab now detects archive type and can extract tar, tgz, and zip files (at least, that is the goal).  It detects the type of the archive based on the unix 'file' command, so that's what the submission is confusing here.

**Comment by RONNCC** [comment]
so how do i know what the issue was.....?

**Comment by dlbucci** [comment]
What type of archive were you submitting?

**Comment by RONNCC** [comment]
no clue :D they (should) all be zips. hence why i was wondering if you could show me the problem file.

**Comment by dlbucci** [comment]
No, but I can probably add robustness to moss for when a non-archive is submitted by skipping the file and reporting it.

**Comment by RONNCC** [comment]
that would be great!
