### ISSUE TITLE
All writeups gone

### ISSUE THREAD

**Issue by robsimmons** [autolab/Autolab#380]
All 122's programming assignments take me to the "There is no writeup for this assessment." page when I click on "View writeup" - there's always a writeup for our programming assignments, in particular https://autolab.cs.cmu.edu/courses/14/assessments/395/writeup should definitely be a writeup and I've confirmed that editor-writeup.pdf is there in AFS.

**Comment by dlbucci** [comment]
I'm going to close this as it's related to the CMU deployment and AFS malfunctioning, not the Autolab codebase.
