### ISSUE TITLE
Assignment deletion doesn't delete autograder feedback

### ISSUE THREAD

**Issue by robsimmons** [autolab/Autolab#382]
Not a big deal, but it causes the handin directory to have autograde.txts where it has no corresponding .tgzs, and if autograding failed for some reason this could lead to a confusing case where students were seeing feedback from deleted submissions. I'm not sure what the right behavior here is, but one reasonable thing would be that when

rjsimmon@andrew.cmu.edu_1_handin.tgz
gets moved to archive/deleted_rjsimmon@andrew.cmu.edu_95851_handin.tgz

rjsimmon@andrew.cmu.edu_1_editor_autograde.txt
gets moved to archive/deleted_rjsimmon@andrew.cmu.edu_95851_editor_autograde_.txt

**Comment by dlbucci** [comment]
Fixed by #416
