### ISSUE TITLE
Late Slack isn't configurable per assignment

### ISSUE THREAD

**Issue by RONNCC** [autolab/Autolab#395]
as per title - it was in legacy autolab

also the default was >0  in legacy autolab?

**Comment by dlbucci** [comment]
I just checked, and this was not in legacy autolab.  You can still set late slack for the whole course.  Is there a reason you would want different late slacks depending on the assessment?

**Comment by RONNCC** [comment]
Sorry you're right!

If certain assignments are placeholders for grades in Autolab - e.g. written homework vs actual programming assignments with a certain slack.

**Comment by jez** [comment]
If you have a need for assignments to be accepted later, you should either move the time submission closes back or grant extensions. Late slack is not really designed to be a feature.

**Comment by RONNCC** [comment]
kk
