### ISSUE TITLE
Per Assignment Statistics Broken

### ISSUE THREAD

**Issue by RONNCC** [autolab/Autolab#400]
http://i.imgur.com/g7UkOoc.png has 122 ta's instead of the correct ones?

**Comment by ymzong** [comment]
I'm suspecting that it might be a user_id / cud_id mess-up...

**Comment by dlbucci** [comment]
Good catch!
https://github.com/autolab/Autolab/blob/master/app/controllers/assessment/grading.rb#L437

**Comment by RONNCC** [comment]
surprise test case? haha
