### ISSUE TITLE
Brush Up Documentation

### ISSUE THREAD

**Issue by jez** [autolab/Autolab#403]
Very little of the newer versions of Autolab is documented. We should soon before we market Autolab to a wider audience. We can't exactly redirect people to docs.autolab.cs.cmu.edu where the first bullet point tells them to send an email to ugradlabs.

Ideally, our documentation should have up-to-date screenshots (or as up-to-date as possible), listings, and maybe even sample terminal output from certain commands.

Here's a list of some things I think we should make sure is well documented--feel free to edit this description and add to the list:

- [ ] Installation instructions for the Autolab front end for
  - [x] Mac OS X
  - [x] Ubuntu Linux
- [ ] Installation instructions for Tango back end for
  - [ ] Mac OS X (If this is complicated right now, then we should make sure that it's _very_ clear, because people _will_ want to do this to try it out.)
  - [x] Ubuntu Linux
- [ ] How to create a class
- [ ] How to create an assessment
- [ ] Tips for managing a course
  - We have a lot of buttons, menus, and options that have very similar names: Manage submissions, Grade submisisons, Manage course, etc. It'd be nice to just give some general tips/FAQ, like "I want to do this => go look here"

Ideally, we'd move this into the Autolab Wiki rather than docs.autolab.cs.cmu.edu so all of our documentation is centrally located and easier to keep up to date.

**Comment by ymzong** [comment]
I can take front-end installation on Ubuntu, since it's my primary OS. With some help from @mihirpandya, I'd like to write a bash script for setting up both Tango and front-end on a same machine.

**Comment by jez** [comment]
A bash script would be nice!

**Comment by icanberk** [comment]
We already have the wiki page for installation of dev front-end on Ubuntu and Mac.

I think we should also be migrating non-cmu specific pages on docs to github wiki.

**Comment by jez** [comment]
I took a first stab at this issue. [Checkout our new Wiki!](https://autolab/Autolab/wiki)

__What's been done__
- I refactored the existing content (what little was there) to add structure
- I added a sidebar for easy navigation
- I added some skeleton articles to the sidebar for articles that currently exist on docs.autolab.cs.cmu.edu. We'll want to migrate these and more once we determine what's relevant.

__Notes to the documentation writer__
- GitHub Wiki's permit directory structure, but each article is uniquely determined by it's name, so you can't have two Wiki pages with the same name.
- You can clone Wikis! It kind of defeats the "quick" aspect of Wikis, but I find that I write _much_ better documentation when I make the changes locally, especially if it's a longer update.

It should be fairly apparent what the structure of the Wiki is and where to add new pages, so if you have time, migrate a page or two, checking to make sure the references are still up to date. The sooner we have up-to-date documentation the closer we are to being able to ship Autolab to more people!

/cc @autolab/developers

**Comment by icanberk** [comment]
Ohh fancy. Didn't know you could style the sidebar. How did you do that?

**Comment by jez** [comment]
Just add a file called `_Sidebar.md`. There's no fancy templating (like you'd get in a Jekyll blog for example), but you can hard code the list of wiki pages that you have, which is almost as good.

**Comment by nayak16** [comment]
Docs updated. Closing
