### ISSUE TITLE
Format extension dates with moment.js

### ISSUE THREAD

**Issue by jez** [autolab/Autolab#404]
- [x] Dates like this on the assessment page should be formatted using the same moment.js formatting as other dates.

![screen shot 2015-03-18 at 4 35 21 am](https://cloud.githubusercontent.com/assets/5544532/6705174/5660a7f2-cd28-11e4-8e40-eb4e0242bca2.png)

**Comment by jez** [comment]
@dlbucci I think this is fixed now, right? I wonder why it didn't get closed when the commit landed.

**Comment by dlbucci** [comment]
Yeah, this should be fixed.
