### ISSUE TITLE
Refactor user metadata population

### ISSUE THREAD

**Issue by jez** [autolab/Autolab#408]
The changes introduced in #396 regress back towards having CMU-specific code.

The underlying issue is validating or sanitizing user metadata (name, major, etc.) before populating the relevant Autolab fields.

Some options for how to proceed:
- revert that change, and deal with bad data for now
- refactor the code to accept an alternate method for populating data, configurable without having to hard code the source
- provide CMU instructors with some sort of script that they can run which, independently of Autolab, fetches data from Autolab and mass uploads it to their course, overwriting data that was there previously
- investigate why information from Shibboleth is giving us bad data and adjust appropriately.

/cc @andrewwuan @icanberk

**Comment by icanberk** [comment]
I think we should first do the last item: investigate why information from Shibboleth is giving us bad data and adjust appropriately.


(I fully support this issue)

**Comment by TheodorJ** [comment]
There doesn't seem much description on what "bad data" is, and whether or not sanitizing data is "bad" or not. This issue is also pretty old, and probably hasn't been looked at for a while (and may not even be an issue anymore), so I'm going to close.
