### ISSUE TITLE
Jobs page: "View long list" link broken

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#409]
Normally the jobs page shows a short list of the recently completed jobs, with a link at the bottom that you can click to view the entire list of completed jobs. However, this link no longer does anything.

**Comment by dlbucci** [comment]
When I click it, it goes from showing jobs 45-17 to showing 45-1.  Is this just that Tango was reset recently and there aren't many recent jobs?

**Comment by droh** [comment]
Ah, my mistake. I'll close this.


-- David O'Hallaron
-- Prof of CS and ECE, Carnegie Mellon University
-- GHC 7517, x8-8199
-- http://www.cs.cmu.edu/~droh
