### ISSUE TITLE
Style the public/500.html page like maintenance mode

### ISSUE THREAD

**Issue by jez** [autolab/Autolab#413]
Similar in spirit to #314.

**Comment by jez** [comment]
#413 vs #314: what a coincidence!

**Comment by dlbucci** [comment]
I don't think this is quite like #314.  Apache searches the public folder for a file named 500.html whenever Rails crashes hard enough that our error handler isn't even called.  This means that 500.html has to be a static html page, and I don't think we can rebase it with the application layout.
I agree that the page should be restyled, but how that happens is gonna be different.

**Comment by jez** [comment]
That's what I meant by "spirit". There will probably be some code
duplication involved, but it's unavoidable.

**Comment by dlbucci** [comment]
But then our code climate GPA will go even lower... ah well, just making sure you were aware :)

**Comment by jez** [comment]
Code climate is only checking ruby, isn't it?

**Comment by dlbucci** [comment]
I don't know, all I know is that I ran rubocop, and made it so there was only one error, and code climate took the grade from an A to a C, so that sort of sucked.

**Comment by jez** [comment]
If someone wants to work on this, I can explain what needs to happen pretty quickly. It's a very straightforward fix.

**Comment by remzr7** [comment]
@ymzong the maintenance page doesn't exist under public/ anymore? 

Furthermore, does this issue still apply?

**Comment by devanshk** [comment]
Closed as this doesn't cause any problems, and the maintenance page no longer exists.
