### ISSUE TITLE
AssessmentCategories should probably be an Assessment field

### ISSUE THREAD

**Issue by dlbucci** [autolab/Autolab#42]
It's pretty useless as is.

**Comment by icanberk** [comment]
@dlbucci have you done anything about this? otherwise you can assign it to me.

**Comment by dlbucci** [comment]
No, you can take it, but having thought about it, I think there may be instructor code that determines scores based on AssessmentCategories, so I'm not certain this would be too simple.  At the very least, score computations need to still take category into account.  (SQL GROUP BY might help though)
Also, a fix for #142 may be more important, or at the very least can be done at the same time as this.

**Comment by icanberk** [comment]
Good point. I started working on it, but we need to review all that grading code which seems nontrivial right now.

**Comment by jez** [comment]
Closed by #276
