### ISSUE TITLE
Need to update ruby-version to 2.2.1

### ISSUE THREAD

**Issue by icanb** [autolab/Autolab#440]
There is a problem preventing 2.2.0 from being installed on ubuntu (https://github.com/sstephenson/ruby-build/issues/690#issuecomment-68113987)

**Comment by dlbucci** [comment]
I actually did install ruby 2.2.1 on milkshark, but I think shibboleth stopped working when we switched.

**Comment by TheodorJ** [comment]
Ruby 2.2.2 seems to work for me. I'm gonna close this issue
