### ISSUE TITLE
Incorrect maximum output file size

### ISSUE THREAD

**Issue by mihirpandya** [autolab/Autolab#444]
The maximum output file size field says 4096 bytes for every job's page. This value is incorrect and seems hard coded.

**Comment by dlbucci** [comment]
It's exactly what Tango returns to us, so if it is hardcoded, this issue belongs in the Tango repo.  See here:
https://github.com/autolab/Autolab/blob/master/app/views/jobs/getjob.html.erb#L22

**Comment by mihirpandya** [comment]
Yeah, you're right. For some reason, it's set as the default value here. https://github.com/autolab/Tango/blob/1ac11374c900d8fc0169ab6a83a9f8033791219e/tangoObjects.py#L56
