### ISSUE TITLE
Allow base file option for Moss

### ISSUE THREAD

**Issue by RONNCC** [autolab/Autolab#451]
From http://moss.stanford.edu/general/tips.html

" Moss can be more accurate if a base file is supplied. The -b option to Moss supplies a base file of code that should be ignored if it appears in programs; Moss never considers code that appears in a base file to match any other code. If your results include many unintended matches, then it is best to place all legitimately shared code in a base file (e.g., instructor-supplied code, common libraries, etc.) and resubmit the query to the server. "

Would be very very useful!

**Comment by RONNCC** [comment]
Also allowing the general options for moss to be configured would be useful 

"
#  moss [-l language] [-d] [-b basefile1] ... [-b basefilen] [-m #] [-c "string"] file1 file2 file3 ...
"

**Comment by zyx-billy** [comment]
Fixed in [Autolab2.0](https://github.com/autolab/Autolab/releases/tag/v2.0.2)
