### ISSUE TITLE
Editing course settings appends an extra "(semester)" field to the course name

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#453]
Each time an instructor updates the Course Settings page, Autolab appends an extra "(semester)" field to the course display name. For example, after updating the 213 course settings 4 times, the Display Name for 213 is now:  

15213: Introduction to Computer Systems (f15)(f15)(f15)(f15)(f15)

Can someone make a hot fix for this? It looks really weird.

**Comment by icanberk** [comment]
I fixed this but it's not in production yet.

**Comment by dlbucci** [comment]
#449 We should probably merge develop sometime soon.
