### ISSUE TITLE
Scoreboard Editor

### ISSUE THREAD

**Issue by dlbucci** [autolab/Autolab#461]
Instead of having instructors write JSON strings, we should have a frontend javascript editor that generates the strings.

**Comment by devanshk** [comment]
Looks like a pretty useful feature, and something that's fairly straightforward. Keeping this open!

**Comment by devanshk** [comment]
On second look, we have an example json string `{"scoreboard": [ {"hdr":"Score"}, {"hdr":"Ops", "asc":1} ] }` and the format only takes a few minutes to type up. Closing this off.
