### ISSUE TITLE
Scoreboard banner size needs to be increased and shouldn't DK if it's too long

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#463]
For 213 datalab, I need an html scoreboard banner of the form:

***
This page shows your most recent submission. You may handin as many versions as you like. You will be graded on the last version.

Puzzle key: 1=bitAnd, 2=tmin, 3=negate, 4=allEvenBits, 5=bitCount, 6=logicalShift, 7=isNegative, 8=isGreater, 9=isPower2, 10=firstBits, 11=greatestBitPosition, 12=float_i2f, 13=float_abs
***
Entering this in the scoreboard banner causes a DK:
--- !ruby/exception:Mysql2::Error
message: Data too long for column 'banner' at row 1
server_version: 50541
error_number: 1406
sql_state: '22001'

Two things:
1. The maximum size needs to be bigger.
2. The system shouldn't DK if it's too large. It should display an error message on the "scoreboard settings" page.

**Comment by dlbucci** [comment]
This is fixed in #454
