### ISSUE TITLE
Scoreboard properties aren't being exported to the yml file

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#465]
Scoreboard properties aren't being exported to the yml file. This should happen when
1) A scoreboard property is changed and 2) the assessment is explicitly exported using the "Export Assessment" link.

**Comment by droh** [comment]
Dan: 
If you need an example of a configured scoreboard whose properties are not exported, see the datalab for 15213-m15. 
Best, Dave

**Comment by dlbucci** [comment]
Fixed by #454
