### ISSUE TITLE
Autograding and Scoreboard Settings pages have a dead link in the title.

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#467]
The Autograding Settings page has a dead link in the title. For example "Admin Autograding for Datalab",
the link for Datalab is dead. We should remove the reference to Datalab (because it's redundant with the breadcrumbs), and change the title to simply "Autograding Settings".

**Comment by dlbucci** [comment]
This is fixed in the scoreboard PR.

**Comment by dlbucci** [comment]
Fixed by #454
