### ISSUE TITLE
"No user" page should link to instructions on creating an instructor account

### ISSUE THREAD

**Issue by jez** [autolab/Autolab#473]
Right after installing Autolab, creating and verifying an account, I see the following page:

![screenshot 2015-04-19 06 57 29](https://cloud.githubusercontent.com/assets/5544532/7219184/83de39d6-e661-11e4-881d-564e0d9c6be4.png)

I think that the majority of people seeing this page are going to be people setting up new Autolab instances vs students who haven't been added to any classes, so we should add a note to this page about how to go about creating an instructor account if the user is really an instructor.

Also, the "Interested in Autolab" snippet links to greatwhite.ics.cs.cmu.edu. When we change this page, we should remember to switch that link as well.

**Comment by dlbucci** [comment]
Also, I think we actually redirect people to a different page when they aren't in any courses.  We should merge this page with the current courses page so that they at least get a link to the old autolab.

**Comment by jez** [comment]
I found out that the documentation for this was the next step in the deployment instructions (I just didn't read ahead), so I'm closing this.

Also, in the `feature/dockerized-autolab` app, I created a rake task to automate the process of promoting a new user to admin level, so it's really easy now.
