### ISSUE TITLE
Scoreboard colspec too short and then DKs

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#474]
I'm trying to enter the following colspec for the 15213-m15 tshab scoreboard:
{"scoreboard": [ {"hdr":"Score"}, {"hdr":"0"}, {"hdr":"1"}, {"hdr":"2"}, {"hdr":"3"}, {"hdr":"4"}, {"hdr":"5"}, {"hdr":"6"}, {"hdr":"7"}, {"hdr":"8"}, {"hdr":"9"}, {"hdr":"10"}, {"hdr":"11"}, {"hdr":"12"}, {"hdr":"13"}, {"hdr":"14"}, {"hdr":"15"}, {"hdr":"16"}, {"hdr":"17"}, {"hdr":"18"}, {"hdr":"19"}, {"hdr":"20"}, {"hdr":"21"}, {"hdr":"22"}, {"hdr":"23"}, {"hdr":"24"} ]}

Autolab DKs because the colspec is too long. We need to increase the maximum colspec size, and then not DK if it's too long, giving the user a reasonable message instead.

**Comment by dlbucci** [comment]
This is fixed in the scoreboard PR.

**Comment by dlbucci** [comment]
Fixed by #454
