### ISSUE TITLE
Latest Submission not working

### ISSUE THREAD

**Issue by ymzong** [autolab/Autolab#492]
For *plug in a course* *plug in an assessment*, `asmt.submissions` returns a list of submissions. However, `asmt.submissions.latest` returns ` #<ActiveRecord::AssociationRelation []>`. 

This issue require an immediate fix because it might affect grade calculation, etc.

**Comment by dlbucci** [comment]
Where is this failing?  I think I fixed this in my bug fixes branch

**Comment by ymzong** [comment]
It happens when I'm trying to fix MOSS. In `courses_controller.rb:633`, the for-loop runs on an empty list, when `asmt.submissions` is not empty.

**Comment by dlbucci** [comment]
This was corrected in production last night and is corrected in #490.

The issue was that the aud.update_latest_submission callback was not correctly updating aud.latest_submission when a submission was created.

This shouldn't be an issue going forward, but we should run a rake task in production that makes sure that anyone who submitted something between ~6pm yesterday and ~2am today gets their AUD updated properly, or there will be score issues.

**Comment by ymzong** [comment]
I already checked-out master, and used "create submission" to create submissions for students, however `asmt.submissions.latest` is still empty. I will give it a double-check now.

**Comment by dlbucci** [comment]
Try changing a statement in submissions.rb: `delegate :update_latest_submission, to: :aud` change this to a function:
```
def update_latest_submission
  aud.update_latest_submission
end
```

**Comment by ymzong** [comment]
Nope, still empty for me -- could you verify?

**Comment by ymzong** [comment]
Oh wait nvm, I didn't check out the most recent master, my b my b

**Comment by dlbucci** [comment]
Also, you'll need someway to trigger an update so that the AUDs are pointing to the correct latest_submission, otherwise the relation will continue to be empty, because it's calculated with a join on assessment_user_data.

**Comment by ymzong** [comment]
Well, I just created some more submissions, and they are not showing up in `latest`. Anything else I need to do?

**Comment by dlbucci** [comment]
Did you create them with or without the delegate thing?  Where are you testing these changes?

**Comment by ymzong** [comment]
I'm testing on develop, with delegate. it's essentially `HEAD` of master with my fixes.

**Comment by dlbucci** [comment]
Try it without delegate?

**Comment by ymzong** [comment]
Nope, still empty.

**Comment by dlbucci** [comment]
What SQL query is being generated by that statement?

**Comment by ymzong** [comment]
Which statement, and how can I see?

**Comment by dlbucci** [comment]
Let's take this to Slack.

**Comment by dlbucci** [comment]
Do we think this is still an issue?

**Comment by ymzong** [comment]
Sorry -- closed it!
