### ISSUE TITLE
Option to delete on "Manage users" view

### ISSUE THREAD

**Issue by jez** [autolab/Autolab#495]
![screenshot 2015-04-29 19 56 43](https://cloud.githubusercontent.com/assets/5544532/7404773/7f503542-eeb6-11e4-8a5a-8d09481ec2cb.png)

We should add a button (or checkbox) that lets admins delete (or mass delete) users from the "Manage users" screen. Right now, you have to click on the user, then click Edit Information, **then** finally you have a button that lets you delete a user.

**Comment by dlbucci** [comment]
Conversely, maybe it's good that it's hard to delete users, seeing as that's not something that should accidentally happen.

**Comment by jez** [comment]
Sure, but it's also not obvious that you should have to edit a user's information for a delete button to show up. Maybe we move the delete button forward one view in the chain: you still have to click on the user, but you don't have to click all the way to edit information.

**Comment by damianhxy** [comment]
Suggestion:

(Note: confirmation message is currently broken, the `confirm` has to be wrapped by a `data`)

```patch
diff --git a/app/views/users/edit.html.erb b/app/views/users/edit.html.erb
index 8c99a716..31855b33 100755
--- a/app/views/users/edit.html.erb
+++ b/app/views/users/edit.html.erb
@@ -23,9 +23,3 @@
 
   <%= f.submit 'Save Changes', { :class=>"btn primary"} %>
 <% end %>
-
-<% if current_user.administrator? %>
-<br> <br><hr><br>
-<h3> Admin Only</h3>
-  <%= link_to raw('<span class="btn">Delete User</span>'), user_path(@user), method: :delete, confirm: "Are you sure!?" %>
-<% end %> 
diff --git a/app/views/users/show.html.erb b/app/views/users/show.html.erb
index f07e9a64..0c4bc5ee 100644
--- a/app/views/users/show.html.erb
+++ b/app/views/users/show.html.erb
@@ -20,7 +20,10 @@
     <% end %>
   </li>
 </ul>
-<%= link_to raw('<span class="btn primary">Edit Information</span>'), edit_user_path(@user) %><br>
+<%= link_to raw('<span class="btn primary">Edit Information</span>'), edit_user_path(@user) %>
+<% if current_user.administrator? %>
+  <%= link_to raw('<span class="btn">Delete User</span>'), user_path(@user), method: :delete, data: {confirm: "Are you sure?"} %><br>
+<% end %>
 <% if @user == current_user %>
   <hr>
   <h4>Private Settings</h4>
```
