### ISSUE TITLE
Scoreboard and Autograding section heading have changed in .yml file

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#500]
The scoreboard and autograding headings in the .yml file have changed from scoreboard_setup: (autograding_setup:) to scoreboard: (autograder:). 

Next semester, if instructors try to install an assessment using their .yml files from last Fall or Spring, the install will fail with a non-descriptive Donkey Kong. So how are instructors supposed to import their courses from previous semesters, especially the ones from Fall 2014, which aren't even available on the current production system

**Comment by dlbucci** [comment]
No, I made sure to add backwards compatibility so that yaml files with autograding_setup and scoreboard_setup (and a few other properties that we've changed) will still work.

**Comment by droh** [comment]
...But when I tested it just now using an old .yml file, the production system DK'd. Has this backwards compatibility not yet been pulled to production?

**Comment by dlbucci** [comment]
That's a different issue that I'll try to fix now.
