### ISSUE TITLE
Saving scoreboard and autograding settings does *not* update .yml file

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#501]
Explicitly saving the autograding and scoreboard settings does *not* update the .yml file as it should. To reproduce, Click "Scoreboard settings", make a change, then click "Save Settings".

The only way to update the .yml file right now is to do an explicit export of the assessment, or to click the "Save" button on the main "Edit Assessment" page.

**Comment by dlbucci** [comment]
This was fixed in #498, which has been merged.  I just pulled and tested, and it works, but note that deleting an autograder or scoreboard will not be immediately reflected in the yaml file.
