### ISSUE TITLE
Some menu items don't follow sentence case convention

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#503]
Autolab uses sentence case (first word capitiized, following words lower case) for menu items in the "Admin options", "Admin options (CA)", and "Options" lists. However, there are some list items that don't following this convention (e.g., Autograder Settings, Scoreboard Settings, Download Section Submissions, View Scoreboard), which creates a dissonance for the reader. 

All list items need to be changed to follow sentence case.

**Comment by nayak16** [comment]
Merged 26ba3a1667f8096aa467fc72c3e13836ff9cc229
