### ISSUE TITLE
Can't enter scoreboard colspecs

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#504]
Go to "Scoreboard settings", enter a JSON colspec, then click "Save Settings". It returns to the "Scoreboard settings" page and erases the colspec you just typed in without saving it. 

For example, see tshlab in upcoming course 15213-m15.

**Comment by dlbucci** [comment]
Seems to work for me.  Are you sure your colspec is well-formed?  We could stand to have a more useful error message though.
