### ISSUE TITLE
Many pages are missing the Facebook icon in the lower right hand corner

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#505]
Some pages have both a Github and Facebook icon in the lower right-hand corner. Many others are missing the Facebook icon.

**Comment by dlbucci** [comment]
What pages are missing the facebook icon?  I'm pretty sure this is just the facebook icon taking time to load, and not anything we're doing.  It's been on every page for me.

**Comment by droh** [comment]
OK, I see it now. I guess you're right, there's some large delay at Facebook.
