### ISSUE TITLE
Sorting by andrew id

### ISSUE THREAD

**Issue by RONNCC** [autolab/Autolab#512]
On the view grades page you can click the columns to sort by name, section, lecture, grades.

It would be useful to be able to sort by andrew id since when grading many of the times the work is alphabetized by andrewid.

**Comment by jez** [comment]
I believe you can sort by email.

We're moving towards removing all CMU-specific fields from Autolab so that
it can be of maximum utility for other schools as well. Because of this, we
no longer store the Andrew IDs of students.

**Comment by RONNCC** [comment]
how? Clicking on the email & name column only sorts by name I believe

**Comment by jez** [comment]
hmm I'll have to look at it then. I don't remember.

**Comment by dlbucci** [comment]
@RONNCC is correct, you can only sort by names since we merged the name and email columns.

**Comment by jez** [comment]
Oh, I'm assuming in the HTML, but not in the database?

**Comment by dlbucci** [comment]
What? You can sort by emails in the DB, but I don't know how useful that is when you'd need to reload the gradesheet to have that effect.

**Comment by jez** [comment]
Never mind. The way you said it I couldn't tell f you meant that we had
joined the columns in the actual database or just displayed them as one
column in the HTML.

**Comment by zyx-billy** [comment]
This was accidentally fixed by #643.
Now the 'Name & Email' column sorts according to email.
