### ISSUE TITLE
Tweak score automatically visible

### ISSUE THREAD

**Issue by sehgalrohan** [autolab/Autolab#513]
If there is no problem created for the assessment the tweak score is visible by default.

**Comment by dlbucci** [comment]
What page does this occur on?

**Comment by sehgalrohan** [comment]
If the lab does not have a problem created, and the TA adds a value to the tweak column on the "Grade all Submissions" page, the tweak is shown to the student by default as "Total Score" in his/her "View Submissions" page.

**Comment by sehgalrohan** [comment]
This is happening right now with a different score, the "Grade all submissions" pages says the scores are not released, but the scoreboard shows them..

**Comment by sehgalrohan** [comment]
^created a new issue for the previous comment, as its a different case (and a more insidious one I think).

**Comment by victorhuangwq** [comment]
Closing stale issue. Do open a new issue if problem still persist
