### ISSUE TITLE
Please make the autograder feedback view for CAs and Admins larger!

### ISSUE THREAD

**Issue by vulq** [autolab/Autolab#523]
Hi,

It would be super useful if we could have a full-screen autograder report view like students do (in a new page).  It becomes really painful to scroll through everything in the tiny box, and you can only expand it so much.

Thanks!

![screen shot 2015-06-11 at 8 20 19 pm](https://cloud.githubusercontent.com/assets/10230153/8121305/fa05dc8c-1077-11e5-8c2c-cdbac7ced2dd.png)

**Comment by jez** [comment]
Instructors can see this already, though it may be a bit of a roundabout workflow (on that note, we've received many suggestions to rework the wording and organization of the instructor options and views).

To view the full feedback (as if you were the student), from "Grade submissions" (the view depicted in your screenshot above),
- click the students' email at the far left or right of the row
- click the `.tgz` file at the top of the popup (for the most recent submission) or click "(more...)" for older submissions
- click on any of the individual scores to see the full autograder feedback

Let me know if this doesn't work for you or if you have any other suggestions.

**Comment by vulq** [comment]
Thanks! I feel like this could be made a little more clear though.  Perhaps have a link when you click on an individual score in "Grade Submissions" to bring you to the full report of the most recent submission?

**Comment by devanshk** [comment]
Merged into #695
