### ISSUE TITLE
Refactor the attachments#new view to use our FormBuilder

### ISSUE THREAD

**Issue by jez** [autolab/Autolab#524]
The form in `app/views/attachments/new.html.erb` should use the new FormBuilder (`FormBuilderWithDateTimePicker`) that we've been cleaning up. It should be a pretty straightforward change, and you can see an example of how it works on one of my previous PRs:

- #401 Add datepickers to the Announcements forms, specifically
  - This line <https://github.com/autolab/Autolab/pull/401/files#diff-b76ac1fddc1583275323589933fc65d9R4> and
  - This file <https://github.com/autolab/Autolab/pull/401/files#diff-7b8be66719056f3df229b112add26a48R1>

Right now, it looks pretty ugly:

![screenshot 2015-06-14 13 40 13](https://cloud.githubusercontent.com/assets/5544532/8150353/f9bad028-129a-11e5-96fe-a861ba1c195c.png)

in comparison with our other forms:

![screenshot 2015-06-14 13 41 15](https://cloud.githubusercontent.com/assets/5544532/8150355/10cdc888-129b-11e5-88c3-9fc3344c3d79.png)

**Comment by remzr7** [comment]
@nayak16 shouldn't this be closed? The form is using FormBuilderWithDateTimePicker

**Comment by ymzong** [comment]
@remzr7 Yup that's right -- we forgot to close the issue after the PR was merged. Thanks for the heads up! :smiley_cat:
