### ISSUE TITLE
Polish Admin SVN forms

### ISSUE THREAD

**Issue by jez** [autolab/Autolab#526]
The Admin SVN page could use a little polish:

![screenshot 2015-06-14 14 51 24](https://cloud.githubusercontent.com/assets/5544532/8150610/edabc396-12a4-11e5-9be3-bd802eb157fa.png)

- the `Create` buttons are unstyled
- we could probably use some CSS magic to make the text fields look better than they do now

**Comment by remzr7** [comment]
Closed because feature is irrelevant
