### ISSUE TITLE
Sign up page could use some flavor text

### ISSUE THREAD

**Issue by jez** [autolab/Autolab#527]
This page is pretty uninviting:

![screenshot 2015-06-14 17 08 43](https://cloud.githubusercontent.com/assets/5544532/8151077/15e67fa0-12b8-11e5-84ae-c8ed2ae76680.png)

We should add some flavor text to add a little personality to this page.

Additionally, we should use the FormBuilder to style this form.

**Comment by TheodorJ** [comment]
We made the sign-up page look better in Autolab 2.0. Closing
