### ISSUE TITLE
Refactor Submissions to remove special_type code

### ISSUE THREAD

**Issue by jez** [autolab/Autolab#529]
re: Statistics not showing up?

> On Jun 28, 2015, Ilter Canberk wrote:
> 
> > I just debugged this, the problem was with the following line in `grading.rb`:
> > 
> > ```
> > next unless submission.special_type == Submission::NORMAL
> > ```
> > 
> > The "special_type" of the submissions is not NORMAL for any of the
> > submissions. I tried to figure out why this might be happening but couldn't
> > find any explanation about what "special_type" is or when we're setting
> > special type to anything other than NORMAL. Anyone know anything about this?
> > 
> > Commented out the line as a temporary solution.

On Jun 28, 2015, Daniel Bucci wrote:

> I believe that we used to have special_type (no grade/excused) specific to
> submissions, but this would be a pain for instructors if the student
> resubmitted, because they would need to respecify the special_type for the new
> submission.  There's a migration called
> `transfer_submission_special_type_to_aud_grade_type` from 2013, and AUD's
> handle this currently, so I believe we can remove the special_type code from
> our codebase.

**Comment by remzr7** [comment]
@ymzong I found this 

`      grouping[group].each do |submission|
        next unless submission.course_user_datum.student?
        # TODO(jezimmer): Find a more permanent fix (see #529)
        #next unless submission.special_type == Submission::NORMAL

        submission.scores.each do |score|
          problem_scores[score.problem_id] << score.score
        end

        problem_scores[:total] << submission.final_score(@cud)
      end`

in grading.rb. I'm not sure how big of an issue this is.

**Comment by victorhuangwq** [comment]
Closing stale issue. Do create a new issue if still relevant
