### ISSUE TITLE
Need breadcrumbs on "Manage Autolab" page

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#532]
The "Manage Autolab" page for administrators needs breadcrumbs at the top of the page.

**Comment by dlbucci** [comment]
What breadcrumbs does it need, specifically?  It seems like the only place to go is back to the "Manage Autolab" or the courses page, which you can reach by clicking the Autolab logo.

**Comment by droh** [comment]
Good point. I'll close that issue.

-- David O'Hallaron
-- Prof of CS and ECE, Carnegie Mellon University
-- GHC 7517, x8-8199
-- http://www.cs.cmu.edu/~droh
