### ISSUE TITLE
Tango open request fails with spaces in course name

### ISSUE THREAD

**Issue by GjjvdBurg** [autolab/Autolab#550]
Hi there,

When uploading an assignment we encountered an error in line 355 of app/controllers/assessment/autograde.rb. Here's some context:

````Ruby
    # send the tango open request
    begin
      existing_files = TangoClient.open("#{course.name}-#{assessment.name}")
    rescue TangoClient::TangoException => e
      flash[:error] = "Error with open request on Tango: #{e.message}"
      return -1
    end
````

After logging the error we saw that the URI is bad, the error message is:

````
Error with open request on Tango: Unexpected error with Tango (bad URI(is not URI?): /open/ourkey/Test 5-sumdivisors/)
````

When we created a new course without spaces in the name the problem did not occur, so that seems to be the issue. It would be good to either warn users about this, or filter out the spaces before opening the Tango request. Thanks!

**Comment by jez** [comment]
Is "Test 5" the name of the course you entered when creating a course from this page?

![](https://cloud.githubusercontent.com/assets/5544532/8787355/826463c6-2ee8-11e5-9c13-3ebc4f532381.png)

It's very unclear; the name is actually supposed to be a url-able slug. Unfortunately the help-text hasn't been added to this screen, but it shows up in the Course settings page:

> The course ID used in URLs and DB keys. This field must be unique and URL-able. Typically includes the course number and semester. Examples: 15213-f12, 15110-s11

**Comment by GjjvdBurg** [comment]
It is indeed the name of the course on that page. Thanks for clearing it up, I'll keep it in mind for future reference. Perhaps it would be good to add it to the page for other users.

**Comment by jez** [comment]
Will do. Merging this into #538.

**Comment by dlbucci** [comment]
As an aside, if 'url-ability' is the only reason for this restriction on course names, we might be able to just URI-encode/decode course names, right?
