### ISSUE TITLE
Persistent Announcements ignore start and end dates.

### ISSUE THREAD

**Issue by jozefg** [autolab/Autolab#558]
Autolab is currently warning (instructors only?) of a shutdown on August 12th. Is the date wrong or is this just a wrong warning?

Cheers,
Danny

**Comment by dlbucci** [comment]
This warning is CMU-specific, so it sort of doesn't belong in the open-source repo, but it has uncovered a bug with announcement displays. (Also, the CMU Autolab maintenance is done now.)

**Comment by icanberk** [comment]
Hi @jozefg, There was some maintenance work scheduled for August 12th. The announcement should've persisted from that. Please disregard.
