### ISSUE TITLE
Permission issues when following documentation

### ISSUE THREAD

**Issue by edmcman** [autolab/Autolab#560]
If I follow the directions at https://github.com/autolab/Autolab/wiki/Deploying-Autolab-with-Docker

When I create a new course I get the following error:

```
--- !ruby/exception:Errno::EACCES
message: Permission denied @ dir_s_mkdir - /home/app/webapp/courses/123
```

If I manually correct the problem, I then get an error about /home/app/webapp/assessmentConfig.  If I `chown -Rv app:app /home/app/webapp`, the problem goes away.

**Comment by jez** [comment]
Yeah sorry, that's a known issue. I have a diff for it in my testing
environment but I haven't had time to submit it. Thanks for the report!
It'll be fixed soon.
