### ISSUE TITLE
Problems with running develop branch in Docker

### ISSUE THREAD

**Issue by edmcman** [autolab/Autolab#561]
If I follow the directions in https://github.com/autolab/Autolab/wiki/Deploying-Autolab-with-Docker#10-make-required-volume-directories with the develop branch, I encounter the permissions problem as described in #560.  If I correct them using the commands in that issue, the branch feature/dockerized-autolab allows me to create a new course.  If I use the develop branch, however, I'm taken to a 500 error page without any meaningful information.  There is also little information in the log, other than the error seems to happen while processing the show action of CourseController.

I'm not really sure how to debug further.  Any suggestions?

**Comment by jez** [comment]
Out of curiosity, does the page look like this:

> # 500 – Internal error
>
> Oops! Autolab seems to have done something wrong. We have been notified about
> this and will look into it. If you would like to file a Bug Report, you may
> email us at autolab-dev@andrew.cmu.edu or open an issue in our issue tracker
> on GitHub.

If so, then it's almost certainly related to #563, which has been merged into develop but will not affect the `feature/dockerized-autolab` branch.

**Comment by edmcman** [comment]
Yup, that is what the error looks like.

**Comment by jez** [comment]
This should be fixed now on `master` and `develop`. Let us know if the problem persists.
