### ISSUE TITLE
Admin access is broken

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#565]
As an admin, if I visit a course such as 15112-f15 where I'm not a user, I see a new (to me) page that says "Request to Join". If I click that button, the system DK's with a 404 not found.

If I visit a course where I am already a user, such as 15-317Q, I don't seem to have full instructor privileges. For example, I can install an assessment, but when I visit a particular assessment, I only see the student options.

**Comment by jez** [comment]
This is a regression that was likely introduced by the public courses pull request.

@icanberk: Can we please back out this change?

**Comment by dlbucci** [comment]
For whatever it's worth, I'd support that decision.

**Comment by jez** [comment]
This should be fixed now. Please re-open the issue if the problem persists.
