### ISSUE TITLE
Jobs Page shows jobs for other courses

### ISSUE THREAD

**Issue by dlbucci** [autolab/Autolab#57]
From an email from David Winters:
Iliano Cervesato sent the following, asking about a page showing recently-completed jobs and asking if this is expected.  His exact words:

> I can now see my course page.  One thing: clicking under "Jobs", I see
> the attached screen shot.  Is this expected?

**Comment by droh** [comment]
Hi Iliano,
We've added that to our bug list.

BTW, you can send bug reports and feature requests directly to the
developers at autolab-dev@andrew.cmu.edu.

Thanks,
Dave


-- David O'Hallaron
-- Prof of CS and ECE, Carnegie Mellon University
-- GHC 7517, x8-8199
-- http://www.cs.cmu.edu/~droh
