### ISSUE TITLE
Grade sheet improvements (Feedback Box & Tweak Workflow)

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#570]
1. The feed box that pops up when you click an autograded score is annoying small and can't moved. It should be larger and should free standing and should be able to be moved and resized. 

2. Clicking the tweak field currently takes you to a separate page, which is really inconvenient because there's no way to navigate back to the gradesheet. It should be a popup windown,  exactly like any other feedback box.

**Comment by jez** [comment]
I can't agree more. I think the gradesheet views are our most painful flows right now. I'm going to primarily focus on user experience improvements like these this semester.

**Comment by devanshk** [comment]
Merged into #695
