### ISSUE TITLE
Very inconsistent behaviour when setting assessment due time

### ISSUE THREAD

**Issue by GjjvdBurg** [autolab/Autolab#576]
Hey guys,

I'm experiencing some very inconsistent behaviour when setting the assessment times. I'm not an expert in Ruby so I haven't been able to find the relevant code which could be responsible, but I think that the locale time may also have an influence.

Let's say I have an assessment which currently has a due time of 7pm, in the main assessment window:

![screenshot - 290815 - 19 58 21](https://cloud.githubusercontent.com/assets/3286696/9563607/1e83764c-4e89-11e5-9239-806a5f8b881c.png)

Now, if I check the "Edit Assessment" Page, the due time I see there is 5pm:

![screenshot - 290815 - 19 58 45](https://cloud.githubusercontent.com/assets/3286696/9563611/3673c676-4e89-11e5-838d-8777de2d2ea5.png)

This is a 2 hour difference which could be caused by the difference with UTC, which is currently 2 hours behind my local time. If I try to set the due time at 9am as desired using this screen:

![screenshot - 290815 - 19 59 21](https://cloud.githubusercontent.com/assets/3286696/9563620/7bdc5ca0-4e89-11e5-82b8-5a8934031f70.png)

As soon as I press "Save", the due time changes to 1pm:

![screenshot - 290815 - 20 00 37](https://cloud.githubusercontent.com/assets/3286696/9563622/8e60a782-4e89-11e5-9c1a-9bb1790598fa.png)

And back in the main assessment window the time is shown as 3pm:

![screenshot - 290815 - 20 00 58](https://cloud.githubusercontent.com/assets/3286696/9563623/99fd537e-4e89-11e5-9787-e40669a85325.png)

So, in order to have a displayed due time of 9am, I have to set the time to 3am in the configuration, and hope that the system will use the displayed due time instead of the one that will show up in the configuration after pressing Save (which is 7am).

Any help is appreciated since we'll start using Autolab here on Monday :)

**Comment by dlbucci** [comment]
We've never had Autolab deployed in more than one time zone, so I wouldn't be surprised if it has some timezone inconsistency issues.  I can try to take a look at this sometime this weekend, but the relevant code should be in `app/controllers/assessments_controller.rb` and `app/models/assessment.rb`.

**Comment by GjjvdBurg** [comment]
Thanks for the quick response, would be great if you could take a look at it. If you need some debugging output or something let me know.

**Comment by dlbucci** [comment]
Please try setting `config.time_zone` to your current time zone (try `rake time:zones:all` for a list of timezones) in your `config/application.rb`.

Here's what I think is occurring: our datetime pickers do not specify a timezone when the dates are sent to the server, so Rails assumes they are in the `config.time_zone`.  But when those dates are sent to the client, the javascript date time pickers correctly parse the UTC time into the user's current timezone, resulting in skew if the two timezones are different.

Really, we should be adding a timezone to all time strings, but for now, I think this fix will work.

**Comment by GjjvdBurg** [comment]
Thanks for the help, I think this fixed half of the problem. Now, if I set the time to 9am in the Edit assessment window and press save, the time in that window changes to 7am. However, when I go back to the main assessment view, it does show up as 9am.

Also, every time I click save, all the times are shifted backwards by 2 hours (time difference with UTC). This is probably due to javascript converting between UTC and my local time. For now, my main concern is whether the time I see in the main assessment window is the due time Autolab will maintain, or whether it's the time that shows in the Edit Assessment window.

Thanks for the effort so far, we're excited to start using Autolab here.

**Comment by dlbucci** [comment]
I think that if it shifts by two hours every time you save, the actual due date will be the time displayed + 2 hours.  So if you set the due time to 12am, and then 10am is what is displayed, the due time will stay 12am as long as you don't save the the assessment from the edit/handin page.

**Comment by GjjvdBurg** [comment]
Great, thanks a lot, that's what I was hoping for. This way I can at least work around it in a reliable way :)

**Comment by dlbucci** [comment]
@GjjvdBurg I think I was actually incorrect earlier.  I think the date that is displayed is the actual due date for users in your time zone. (As in, if 10pm is displayed, 10pm is when it's due).  We use moment.js to display dates, and I believe it is currently properly converting a datetime string into the time in the browser's timezone, so the fix would be to set datetimes to 2 hours later (or earlier? whichever works) when filling out a form, or wait until #576 gets merged.

**Comment by GjjvdBurg** [comment]
@dlbucci Thanks for the fix, this works for me. Pressing Save in the edit/handin window doesn't change the times, and the time in that window corresponds to the time in the main assessment window. All like it's supposed to, so #577 fixes the problem as far as I can see. Thanks again!

**Comment by jez** [comment]
Closed via #577
