### ISSUE TITLE
Dockerfile does not set permissions for tmp/cache

### ISSUE THREAD

**Issue by edmcman** [autolab/Autolab#579]
I receive the following error when visiting most pages:

`--- !ruby/exception:Errno::EACCES
message: Permission denied @ dir_s_mkdir - /home/app/webapp/tmp/cache/206`

**Comment by GjjvdBurg** [comment]
I had this issue too, a temporary solution is to go into the docker container using:

    docker exec -i -t autolabprod_web_1 bash

and manually do:

    chown -R app:app /home/app/webapp/tmp

There's probably a way to fix it through the Dockerfile though.

**Comment by damianhxy** [comment]
Closing as stale / can't repro

This might have been fixed in #1277 -- in any case, nightly has the correct permissions on `tmp/cache`
<img width="433" alt="Screenshot 2023-06-03 at 23 02 13" src="https://github.com/autolab/Autolab/assets/9074856/4f17d749-069a-4227-b7f0-c858549d620e">
