### ISSUE TITLE
Edit Course should use a Date Picker.

### ISSUE THREAD

**Issue by dlbucci** [autolab/Autolab#58]
VS the old dropdown menus it currently uses.

**Comment by robsimmons** [comment]
I currently see just a text field where I can enter data of the form "2015-01-12T22:00:00"

That's actually great for me - I can cut and paste! It would be further improved in its current form by a little bit of text above the four fields that said: "The current time is 2015-01-12T21:20:16" or whatever. 

But it may not be webby enough or whatever. If so, my life would be improved by whatever selector having a "Now" button that fills in whatever time now is automatically.

**Comment by Z1MM32M4N** [comment]
Merging into #181
