### ISSUE TITLE
Autolab allows duplicate user names

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#581]
I encountered an odd situation where a student with the identical Andrew email address was listed on the roster twice.

**Comment by TheodorJ** [comment]
Currently, importing a roster will fail if there's a duplicate email address. Let's catch any duplicates and present them to the user, who can then cherry-pick which of the duplicates should be allowed. Duplicate entries in the roster can still happen, but at least they won't cause the roster import to fail and leave the instructor do fix the problem. I'm gonna close this issue and open a new one with the new suggested fix.
