### ISSUE TITLE
extract_tar_for_moss breaks later handins

### ISSUE THREAD

**Issue by cg2v** [autolab/Autolab#583]
extract_tar_for_moss chdir's to the temporary directory (even though I don't think it needs to - destination files are built up as absolute paths by File.join), which breaks any later uses of relative paths, such as autograding handins

Edit: I guess this only happens when AUTOCONFIG_COURSE_DIR is a relative path, so maybe it's not a big deal. the chdir should still be removed if it's not needed

**Comment by cg2v** [comment]
Hmm. maybe the bug is that AUTOCONFIG_COURSE_DIR exists at all. It's only used in the autograde subcontroller. Everywhere else uses File.join(Rails.root, "courses", ,,,)

**Comment by jez** [comment]
Fixed in #585
