### ISSUE TITLE
Robustness of yml parsing of assessments

### ISSUE THREAD

**Issue by GjjvdBurg** [autolab/Autolab#584]
Hi there,

We prefer to upload the assessments from a tarfile. The assessment's yaml file is edited by hand and can occasionally contain a typo, which leads to  "Psych::SyntaxError in assessments#importAsmtFromTar". This by itself is not a problem, it's just that now the assessment is sort of half loaded, and it can't be deleted easily from Autolab because the assessment view can't be opened:

![image](https://cloud.githubusercontent.com/assets/3286696/9821272/8e9d2d44-58b9-11e5-821e-0593a911c67a.png)

It would therefore be better if the assessment tarfile is simply refused if an error occurs in the yaml parser. Also, if there is a way to remove the assessment that's stuck now I'd be very interested :)

Thanks in advance!

**Comment by dlbucci** [comment]
If you append `/edit` to the assessment's url, you should reach an edit page that will let you delete the assessment, and yes, we should have more transactional assessment creation, but honestly, that whole codepath is a bit of a mess right now...

Additionally, it looks like the error here may be that the module's name in the assessment.rb file does not match the camelized version of the course's name.  Double check the `assessmentConfig` folder and see what the name of the loaded module is.

**Comment by GjjvdBurg** [comment]
Thanks for the help, appending `/edit` indeed made it possible to remove the assessment. I'll check the `assessmentConfig` folder to check the module name too.

**Comment by remzr7** [comment]
Issue seems resolved
