### ISSUE TITLE
Broken admin access

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#586]
If an admin (like me) visits a course where I don't have an explicit instructor account, I'm unable to access  any of the instructor functionality. I see the student view, with the exception of "Install assessments" on the course home page. At the top of the page I see the "Manage Autolab" button, but not the "Manage course" button.

Can someone jump on this right away? It's affecting our ability to support instructors when they have questions.

**Comment by dlbucci** [comment]
https://github.com/autolab/Autolab/blob/master/app/models/course_user_datum.rb#L193

Based on that line, I think all admins start out as instructors, but there's nothing stopping a course instructor from demoting a CUD to a student (which is probably how it should be if an admin is a student).  If this is about a specific course, can you check with the instructor to see if they didn't demote you manually?

**Comment by droh** [comment]
I don't think so. I was seeing some instructor functionality (install
assessment) but not others (manage course).

On Saturday, September 12, 2015, Daniel Bucci <notifications@github.com>
wrote:

>
> https://github.com/autolab/Autolab/blob/master/app/models/course_user_datum.rb#L193
>
> Based on that line, I think all admins start out as instructors, but
> there's nothing stopping a course instructor from demoting a CUD to a
> student (which is probably how it should be if an admin is a student). If
> this is about a specific course, can you check with the instructor to see
> if they didn't demote you manually?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autolab/Autolab/issues/586#issuecomment-139809792>.
>


-- 
-- David O'Hallaron
-- Prof of CS and ECE, Carnegie Mellon University
-- GHC 7517, x8-8199
-- http://www.cs.cmu.edu/~droh

**Comment by droh** [comment]
This seems to have fixed and is no longer an issue.
