### ISSUE TITLE
The "dropped" attribute is sticky

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#588]
If a student ever gets marked as dropped, then that attribute persists, even if the student is subsequently listed in a roster file that an instructor imports.

**Comment by remzr7** [comment]
@droh Could you shed more light on this please?

**Comment by ymzong** [comment]
I'll try to explain the situation. For courses with volatile rosters, instructors manage their Autolab roster by pulling a roster from SIO and upload on Autolab. The roster includes a "dropped" bit, so when an instructor uploads new roster, the newly dropped students are marked as so.

If for some reason a student decides to return to the class, the "dropped" bit becomes false again, and when an instructor uploads that roster, the student's dropped status should be removed. _But it's not._

Does it make sense @remzr7?

**Comment by remzr7** [comment]
@ymzong alright got it! Thanks!

**Comment by TheodorJ** [comment]
Whenever I try to replicate this, I get an error saying we can't have duplicate addresses in the course roster. I already created an issue for this (#906), so I'll close this one.
