### ISSUE TITLE
Allow option for assigning score as max(scores of all submissions)

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#589]
We often encounter some jitter on assignments like malloclab that measure running time. One way to counteract this would be to allow an option where the score assigned to a particular submission would be max(scores of all submissions).

**Comment by victorhuangwq** [comment]
May I ask if this issue is still present in the latest version of autolab? If so could you further describe this issue?

**Comment by damianhxy** [comment]
This seems to still be an issue, it appears to only be possible to [override raw score calculations](https://docs.autolabproject.com/instructors/#overriding-raw-score-calculations), but not specifically take the max score over all submissions.

This will likely require significant refactoring of code though.

**Comment by damianhxy** [comment]
Fixed with the addition of the `modifySubmissionScores` hook
