### ISSUE TITLE
Assessment Editing Suggestions

### ISSUE THREAD

**Issue by dlbucci** [autolab/Autolab#59]
Taken from an email from David Winters:

- Edit assessment:
  - Under "Basic", it shows again the "Module Used" but has of the selection made under "Install assessment"
  - Clicking a different tab does not seem to save changes--that's going to confuse a lot of people.
  - Under "Handin", the textual dates are better than the old dropdown menus, but there may be an opportunity to make life simpler by using a date/time picker (time pickers are rather clumsy unfortunately).
  - One thing you should definitely do is to automatically adjust later dates when earlier dates are changed.  For example, I see 
    - Start at: 2015-01-10T07:58:39
    - Due at: 2015-01-10T07:58:39

    If I change "Start at" to 2015-01-12T07:00:00, it would be good if "Due at" were changed to it as well since the due date cannot be before the start date.
  - Under "Problems": it would be better if problems could be added using Ajax calls rather than by going to do different page.  Also, when coming back from adding a problem, the application goes to "Basic" -- that's extra work because we typically enter problems in batches.
  - Also under "Problems", the explanation text is really small (even for me, and my eyesight is pretty good).

In general, seeing all the options for an assessment in a single page was much more convenient than having it split into 4 tabs (which are really separate pages).

**Comment by dlbucci** [comment]
Also, editing problems should redirect to the problems tab.

**Comment by dlbucci** [comment]
Also, professors seem to think the tabs are unintuitive because they still reload the whole page, and some professors have even tried to switch tabs before saving, only to lose their settings.  AJAX would be nice.  (AJAX problem editing would also be good).

**Comment by Z1MM32M4N** [comment]
I'll be getting around to standardizing the datetime pickers across the inputs here really soon. The [library we'll be using][1] has nice support for both textual editing as well as dropdowns, and has an option for linked fields (i.e., one cannot come before another).

[1]: https://github.com/Eonasdan/bootstrap-datetimepicker

**Comment by Z1MM32M4N** [comment]
Summary:
Clicking through different tabs not saving: #180
Datepickers: #181
Add problems over AJAX calls: #179
Text too small: #101 

Merging this issue into the issues listed above.
