### ISSUE TITLE
Autograder Settings should give error message if there is a problem with save

### ISSUE THREAD

**Issue by icanb** [autolab/Autolab#604]
"to any value above 599, the update silently fails with absolutely no feedback - and if the VM Image has also been changed, it resets the value in that field as well. Having a max timeout is arguably reasonable (though I would add as an aside that it certainly reinforces my decision to take Compiler Design off of Autolab, since we're regularly into the territory of 30-45 minute grader runs), but it is completely ridiculous to simply fail to save any information with no feedback to the user whatsoever."

**Comment by nayak16** [comment]
@cg2v Do you think this is the same issue as #708 ? I'm looking into both

**Comment by cg2v** [comment]
My interpretation of this issue is that it is about AutogradersController:update not providing feedback if it cannot save

#708 is about local_submit not completing tango submission and swallowing the error

**Comment by damianhxy** [comment]
As far as I can tell, #974 added an error flash if the Autograder settings can not be saved. Also 4eb4feb increased the timeout to 900 seconds.

Marking as resolved
