### ISSUE TITLE
Import Roster/Users does nothing on some of the browsers

### ISSUE THREAD

**Issue by icanberk** [autolab/Autolab#61]
I've had a report that clicking Import Roster/Users does nothing.  My testing shows,

Linux, Chromium: single click works/takes you to the upload file page
Linux, Firefox:  single click works

Mac OS, Chrome:  single click works
Mac OS, Firefox: single click works
Mac OS, Safari:  does not work

Windows, IE:      single click works
Windows, Chrome:  single click works
Windows, Firefox: does not work

**Comment by dlbucci** [comment]
I'm not sure this is still an issue.  I think it had to do with waves.js, which we removed.
