### ISSUE TITLE
drop downs need to be made easier to search

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#610]
The drop down boxes used for selecting a student in the Manage Extensions and Create New Submission pages need to be reengineered to be easier to use. The Manage extensions drop down is not alphabetized, requires the user to type very fast in order to disambuate. The Create New Submission drop down is alphabetized by user id, but has the same fast typing requirement.

**Comment by remzr7** [comment]
@droh @ymzong are we looking for something that behaves like the search selection component at 

http://semantic-ui.com/modules/dropdown.html ?

**Comment by droh** [comment]
Yes, exactly.

-- David O'Hallaron
-- Prof of CS and ECE, Carnegie Mellon University
-- GHC 7517, x8-8199
-- http://www.cs.cmu.edu/~droh

**Comment by droh** [comment]
This is the same issue as #602 and #591.

**Comment by zyx-billy** [comment]
Closed with pr #636 and #637
