### ISSUE TITLE
Overall gradebook statistics should break things down like the assessment statistics page

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#612]
The overall course statistics page shows results for the entire class. It should also break things down like the assessment statistics page.

**Comment by remzr7** [comment]
Can't we just replace this with the new statistics page from #611 ?

**Comment by nayak16** [comment]
Yes this issue can be consolidated with #611

**Comment by remzr7** [comment]
@droh @icanberk This is how the revamped statistics page looks like: 

![screen shot 15](https://cloud.githubusercontent.com/assets/5417284/14697151/4d4d393e-074f-11e6-8b2c-a5114939eea0.jpg)

![screen shot 19](https://cloud.githubusercontent.com/assets/5417284/14697156/52c97ef4-074f-11e6-83f8-4a7430a12da6.jpg)

What do you think?

**Comment by remzr7** [comment]
Closed with #611
