### ISSUE TITLE
attachments should be stored in the course directory

### ISSUE THREAD

**Issue by cg2v** [autolab/Autolab#617]
There seems to be no good reason for attachments to live in a single toplevel directory. Why aren't they in the course or assessment directory?

**Comment by TheodorJ** [comment]
Wow, apparently all of the attachments for all courses seem to be stored in the ./attachments folder with no heirarchy. Leaving this one open.

**Comment by victorhuangwq** [comment]
Not sure if this issue is still relevant in the latest master. Let me know if it is.

**Comment by mtoupsUNO** [comment]
I'm pretty sure it still is relevant. I still observe this behavior in my deployment. I'm not running the latest master there, but it isn't very out of date. And I see no meaningful changes to `app/models/attachment.rb` in the past two years.

**Comment by victorhuangwq** [comment]
@mtoupsUNO thank you for the update. I will keep this open.

**Comment by damianhxy** [comment]
Addressed in #1810 (currently in develop) by switching to ActiveStorage.
