### ISSUE TITLE
SQLite3 implicitly in Gemfile for production

### ISSUE THREAD

**Issue by rbrigden** [autolab/Autolab#622]
Just took a look through the Gemfile and was a little confused why sqlite3 and mysql2 are bundled by default. Is there a specific reason for this? Maybe one (probably sqlite3 is supposed to be separated into :development env config? There also seems to be know explicit bundle config for :production in Gemfile.

**Comment by ymzong** [comment]
The reason why `Gemfile` includes `sqlite3` is that we are in the progress of supporting sqlite as database, in addition to MySQL.

Also, for this project, there aren't much difference between `production` and `test` gemsets, so we are kind of merging them together.

If you think modularization is a better approach and is worth the effort, feel free to submit a PR for it! :smile_cat:
