### ISSUE TITLE
Allow the option to specify extension as # of days _or_ new due date

### ISSUE THREAD

**Issue by ymzong** [autolab/Autolab#629]
Currently, our assessment extension only allows instructors to specify "number of days of extension."

There was a feature request to add an option to specify a target due date for the extension, regardless of the due date.

I don't think this is urgent, but it could be a great bootcamp task for front-end developers.

Thoughts? @remzr7 @zyx-billy

**Comment by zyx-billy** [comment]
Sounds like a nice beginning task. I'll take a look at it.

**Comment by zyx-billy** [comment]
Closed with pr #636
