### ISSUE TITLE
Assessment name shouldn't start with number

### ISSUE THREAD

**Issue by ymzong** [autolab/Autolab#632]
According to a bug report, an instructor was able to create an assessment whose name begins with a number (e.g. `15000assignmentone`). This is unsupported as a Ruby object name, and we need to block this on our front-end.

Relevant page: `https://AUTOLAB_HOST/courses/COURSE_NAME/assessments/new`

**Comment by andersonleite** [comment]
Hi @ymzong 
How about adding a validation in the assesment.rb model?

`validates_format_of :name, :with => /^[a-zA-Z]+$/, :multiline => true`

This way we can block server receiving assessment starting with numbers and will make use of the actual notifications:

The result message in the frontend would be like that:

> Error saving 15000assignmentone: Validation failed: Name is invalid

Let me know if I can submit this PR.

**Comment by ymzong** [comment]
Yep @andersonleite, that's exactly what I was thinking about. Go ahead and submit your PR!

**Comment by remzr7** [comment]
@ymzong have you looked at this commit?

**Comment by ymzong** [comment]
Yeah, it's already been pulled to master as cd88a445
