### ISSUE TITLE
Automatic Setup Script for Autolab Front-end

### ISSUE THREAD

**Issue by ymzong** [autolab/Autolab#638]
We should continue pushing for an automatic setup script for Autolab. Ideally, our `README` should say the following instead the daunting chain of instructions now:

> To install & configure Autolab and its dependencies, run:
> `curl -sL https://raw.githubusercontent.com/autolab/Autolab/master/setup.sh | sudo bash -`

I'm going to start working on the script for Ubuntu 14.04+ and Docker -- folks using Mac can join in and create the Mac-compatible script. (I expect there to be major differences at least on the parts that install the dependencies.)
- [x] Ubuntu 14.04+ script
- [ ] Mac script
- [ ] Docker script

**Comment by nayak16** [comment]
Related to #774

**Comment by Rots** [comment]
Even easier, if you'd publish the autolab docker image publicly.
Also see related
https://github.com/autolab/autolab-oneclick/issues/7

**Comment by victorhuangwq** [comment]
One click is currently deprecated, and won't be worked on. Closing issue.
