### ISSUE TITLE
More Thorough ReadMe

### ISSUE THREAD

**Issue by devanshk** [autolab/Autolab#644]
Some parts of the setup instructions should be explained better and there's atleast one command missing. As someone new to how things worked, it would help to have more detailed instructions on certain steps.

**Comment by ymzong** [comment]
I worked with the instructions recently, and it worked fine for me on Ubuntu 14.04.

What is the command that is missing?

**Comment by devanshk** [comment]
I'm talking about the instructions in the readme for the main Autolab page - Jacob Zimmerman's Ubuntu page is a separate file.

The command to 'Configure Device for Safe Authentication' is missing from this one.

**Comment by ymzong** [comment]
@devanshk Gotcha, good catch! Feel free to update it in `./README`.

How was it like to set up Autolab on Mac? In the long run, I'm hoping to port my Ubuntu 14.04 installation script to Mac users by using Docker.

**Comment by devanshk** [comment]
Most of the setup was straight-forward, but a few parts required Googling and following multiple links to understand how to do something. Namely in MySQL setup, but that seems to be outside the scope of a setup script.
