### ISSUE TITLE
Grade Import workflow can be confusing

### ISSUE THREAD

**Issue by ymzong** [autolab/Autolab#647]
According to Seth, the specified column headers didn't match the ones required by the system. Also, the instructions were not clear enough.

**Comment by TheodorJ** [comment]
The instructions could definitely be clarified. "Grade Type" can be explained further and "Score/Feedback" should be clarified (How do we input feedback?). Leaving this issue open.

**Comment by TheodorJ** [comment]
Turns out, #874 already covers this in a little more depth. Closing
