### ISSUE TITLE
handin requires javascript but it's not obvious

### ISSUE THREAD

**Issue by cg2v** [autolab/Autolab#667]
The autolab UI generally appears to work even if javascript is disabled or blocked by noscript, and this can create confusion if someone tries to use a feature (handin, annotations, gradebook) that depends on javascript while it's disabled or blocked.

I think it would be appropriate to either
- allow handins to work without javascript by not hiding the file picker button in the base html, but have the same script that registers the event handlers hide it, or
- include some <noscript> html near the submit button explaining that submissions don't work without javascipt.

**Comment by devanshk** [comment]
Addressed by #910
