### ISSUE TITLE
'Creating a Course' is CMU-Only

### ISSUE THREAD

**Issue by devanshk** [autolab/Autolab#674]
'Creating a Course' in the Instructor Guide and on its own page is CMU-Specific. This should be expanded for third-parties trying to use Autolab.

**Comment by zyx-billy** [comment]
This seems to be specific to the old docs, as the [new ones](https://autolab.github.io/docs/) no longer mention creating courses. (There's now a separate page in our wiki for creating courses at CMU).
For third-parties, the [no_user page](https://github.com/autolab/Autolab/blob/master/app/views/home/no_user.html.erb) (displayed when someone logs in with no associated courses) will let the user know to ask their system admin to create courses. And of course, whoever deploys this is free to change the help text on that page in their deployment.
