### ISSUE TITLE
Couldn't upload a file to submit

### ISSUE THREAD

**Issue by zhuzhuzhulc** [autolab/Autolab#677]
So I couldn't find the upload button when I try to submit the file. 

I tried different browser including chrome, firefox and IE. 

![1](https://cloud.githubusercontent.com/assets/7123786/17275948/33abea0a-574c-11e6-9c1d-9ee9cf2ed630.jpg)

**Comment by ymzong** [comment]
@zhuzhuzhulc If you click the "Submit File" button, there should be a popup that asks you to select your file for uploading.

**Comment by zhuzhuzhulc** [comment]
`Thanks for the reply but that's not what happening. I got a instruction telling me that upload was blank by clicking the submit file button. 
![2](https://cloud.githubusercontent.com/assets/7123786/17286906/1a1202a6-57ff-11e6-8e05-0f8e12ee6505.jpg)

**Comment by zhuzhuzhulc** [comment]
Also I looked into the source code of the web page, there is a input of file type but it's hidden somehow

**Comment by cg2v** [comment]
Do you have javascript disabled or blocked? The submit button does not do the right thing in that case. (#667)

**Comment by zhuzhuzhulc** [comment]
I didn't disabled or blocked the javascript and I tried the webpage on many different computers, the results are the same. I have a very limited time before the deadline of this lab, is there another solution to this problem?

**Comment by zhuzhuzhulc** [comment]
I didn't disabled or blocked the javascript and I tried the webpage on many different computers, the results are the same. I have a very limited time before the deadline of this lab, is there another solution to this problem?

**Comment by zhuzhuzhulc** [comment]
I didn't disabled or blocked the javascript and I tried the webpage on many different computers, the results are the same. I have a very limited time before the deadline of this lab, is there another solution to this problem?

**Comment by zhuzhuzhulc** [comment]
I didn't disabled or blocked the javascript and I tried the webpage on many different computers, the results are the same. I have a very limited time before the deadline of this lab, is there another solution to this problem?

**Comment by zhuzhuzhulc** [comment]
I didn't disabled or blocked the javascript and I tried the webpage on many different computers, the results are the same. I have a very limited time before the deadline of this lab, is there another solution to this problem?

**Comment by zhuzhuzhulc** [comment]
I didn't disabled or blocked the javascript and I tried the webpage on many different computers, the results are the same. I have a very limited time before the deadline of this lab, is there another solution to this problem?

**Comment by zhuzhuzhulc** [comment]
I didn't disabled or blocked the javascript and I tried the webpage on many different computers, the results are the same. I have a very limited time before the deadline of this lab, is there another solution to this problem?

**Comment by zhuzhuzhulc** [comment]
I didn't disabled or blocked the javascript and I tried the webpage on many different computers, the results are the same. I have a very limited time before the deadline of this lab, is there another solution to this problem?

**Comment by zhuzhuzhulc** [comment]
I didn't disabled or blocked the javascript and I tried the webpage on many different computers, the results are the same. I have a very limited time before the deadline of this lab, is there another solution to this problem?

**Comment by zhuzhuzhulc** [comment]
I didn't disabled or blocked the javascript and I tried the webpage on many different computers, the results are the same. I have a very limited time before the deadline of this lab, is there another solution to this problem?

**Comment by zhuzhuzhulc** [comment]
I didn't disabled or blocked the javascript and I tried the webpage on many different computers, the results are the same. I have a very limited time before the deadline of this lab, is there another solution to this problem?

**Comment by zhuzhuzhulc** [comment]
I didn't disabled or blocked the javascript and I tried the webpage on many different computers, the results are the same. I have a very limited time before the deadline of this lab, is there another solution to this problem?

**Comment by zhuzhuzhulc** [comment]
I didn't disabled or blocked the javascript and I tried the webpage on many different computers, the results are the same. I have a very limited time before the deadline of this lab, is there another solution to this problem?

**Comment by zhuzhuzhulc** [comment]
I didn't disabled or blocked the javascript and I tried the webpage on many different computers, the results are the same. I have a very limited time before the deadline of this lab, is there another solution to this problem?

**Comment by zhuzhuzhulc** [comment]
I didn't disabled or blocked the javascript and I tried the webpage on many different computers, the results are the same. I have a very limited time before the deadline of this lab, is there another solution to this problem?

**Comment by zhuzhuzhulc** [comment]
I didn't disabled or blocked the javascript and I tried the webpage on many different computers, the results are the same. I have a very limited time before the deadline of this lab, is there another solution to this problem?

**Comment by ymzong** [comment]
@zhuzhuzhulc, could you send an email to `autolab-dev@andrew`? We can take this offline and help you resolve the issue.
