### ISSUE TITLE
No implicit conversion of Pathname into String (TypeError)

### ISSUE THREAD

**Issue by magsol** [autolab/Autolab#679]
Round two of getting production AutoLab up and running--when I switch from "development" mode into "production" (no other changes), I once again cannot load up the main page and get an error message. Here's what I see in the Apache error logs:
<img width="1234" alt="screen shot 2016-08-15 at 2 44 33 pm" src="https://cloud.githubusercontent.com/assets/135417/17675279/1396e7d6-62f7-11e6-9bcf-df33818470c8.png">

It looks similar to this issue https://github.com/autolab/Autolab/issues/639, but resolving that seems to require AutoLab access: specifically, creating courses, which I can't do until I can log in.

**Comment by ymzong** [comment]
It seems like you haven't populated `config/autogradeConfig.rb` from the sample file `config/autogradeConfig.rb.template`. The template contains instructions for how to modify the config -- feel free to ping us if you have any questions about it!

**Comment by magsol** [comment]
So I just realized I somehow skipped the step entirely of using the `setup.sh` script to automate all the setup and install--and the script includes renaming `autogradeConfig.rb`.

Thanks! Still having a few hiccups switching over to production, but steadily moving forward.

**Comment by ymzong** [comment]
Yeah I actually wrote the script earlier this year so people could quickly get Autolab up and running from a clean VM, but I guess setting everything up manually would be better for people who want to deploy it seriously so they understand the components involved.

Feel free to ping us if you have further questions!

**Comment by magsol** [comment]
I've written a couple emails to the `autolab-dev@andrew.cmu.edu` address with no response; sorry to ping you this way, but getting AutoLab up and running is slightly time-sensitive. Is there a different way I should get in touch aside from opening and closing issues?

**Comment by ymzong** [comment]
@magsol Sorry about the delay -- the majority of Autolab team are doing internships / full-time jobs during summer (including me), so there might be a delay in our response. We do check `autolab-dev` email though!
