### ISSUE TITLE
redirect students from autolab.cs to autolab.andrew

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#681]
According to Tom Cortina, students are getting confused when they mistakenly visit autolab.cs instead of autolab.andrew and don't see their courses. 

Could we add some text to autolab.cs.cmu.edu page (on milkshark) that explains that this version of Autolab cover courses prior to Spring 2016 and that they should visit autolab.andrew.cmu.edu for their current courses.

**Comment by devanshk** [comment]
Temporary fix was implemented with a system-wide announcement. The announcement could be improved by having it show up on the home-page rather than just inside each course, but that's not as high-priority as other issues.
