### ISSUE TITLE
Unhelpful and outdated UI Autograder Output from administrator grade page

### ISSUE THREAD

**Issue by rlasko** [autolab/Autolab#686]
TAs care about the error messages students encounter and to help them we often look at what errors they have. However the UI automatically opens up an extremely small that displays less than 30 characters across! 

To meaningfully look at the output a TA is forced to drag open a very clunky textbox which expands to larger than the popup size which appears awkward and is super unhelpful. A better UI would allow TAs to open up the output in a large window and quickly find and remedy the student's error.

**Comment by rlasko** [comment]
Do look at the attached images

<img width="565" alt="screen shot 2016-09-11 at 12 34 37 am" src="https://cloud.githubusercontent.com/assets/15827934/18415202/b7961544-77b7-11e6-96ff-94264a1a2c39.png">
<img width="668" alt="screen shot 2016-09-11 at 12 33 54 am" src="https://cloud.githubusercontent.com/assets/15827934/18415203/b7cd2d5e-77b7-11e6-8c7d-bb188b555067.png">

**Comment by devanshk** [comment]
Merged into #695
