### ISSUE TITLE
Annotate Submission View doesn't display lines longer than 80 characters (and no ability to scroll)

### ISSUE THREAD

**Issue by mriveralee** [autolab/Autolab#692]
![screen shot 2016-09-14 at 11 27 53 pm](https://cloud.githubusercontent.com/assets/1381319/18537366/fbaec064-7ad2-11e6-9f6c-f29002fd6167.png)

Actual text on line 19 should read as below but the annotation viewer does not scroll or wrap the text- it just clips it off.

```
mFibSumTextView.setText(getString(R.string.fib_string, 20, calculateFibonacciNumber(20)));
```

**Comment by mriveralee** [comment]
As a note, if you click to add an annotation to the text, it shows up (wrapped to a new line), but the initial behavior is unexpected and almost lead to grade something as incorrect.  
![screen shot 2016-09-14 at 11 34 29 pm](https://cloud.githubusercontent.com/assets/1381319/18537505/f154803a-7ad3-11e6-8a15-93dccbe1becd.png)

**Comment by AmirAlavi** [comment]
I'd like to also give voice to this issue. Code view should have horizontal scrolling. Is this planned as an update/new feature?

**Comment by zyx-billy** [comment]
This seems to have been fixed now (could anyone confirm this?). I tried this just now, and the code view does show a horizontal scrolling bar.

Additionally, there's the option to highlight lines that are over 80 characters, so the red highlight could also serve as an indicator that there's more text on this line.

**Comment by zyx-billy** [comment]
Just an update on this: @TheodorJ is working on a complete redesign of the annotations page, so we'll make sure this gets addressed in the new version.

**Comment by TheodorJ** [comment]
Can confirm that scrolling works on our master and develop branches. Closing this issue
