### ISSUE TITLE
Assignment Name missing from submission downloads

### ISSUE THREAD

**Issue by mriveralee** [autolab/Autolab#693]
Downloading the submissions for an assignment has all of the files names in the following format:
`<email>_<version>_handin.<ext>` eg: `testUser@andrew.cmu.edu_1_handin.zip`

This isn't idea when you download submissions for multiple assignments. It would be helpful to have the name of the assignment in the file names- for example: 
`<email>_<assignment_shortname>_<version>_handin.<ext>`

For example `testUser`'s version `1` for assignment `A0` could have a format such as:
`testUser@andrew.cmu.edu_A0_v1_handin.zip`

**Comment by zyx-billy** [comment]
This should be a easy fix so I thought I'd just go resolve this first. If we don't want to change the name we use when storing handins on the server, we could just construct a new name for use when downloading (at download time).
The only questions is would we want to implement this then, maybe there's something else we want to add to the name? @nayak16 Any suggestions?
