### ISSUE TITLE
Download Annotated Pdf doesn't include annotations

### ISSUE THREAD

**Issue by mriveralee** [autolab/Autolab#694]
Steps to Repro:
1. Upload PDF submission
2. Add annotations to pdf
3. Witness annotations in preview mode
4. Download Annotated PDF
5. Witness no annotations appear in the pdf

**Comment by jbman223** [comment]
I have just tried to recreate this bug on the current develop branch, and was not able to reproduce the bug. Following your instructions directly, after hitting "Download Annotated" button, the PDF was downloaded with annotations. If anyone else can double check this bug & see if they can reproduce, that would be great.

**Comment by zyx-billy** [comment]
Just tried this as well and the resulting pdf does include annotations.
However, an annotation on the second page was split into two pieces: the text remained on the second page, but the red border box showed up on the first page. Seems like there's a mistake in the pdf-generating code.
