### ISSUE TITLE
Autolab Feedback Box UX

### ISSUE THREAD

**Issue by devanshk** [autolab/Autolab#695]
Autolab feedback box starts too thin, which is a problem for TAs who have to look at the feedback for multiple students and repeatedly expand the box each time.

**Comment by zyx-billy** [comment]
This should definitely have a high priority. There's already 3 issues submitted regarding this feedback box:
#523 #570 #686.

**Comment by devanshk** [comment]
Reopened to merge other three issues into one

**Comment by nayak16** [comment]
Merged
