### ISSUE TITLE
autograding submissions can fail silently

### ISSUE THREAD

**Issue by cg2v** [autolab/Autolab#708]
An instructor reported to computing services that some submissions had no scores. I verified in at least one case that a submission was received via local_submit, but tango only got the upload requests, not the addJob.

The course log does not indicate any error.
I think this means that autograde.rb:save_daves failed (most other failure paths include a COURSE_LOG), but can't be certain

**Comment by cg2v** [comment]
FWIW, the underlying problem in these cases seems to be a problem with the computing services network or load balancer. Some retry/transactional logic in the tango client could be helpful with this, but the failure itself was not autolab's fault.

**Comment by zyx-billy** [comment]
Seems to be the same problem as #983. Closing this one and leaving that one.
