### ISSUE TITLE
Version Penalty does not account for deleted submissions

### ISSUE THREAD

**Issue by zyx-billy** [autolab/Autolab#710]
As reported, after an earlier submission was deleted by course staff, the total number of submissions is not updated when considering version penalty.

**Comment by zyx-billy** [comment]
The code for giving penalty (in submission.rb) only compares the version number (which simply increments for each new submission) with the version penalty threshold. To account for deleted submissions, this entire logic would need to be fixed.

**Comment by TheodorJ** [comment]
Merged #753
