### ISSUE TITLE
delete my own user account

### ISSUE THREAD

**Issue by 5nizza** [autolab/Autolab#712]
Go to manage course -> manage students -> click on my own account -> edit user -> delete user.

Nothing happens.

Expected: I removed myself and kicked out of the system.
Or this is a feature?

**Comment by remzr7** [comment]
@5nizza did you login through CMU's authentication?

**Comment by 5nizza** [comment]
no, that is our local installation.

**Comment by ymzong** [comment]
@5nizza This is expected behavior to prevent accidental account deletion.
