### ISSUE TITLE
Tango Stalling

### ISSUE THREAD

**Issue by 5nizza** [autolab/Autolab#722]
- I uploaded the infinite sleep submission
- while Autolab waited for Tango to return, I uploaded one more infinite sleep 
- while these two jobs were waiting, I uploaded one normal submission

Tango timed out on the first two. The last one (normal submission) hanged, so I destroyed it.

Now: no more jobs can be run on Tango -- they are put into the waiting queue but never get executed.
Suggestions?

Here is what autolab reports for the last 30 minutes:

![status](https://cloud.githubusercontent.com/assets/928552/19725880/75a15ce4-9b88-11e6-93c8-250e62dc0779.png)

System info:

AUTOLAB commit 7c8ba833054f1993504a2f01bf47c2b1f358b00b
Add ssl configuration
TANGO commit 095f4e33c4685d997f251b77e3c3a3d901fa8463
_No REDIS_ server

**Update**: our admin just fixed fixed a race-condition in Tango timeout kill logic.( It did help with simple cases, but not with more difficult cases.

**Comment by 5nizza** [comment]
**Update:** 
We added REDIS server. Now several jobs can be run in parallel, but the timout is not respected. Now autolab shows a list of ~10 jobs that are run for > 10min, although the timeout is 60sec (some of those jobs are "infinite sleep" so they can really run so long, but some of the jobs are normal and certainly finish within 20seconds).

**Comment by nayak16** [comment]
Sometimes Tango get into a limbo state communicating with jobs. My suggestion is to kill all Tango processes (server and jobManager). Then, with the redis-server running, run `redis-cli FLUSHALL` which will clean all redis info. Restart tango and the jobManager and check if you can successfully run jobs again.

**Comment by nayak16** [comment]
Was this solved?

**Comment by 5nizza** [comment]
we stopped using autolab, so yes, in a way...
