### ISSUE TITLE
Import users: which encoding? which line endings?

### ISSUE THREAD

**Issue by 5nizza** [autolab/Autolab#723]
1. Encoding: It seems that you can import in UTF8 but non-ASCII letters are not accepted anyway -- actually, autolab shows it correctly in previes, but when you press 'import', it gives you bunch of ? symbols instead of real names.
   Which encoding does autolab support?
2. Line endings: seems that Mac line endings should be used. Right?

**Comment by TheodorJ** [comment]
This was addressed in #874. Closing
