### ISSUE TITLE
Autolab UI does not render properly inside an IE Intranet zone

### ISSUE THREAD

**Issue by nayak16** [autolab/Autolab#727]
This seems to be a specific issue with clusters at CMU. The clusters and virtual Andrew configuration makes use of the IE Intranet zone, and has (or defaults to) "Use compatibility mode in the intranet zone" enabled. This prevents css and jquery from working properly. One way to attempt a fix would be to try and have the autolab server send an X-UA-Compatible header. (This is not normally needed for HTML5 pages properly declared with <!DOCTYPE html>)

**Comment by victorhuangwq** [comment]
Issue is stale and likely no longer relevant. Closing.
