### ISSUE TITLE
Display times in user's timezone

### ISSUE THREAD

**Issue by dnivra** [autolab/Autolab#729]
Currently, the times being displayed(eg: deadline for an assessment) are based on the time zone configured in `config/application.rb`. It seems only UTC times are stored in the database. Perhaps, users can configure their preferred time zone in their profile and the settings in `config/application.rb` could be used as fallback in case users don't set their preferences.

**Comment by zyx-billy** [comment]
Instead of making it a user setting, all times will be displayed in the user's browser time zone. See PR #775.
