### ISSUE TITLE
Manage accounts page: Column sorting broken

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#74]
Clicking on a column header should sort the table on that column, but it doesn't.

**Comment by Z1MM32M4N** [comment]
@autolab/developers What library was being used for table sorting earlier? If there was one, I can look into alternatives, but I don't want to add extra functionality if it's already there.

**Comment by dlbucci** [comment]
jquery sorttable, I believe.  It used to be on loaded on every page by being on the application layout, but it would be better if we only loaded it when tables are on the page.

**Comment by Z1MM32M4N** [comment]
Duplicate of #1.
