### ISSUE TITLE
entire "blocks" in materialize should be links

### ISSUE THREAD

**Issue by cg2v** [autolab/Autolab#756]
Since there are no buttons or links on the new course list index page, AND the whole block has a shadow animation, the whole block, and not just the text, should be a link to the course.

**Comment by cg2v** [comment]
Actually, this happens across the entire site, not just on the index page. If link text is no longer marked as a link and underlined, the surrounding container should be the link

**Comment by nayak16** [comment]
@zyx-billy this was the issue you brought up before. Can you fix this?

**Comment by zyx-billy** [comment]
fixed with #767.
