### ISSUE TITLE
Allow users to register themselves for courses using unique links

### ISSUE THREAD

**Issue by nayak16** [autolab/Autolab#764]
We should add an extra feature so that an Instructor creating a course can choose whether to allow students to register themselves for the course. This way, we don't need any complicated methods to register contestants for programming challenges; instead, the organization posts a link to the course and the contestants register themselves.

Complement to #420

**Comment by nayak16** [comment]
This [link](http://stackoverflow.com/questions/19115929/generating-a-unique-url-with-tokens-in-rails-4-for-an-external-form-response) will be useful

**Comment by damianhxy** [comment]
Closing as duplicate of #1786
