### ISSUE TITLE
OSX Setup script does not run out-of-box

### ISSUE THREAD

**Issue by TheodorJ** [autolab/Autolab#774]
After running the OSX setup script, you see a bunch of errors that don't need to be fixed (Let's fix this later). The real problem is that when you run "bundle exec rails s", the server doesn't start. We need to modify the setup script/server commands such that all a user needs to do is run the setup script and type a command to run the server without complications.

**Comment by TheodorJ** [comment]
Let's try to fix this by Wednesday, February 1.

**Comment by jbman223** [comment]
Is there an error message when you run the rails server?

**Comment by jbman223** [comment]
It looks like macs come with SQLITE installed, so we can take that out of the script. https://razorsql.com/articles/sqlite_mac.html

**Comment by jbman223** [comment]
Script has some big issues with installing the gems, on my computer it was complaining about permissions and then eventually failed the install.

**Comment by TheodorJ** [comment]
Sorry about the delay in response; when I run rails server, I get a long error message that I have yet to decipher, but it's most likely a version issue between gems (I'll look into this). If sqlite comes preinstalled on all versions of OSX that we can assume will be running this script, then I'll go ahead and remove the sqlite install and push that. Also, about the permissions error, we can try running each (or some) commands as root and see if that solves the permissions problems.

**Comment by TheodorJ** [comment]
Alright, I've gotten a server up and running. I had to replace a few deprecated lines of code, and then I had to add the line "extend Devise::Models" to app/models/user.rb. If these changes work when Autolab is running on linux, then we can talk about how to merge them in.

**Comment by TheodorJ** [comment]
Also, I am getting an error message when I navigate to localhost:3000, I get an SQLite exception:
"no such table: scheduler" at app/controllers/application_controller.rb. If this is an SQLite problem, we may have to work on using MySQL instead.

**Comment by TheodorJ** [comment]
Alright, so when I try to access localhost:3000 I keep getting a MySQL2 "Access denied for user 'root'@'localhost'" error .. in fact, this happens whenever I try to do anything involving MySQL. Based on how unfriendly, this is, we should probably find out why SQLite isn't working.

**Comment by nayak16** [comment]
Done as part of new docs
www.autolab.github.io/docs
