### ISSUE TITLE
Annotations Summary should auto-update

### ISSUE THREAD

**Issue by devanshk** [autolab/Autolab#783]
On the code annotations page, the annotations summary doesn't auto-update as you add annotations to the code. You need to click a button to refresh the summary.

<img width="1440" alt="screen shot 2017-02-26 at 2 30 38 pm" src="https://cloud.githubusercontent.com/assets/1356687/23342882/3844986c-fc30-11e6-8a35-772781a41a57.png">

^Note the 'Reload Summary' button and that the second annotation is missing from the summary. It should be automatically added in like this:
<img width="1440" alt="screen shot 2017-02-26 at 2 32 18 pm" src="https://cloud.githubusercontent.com/assets/1356687/23342897/64c328cc-fc30-11e6-9807-434ecb232a5a.png">

We can probably do this locally with javascript.

**Comment by victorhuangwq** [comment]
Issue no longer present under speedgrader upgrade. https://github.com/autolab/Autolab/releases/tag/v2.4.0
