### ISSUE TITLE
Scoreboard Settings Page Visuals need a materialize overhaul

### ISSUE THREAD

**Issue by devanshk** [autolab/Autolab#784]
Current screen is clunky and difficult to navigate:

<img width="1440" alt="screen shot 2017-02-26 at 3 18 30 pm" src="https://cloud.githubusercontent.com/assets/1356687/23343305/22bb7144-fc37-11e6-8184-e77e531818e3.png">

**Comment by nayak16** [comment]
Fixed in #796
