### ISSUE TITLE
gradesheet sorting is lexical, not numeric

### ISSUE THREAD

**Issue by cg2v** [autolab/Autolab#791]
This was reported by a CMU faculty in F16, and worked around in the computing services deployment:

When I click on Grade Submissions, then click on a field (say, "Autoscore") to sort by that field, the sorting is not numeric, but seemingly alphabetic.
and
...TA noticed that this works properly if we click on "Total"

My workaround is clearly non-optimal: I added
if (type == "sort" && score != "" && score != "-") return Number(score);
right above the return in the render function in _gradesheet.html. I assume it would be better to store the values as numbers from the beginning, but I don't have enough javascript experience to know if there would be bad side effects from that.

**Comment by nayak16** [comment]
Fixed in #792
