### ISSUE TITLE
Nav Drawer Slides out from the Left on Mobile

### ISSUE THREAD

**Issue by zyx-billy** [autolab/Autolab#798]
On mobile devices, the navigation drawer slides out from the left, whereas the menu button is on the right:
![image](https://cloud.githubusercontent.com/assets/3676913/23485047/bc133454-fea7-11e6-9514-25b900bcba6f.png)

**Comment by jbman223** [comment]
I have created a fix for this, it is very simple and supported by the framework. The material design specs; however, call for a navbar that slides in from the left. I am wondering if we stick with  the specifications here, move the nave popout to the other side, or move the button to the left.

@zyx-billy @nayak16 @devanshk

**Comment by zyx-billy** [comment]
I think it would be best to follow the spec? It doesn't seem hard to move the menu icon to the left side and center the logo on mobile using materialize.

**Comment by nayak16** [comment]
Just saw this. Agree with @zyx-billy let's follow the spec

**Comment by jbman223** [comment]
I'll submit my PR tonight.

**Comment by devanshk** [comment]
Addressed by #857
