### ISSUE TITLE
Jobs page: link for running job broken

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#80]
The link for a running job doesn't point to anything. It should show the current state of the job trace.

**Comment by icanberk** [comment]
hi @droh ,

It seems to work for me.

![screenshot 2015-01-29 13 42 15](https://cloud.githubusercontent.com/assets/803072/5963727/aa190218-a7bc-11e4-84e5-3b98bdbbebfb.png)
When I click on "Input copied ..."

It brings me to this page with all the trace: https://autolab.cs.cmu.edu/courses/28/jobs/100/getjob

Am I missing something here?

Ilter

**Comment by droh** [comment]
I think jimmy might have fixed it earlier.

On Thursday, January 29, 2015, Ilter <notifications@github.com> wrote:

> hi @droh <https://github.com/droh> ,
>
> It seems to work for me.
>
> [image: screenshot 2015-01-29 13 42 15]
> <https://cloud.githubusercontent.com/assets/803072/5963727/aa190218-a7bc-11e4-84e5-3b98bdbbebfb.png>
> When I click on "Input copied ..."
>
> It brings me to this page with all the trace:
> https://autolab.cs.cmu.edu/courses/28/jobs/100/getjob
>
> Am I missing something here?
>
> Ilter
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autolab/Autolab/issues/80#issuecomment-72079821>.
>


-- 
Sent from my iPhone.
