### ISSUE TITLE
generated favicon link is incorrect

### ISSUE THREAD

**Issue by cg2v** [autolab/Autolab#809]
&lt;%= favicon_link_tag 'favicon.ico?v=1' %&gt;
in layouts/application.html.erb expands to
    &lt;link rel="shortcut icon" type="image/x-icon" href="/images/favicon.ico?v=1" /&gt;

but the image is in public, not public/images.

**Comment by zyx-billy** [comment]
This seems to have slipped in with the UB changes. There's now two identical favicons, but this current link points to neither of them.

**Comment by zyx-billy** [comment]
Fixed by #908 (merged into develop).
