### ISSUE TITLE
Grading window appears in layer below document

### ISSUE THREAD

**Issue by blakehurlburt** [autolab/Autolab#812]
When grading a document that is multiple pages long, the grading window appears in the layer above the page clicked on (as intended) but in the layer below the following page. This hides the Save and Cancel buttons, making it impossible to save the grade.

**Comment by devanshk** [comment]
Do you have a screenshot?

**Comment by blakehurlburt** [comment]
It works fine when you click in the middle of the page, but not on the bottom.

![autolab-1.png](https://cloud.githubusercontent.com/assets/17713675/24227850/ae3e6416-0f46-11e7-8558-b59b8b22a581.png)

![autolab-2.png](https://cloud.githubusercontent.com/assets/17713675/24227851/ae41a220-0f46-11e7-9b42-5377b98e86cb.png)

**Comment by zyx-billy** [comment]
Turns out to be a simple z-index problem. Fixing now.

**Comment by zyx-billy** [comment]
fixed by #813.
