### ISSUE TITLE
No text on buttons on viewPDF page

### ISSUE THREAD

**Issue by zyx-billy** [autolab/Autolab#814]
The text on the buttons overflowed to the next line.
(There might seem to be space, but material buttons come with a generous side padding, which applies to all our buttons actually. It only caused a problem here because we're limiting the width of the button here)

![pdf_annotation_sidebar_button_no_text](https://cloud.githubusercontent.com/assets/3676913/24228656/fc1c88ac-0f4b-11e7-88c6-09808db563ed.png)

**Comment by nayak16** [comment]
Fixed
