### ISSUE TITLE
2-Step Assignment Submission

### ISSUE THREAD

**Issue by devanshk** [autolab/Autolab#815]
Some students are worried about submitting the wrong file, especially when their class limits their submissions.

To fix this we should have a 2-step submission process.
1. Click 'Upload' to pick and upload a file.
2. Front-end displays the file name and shows a 'Submit' button.
3. Click 'Submit' if it's the right file.

This is also a great spot to add some visual polish and make submitting a more satisfying interaction.

**Comment by victorhuangwq** [comment]
UX seems to have been addressed in the latest design. (Upload, click checkbox, then submit.) Closing this issue.
