### ISSUE TITLE
Admin looking at a course adds a user to the roster

### ISSUE THREAD

**Issue by devanshk** [autolab/Autolab#820]
Right now when an administrator opens a course for the first time, it creates a new instructor account for them and adds it to the roster.

To fix this, instead of creating a new user account for the admin, it should allow them to open it as an existing instructor in the course.

**Comment by TheodorJ** [comment]
I think it would be best to find a way to allow admins to view a course without modifying the roster at all, since we seem to get a lot of complaints about that. Definitely relevant, so I'll leave this open.

**Comment by devanshk** [comment]
Closing as this is an older version of #875
