### ISSUE TITLE
Embedded Quiz Handin Validation Not Run

### ISSUE THREAD

**Issue by zyx-billy** [autolab/Autolab#839]
Because of [this](https://github.com/autolab/Autolab/blob/master/app/controllers/assessment/handin.rb#L34) weird if condition, handin validation is run only when there's no embedded_quiz, which defeats the purpose of a validation function that checks specifically for embedded quizzes...

By the way, why is there another if block right above this one checking for the same thing (L23).

**Comment by nayak16** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github Issue](https://trello.com/c/fYf1MTdx/3-github-issue)

**Comment by victorhuangwq** [comment]
Stale issue. Closing.
