### ISSUE TITLE
Does not redirect to original url after login

### ISSUE THREAD

**Issue by zyx-billy** [autolab/Autolab#851]
When users attempt to visit a protected page without logging in, they are redirected to the login screen. After logging in, they should be automatically redirected back to the page they were originally trying to access.
Currently after login, the user is simply redirected to the home page.

**Comment by damianhxy** [comment]
https://github.com/heartcombo/devise/wiki/How-To:-Redirect-back-to-current-page-after-sign-in,-sign-out,-sign-up,-update

**Comment by damianhxy** [comment]
Actually -- on Nightly, this seems to be the current behavior already.
