### ISSUE TITLE
Bug in Create Announcement

### ISSUE THREAD

**Issue by nayak16** [autolab/Autolab#852]
From user:
"In Create Announcement, the Start and End Date times default to " NaN, NaN 12:aN AM".  When you choose one, the pop-up calendar to choose days and times is also messed up: It lists "untitled NaN" instead of the month, and there are "aN" values instead of dates."

Haven't verified this yet

**Comment by jbman223** [comment]
Confirmed this bug. Also appears in Schedulers (new, edit).

**Comment by nayak16** [comment]
Merged
