### ISSUE TITLE
Forms text is still too hard to read

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#858]
In 2.0.5, the text in the forms is still too hard to read. The bold titles for each form entry are OK, but the black letters need to be a bit bigger and thicker, and the grey letters need to be darker and thicker. 

Similarly, the blue menu items throughout need to be a little darker and thicker. 

Similarly, the links at the bottom of each page need to be darker.

**Comment by droh** [comment]
Contrast our forms text with the text that github uses when you post an issue.

**Comment by droh** [comment]
Here are specific forms that need to be fixed ("Font issues" refers to #858)
- Edit course, Edit assessment, Manage accounts: 
    Font issues
- Create new assessment from scratch: 
    Font issues. Inconsistent title sizes
- Add user to course: 
   Font issues. Edit lines need to be wider
- Edit account details: 
   There is some gibberish junk at the top of the page: "btn primary handin-btn"
   Font issues. Edit lines need to be wider. 
   Should be able to edit School and Major (so unusually long school entries don't disrupt the 
        gradebook rows).

**Comment by devanshk** [comment]
Addressed by #866
