### ISSUE TITLE
Problems with due dates

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#859]
There are some issues with the dates on the Edit Assessment Handin page:
- No check for setting "Due at" before "Start at"
- No check for setting "End at" before "Due at"
- No check for setting "Grading deadline" before "Due at"

- Any change to a date should preserve the following invariant:
"Start at" <= "Due at" <= "End at" <= "Grading deadline"

**Comment by nayak16** [comment]
This has been a problem for a while. Should be a simple fix if you do a roundtrip to the server. If you decide to do it clientside it will require some messy JS

**Comment by devanshk** [comment]
Looking into the issue, the models catch it with a validation, but the system handles it by throwing an Internal Error instead of going back to the edit page.

**Comment by jbman223** [comment]
@devanshk Good call, I switched the order of the messages. It makes a lot more sense now.
