### ISSUE TITLE
Autolab/bin/setup.sh errors

### ISSUE THREAD

**Issue by spawnflagger** [autolab/Autolab#863]
Hello,
  Referencing the instructions @ https://autolab.github.io/docs/  , Option 2, the master "[setup.sh](https://github.com/autolab/Autolab/blob/master/bin/setup.sh)" script gets an error on line 208, although there is also an earlier rake command failing too:

1st problem is line 191, where it's using backtick exec of  `bundle exec rake secret` 
, which fails because school.yml doesn't exist (yet).  A fix is to move line 195 `cp $AUTOLAB_PATH/config/school.yml.template $AUTOLAB_PATH/config/school.yml` above line 191.

---
2nd problem (that causes setup to fail)
```
~/Autolab$ bundle exec rake db:create
rake aborted!
YAML syntax error occurred while parsing ~/Autolab/config/database.yml. Please note that YAML must be consistently indented using spaces. Tabs are not allowed. Error: (<unknown>): mapping values are not allowed in this context at line 12 column 12
/home/ubuntu/.rbenv/versions/2.2.2/bin/bundle:23:in `load'
/home/ubuntu/.rbenv/versions/2.2.2/bin/bundle:23:in `<main>'
Psych::SyntaxError: (<unknown>): mapping values are not allowed in this context at line 12 column 12
/home/ubuntu/.rbenv/versions/2.2.2/bin/bundle:23:in `load'
/home/ubuntu/.rbenv/versions/2.2.2/bin/bundle:23:in `<main>'
Tasks: TOP => db:create => db:load_config
(See full trace by running task with --trace)
```

The problem here  (I assume) is that ~/Autolab/**config/database.yml.template** is missing a comment hash # for line 11 `SQLite Configuration` should be `# SQLite Configuration`

**Comment by victorhuangwq** [comment]
The one click setup has been deprecated, so this issue is not longer relevant. I will be proceeding to close this issue.
