### ISSUE TITLE
Error when adding multiple annotations to one submission for the same problem

### ISSUE THREAD

**Issue by devanshk** [autolab/Autolab#881]
Creating one annotation works fine but trying to create another or editing an existing annotation fails with "Failed to save annotation!!!".

To replicate:
1. Go to Lab -> Grade Submissions -> List archive -> Click on source file
(*.c).
2. Click on the '+' icon next to a line.
3. Add a comment, non-zero grade and select 'problem0' from the drop-down menu.
4. Save.
5. Repeat steps 3 and 4.

**Comment by StevenJamesMoore** [comment]
It appears this may have been hot-fixed now, but we had another report (INC0285764 in ServiceNow) of a user having this same problem.

Has the hotfix been pushed to dev? I was able to replicate this on https://autolab-dev.andrew.cmu.edu just now.

**Comment by AmirAlavi** [comment]
I'm also having this issue when grading assignments. I need to annotate two issues with the same problem, but can't add the second one.

**Comment by devanshk** [comment]
The hotfix for multiple annotations is ready and we're finishing some testing before we pull to production.

**Comment by devanshk** [comment]
Resolved
