### ISSUE TITLE
api mismatch between submissions#new and submissions#create

### ISSUE THREAD

**Issue by cg2v** [autolab/Autolab#884]
Submissions#create seems to expect multiple (possibly invalid) cud ids as part of the submission, and filters invalid ones out. This may make sense when it's being used to "Fill In Empty Submissions", but not when a single submission is being created. In the latter case, a missing or invalid cud_id should result in an error and the opportunity to fix the form.

**Comment by devanshk** [comment]
Submissions#create appears to return an error if it receives any invalid cud_ids. Is this still an open issue?

<img width="607" alt="screen shot 2018-02-11 at 12 17 16 pm" src="https://user-images.githubusercontent.com/1356687/36076084-bcd8ab46-0f25-11e8-8b60-7c75b75b2eb2.png">

**Comment by victorhuangwq** [comment]
Issue seems to be addressed. Closing
