### ISSUE TITLE
Student Getting Dropped when Changing Sections

### ISSUE THREAD

**Issue by StevenJamesMoore** [autolab/Autolab#894]
Currently if a student changes to a different section within the same course, they get marked as "dropped".

This behaviour makes since for the usual case (where the student is marked dropped if their enrollment status changes, since it's usually that they're dropping the course), but could it be changed so if they're still in the same course they don't get marked as "dropped"? 

This was reported in ServiceNow under INC0284647

**Comment by zyx-billy** [comment]
The ServiceNow ticket mentioned this happens when uploading a new roster. I tried this locally but was unable to replicate the problem... In the code, it checks if a user exists by matching andrewID, so as long as the user's andrewID is still present in the new roster, he/she should not be marked as dropped (even if other info about him/her changed).
I wonder if the student's section was the only thing that changed in the new roster, or were there more items changed?

**Comment by StevenJamesMoore** [comment]
Ah, sorry for not including the roster upload portion!

I just asked the instructor on the ServiceNow ticket if that was the only that changed in the new roster and they said yes.

**Comment by zyx-billy** [comment]
This doesn't seem possible given what the code does... I also tried a couple of times locally, and wasn't able to replicate this problem: the user is marked black, and is not dropped.

I did come across a random bug: if a user is ever dropped (either manually or by uploading a roster without them), they cannot be undropped by uploading a roster that includes them (i.e. an instructor needs to go undrop them manually on the website). Therefore, if a roster without the student was ever imported to Autolab, they will remain dropped even after a new roster that has them (in a different section perhaps) was imported again. This is pretty far fetched, but that's all I can think of right now.

There might be more to work on if the instructor can show us this happening again, or if we can look at the logs, that may help... Some random thoughts: is there a new roster format this year from CMU? is it possible another instructor dropped the students by accident?

**Comment by devanshk** [comment]
@StevenJamesMoore, is the instructor still having this issue?

**Comment by StevenJamesMoore** [comment]
@devanshk They haven't reported or updated this again, but I assume it's because since the semester is more established, students aren't adding/dropping currently for this to occur.

**Comment by victorhuangwq** [comment]
Issue seems stale as of now. Will close. Do create an issue if this is still relevant
