### ISSUE TITLE
[Feature] Allow Annotations to have Color

### ISSUE THREAD

**Issue by StevenJamesMoore** [autolab/Autolab#897]
A user sent in a ticket saying a nice feature to have would be other colors for annotations.

Specifically, they don't like to give full points on a question and have it with a red text on it (it is quicker to mark while looking at the pdf than going back and forth to the table). Even when full marks are given, the text is red which is associated with an error.

(Reported in ServiceNow under INC0285764)

**Comment by jbman223** [comment]
This feature can be easily implemented into the new annotations overhaul.

**Comment by StevenJamesMoore** [comment]
One question in regards to the annotation overall (not sure if I should ask it here?), will grading still be able to be done with said annotations? Previously with the one annotation per category limit it was straightforward, but will it now be an aggregate of them or is the grading aspect removed from annotations now?

**Comment by victorhuangwq** [comment]
Issue should  no longer be relevant under. https://github.com/autolab/Autolab/releases/tag/v2.4.0.
Do raise a new issue if you think such an improvement is still needed under the new annotations viewer.
