### ISSUE TITLE
"End At" Dates Changing After Assessment Creation

### ISSUE THREAD

**Issue by StevenJamesMoore** [autolab/Autolab#899]
This is more of "watch" item, but a user reported setting the "End at" dates for autograded homework to be exactly one day later than their "Due at" date, back in July or August.  Now, all these "End dates" dates have been mysteriously reset to be the same of the "Due date" and they had to go and change them back.

We haven't made a production publish since May, but I do recall there being a code change for this feature:
"On edit assessment handin page “End At” and “Grading Deadline” inputs now change when “Due At” date changed to preserve invariant (Due At <= End At <= Grading Deadline)"

Is it possible this change would cause such behaviour? I've setup a test assessment to see if it'll trigger sometime in the future and I'll update this ticket if anyone else reports it.

[INC0287476](https://cmu.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=8b42d05cdb9d8b00b5863a90ad9619e1%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true)

**Comment by TheodorJ** [comment]
This is definitely worthwhile, but in this case, there's not really much to investigate. Since the ticket is kept open, I'm gonna close this issue.
