### ISSUE TITLE
[Feature] Reread yaml Files on Reload

### ISSUE THREAD

**Issue by StevenJamesMoore** [autolab/Autolab#900]
**Problem**:
Today, I needed to modify one of the assessments in my class (the link to my class is https://autolab.andrew.cmu.edu/courses/15122-f17), in particular the problem set.  I uploaded the new file on AFS (/afs/cs.cmu.edu/academic/class/15122-f17/autolab/speller/speller.yml) but clicking on "Reload config file" for that assessment and trying to regrade the (test) submissions in there did not do anything.  I had to manually propagate the configuration updates on the web interface.

**Reason**:
Currently reload only rereads "course.rb/<lab>.rb". The yaml files are only ever read when assessments are imported. 

**Feature Suggestion**:
Make reload reread the yaml file, as a common change made is to deployed homework, which would require this to avoid the manual propagation.

**Compliment**:
I use scripts to load my assessments on Autolab (the link to my class is https://autolab.andrew.cmu.edu/courses/15122-f17).  That works like a charm. 👍 

Reported from: [INC0287461](https://cmu.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3Dac2077c4db5d8b00b5863a90ad961923%26sysparm_stack%3Dincident_list.do%3Fsysparm_query%3Dactive%3Dtrue)

**Comment by damianhxy** [comment]
This seems to be a matter of removing the `new_record?` check from `assessment.rb#load_yaml` and calling `@assessment.load_yaml` inside `assessments_controller.rb#reload`

**Comment by damianhxy** [comment]
After discussion with Iliano, this is now a non-issue
