### ISSUE TITLE
Student cannot be undropped via roster upload

### ISSUE THREAD

**Issue by zyx-billy** [autolab/Autolab#901]
Not sure if this was a deliberate design decision or a bug, but once a student is dropped (either manually or by uploading a roster that doesn't include them), they cannot be undropped by uploading a roster that includes them. An instructor must undrop them manually on the website.

If this was deliberate, it seems we should inform people of this behavior somewhere. Currently, those that are already dropped still appear on the 'preview' page after uploading a roster (they appear black).

**Comment by zyx-billy** [comment]
Going to leave this open. We should discuss whether this is a feature or a bug next meeting...

**Comment by damianhxy** [comment]
Fixed in #1436 (visual hint pending in #1558)
