### ISSUE TITLE
Code annotations aren't allowed to be longer than about 110 characters

### ISSUE THREAD

**Issue by AmirAlavi** [autolab/Autolab#902]
Should allow significantly longer comments. This would be less of an issue if adding multiple annotations to the same problem was working properly, but that is broken right now as well. See #881

**Comment by TheodorJ** [comment]
Just rechecked this -- long annotations are allowed, but they don't wrap around and just run off the page. Still worth fixing

**Comment by victorhuangwq** [comment]
Issue should be addressed in the new speedgrader upgrader. https://github.com/autolab/Autolab/releases/tag/v2.4.0

Do raise another PR if the issue still persist in the new feature
