### ISSUE TITLE
[Feature] SVN/Git Support

### ISSUE THREAD

**Issue by StevenJamesMoore** [autolab/Autolab#904]
An instructor suggested, as students' voiced, that being able to checkout weekly hw from a SVN/Git repo rather than downloading the handout from the web and then copying it to AFS would be handy.

Additionally, it would be great if the availability of the various files is determined by the "starts at" date.

Could the previous SVN support code be leveraged for this?

(From ticket [INC0291985](https://cmu.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3D27f790ccdb6d4740b5863a90ad961997%26sysparm_view%3Dportal%26sysparm_record_target%3Dtask%26sysparm_record_row%3D3%26sysparm_record_rows%3D7%26sysparm_record_list%3Dassigned_to%253Djavascript%253Ags.user_id%2528%2529%255Eactive%253Dtrue%255Estate%2521%253D6%255EORDERBYDESCsys_updated_on))

**Comment by victorhuangwq** [comment]
Issue seems to be addressed by autolab-cli (ability to download files via a terminal). Closing https://github.com/autolab/autolab-cli
