### ISSUE TITLE
OSX installation instructions do not include instructions to migrate db

### ISSUE THREAD

**Issue by kmicinski** [autolab/Autolab#911]
After 

    bundle exec rake db:create

I tried to perform the next step to populate dummy data. This failed dramatically with a fairly unhelpful error message (to people not experienced in SQL). I figured there would be a migration task, which I eventually used, but I would not have known about this if I hadn't written Rails apps before.

Once I used

    bundle exec rake db:migrate

I was able to go through much of the rest of the tutorial smoothly

**Comment by jbman223** [comment]
I have submitted a PR to the Autolab Docs to get this fixed. Thanks for pointing this issue out.
