### ISSUE TITLE
"Export Roster" button should export all students in a course

### ISSUE THREAD

**Issue by TheodorJ** [autolab/Autolab#912]
Currently, the "Export Roster" button exports all of the users that were added to the course via roster. This should be changed to export all users in a course (except those who have dropped). 

To Replicate:

1. Go to "Manage Course"
2. Go to "Manage Students" Page
3. Click "Export Roster"

If done on localhost with an AutoPopulated course, then the roster will be empty.

**Comment by devanshk** [comment]
Looks like it was a development-only issue with the autopopulate script not setting the 'dropped' property. For some reason, this didn't take the default value 'false,' instead saving it as 'nil.'

Fixed by c9fc881, and adding students with the UI doesn't have this issue.
