### ISSUE TITLE
"Add User to Course" fields grayed out 

### ISSUE THREAD

**Issue by TheodorJ** [autolab/Autolab#922]
Go to:

Course Page -> Manage Course -> Manage Students -> Add User to Course. the name and email address fields seem to be grayed out, they should be open for editing.

**Comment by devanshk** [comment]
Seems to work fine in the develop branch, and the code doesn't appear to have anything that disables the email field. Are you able to replicate this on the develop branch too?

<img width="721" alt="screen shot 2017-10-29 at 12 53 41 pm" src="https://user-images.githubusercontent.com/1356687/32146243-935b291a-bcaa-11e7-8dfa-e40c4c1167a1.png">

**Comment by cg2v** [comment]
Production does not have the patch from #877

**Comment by devanshk** [comment]
Makes sense. Closing this as we've addressed it on develop!
