### ISSUE TITLE
Python in-line console

### ISSUE THREAD

**Issue by TheodorJ** [autolab/Autolab#926]
This would make it a lot easier for TAs to grade submissions for 15-110 and 15-112, in addition to other python courses outside CMU. In the future, we could add support for other debuggers (e.g. GDB, GHCI)

**Comment by jbman223** [comment]
Instead of an in line console maybe this could somehow be worked into the client, a TA could do something along the lines of `autolab run <submission>` and it would run it magically

**Comment by victorhuangwq** [comment]
Closing this issue, as it is stale and there are no longer any ongoing discussion here.
