### ISSUE TITLE
Late Submissions Over Daylight Savings Time

### ISSUE THREAD

**Issue by StevenJamesMoore** [autolab/Autolab#932]
**Issue Summary:**
This is super specific, but when calculating the time for a late submission, is 24 hours subtracted from the current due date, which actually becomes 25 when it's the day for DST? Presumably the inverse would happen and cause an issue too when DST ends.

**Reported Issue:**
We had a homework assignment due on Saturday, November 5th at 8pm. Students were allowed to
use a grace day to submit up to one day late- Sunday, November 6th at 8pm.
However, some students who submitted with a grace day were given a penalty
for submitting with one grace day and one penalty late day. This
specifically happened to students who submitted between 7pm-8pm Sunday
night.

I think this happened because you calculate the number of days submitted
late by adding 24 hours at a time to the original deadline. This works fine
for most cases, but it doesn't work when Daylight Savings Time switches
overnight! In the case of this weekend, that gave students *25 *hours
between submission times.

I'll fix the problem for our class by moving the submission deadline on
Saturday to be at 9pm, but I thought you'd like to know so that you could
fix it for real in the backend.

**Ticket:**
[INC0306359](https://cmu.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=f88eb785db160700cd1cf3a31d96191c%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true)

**Comment by zyx-billy** [comment]
The guess was correct. The number of days late is computed by calculating how many 24-hours have passed since the due time. Since the desired behavior is usually to keep using the same time of day as the due time, we should change this to account for the change in timezone when crossing DST borders.

**Comment by zyx-billy** [comment]
fixed with #939.
