### ISSUE TITLE
Contact page points to wrong git issues tracker

### ISSUE THREAD

**Issue by touretzkyds** [autolab/Autolab#934]
This page contains a link to an issue tracker on GitHub:

  https://autolab.andrew.cmu.edu/contact

The problem is that it points to the issue tracker for a fork of AutoLab at the University of Buffalo, instead of the one at CMU.  Here is the link contained on the page:

  https://github.com/mikedrewitt/Autolab/issues/

The correct link is:

  https://github.com/autolab/Autolab/issues/

**Comment by zyx-billy** [comment]
Thanks for the notice! Fixed in #938,
