### ISSUE TITLE
Code fixes & new features from Univ. Buffalo?

### ISSUE THREAD

**Issue by rosecatherinek** [autolab/Autolab#936]
Hi Team,

I am a TA for a course at CMU that uses Autolab. I happened to report an issue on the fork of Autolab for use at University at Buffalo, by mistake. The repo owner let me know that their code base does not have this problem and that they have other additional bug fixes and new features, which they would be happy to merge with the CMU's Autolab code base. See: https://github.com/daviddob/Autolab/issues/30

I just wanted to bring your attention to that in case you are interested.

Thanks,
Rose.

**Comment by cg2v** [comment]
Team: The reason for the 404 on the regrade was because the regrade request was sent as a GET instead of a POST. I was able to reproduce this one time, but after that, jquery correctly matched picked up on the "data-method" attribute on the button and sent it as a post
