### ISSUE TITLE
View Source can't deal with .zip and .tgz archives (High priority)

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#94]
The view source option doesn't seem to be able to deal with .tgz files or .zip files, which is a problem for courses like 15122-s15 (.tgz files for scavhunt) and 15-110 (.zip files for lab1). For example, clicking on the "View Source" options for one of droh's submissions of the 15122-s15 scavhunt lab gives:

500 – Internal error
This does not appear to be a valid archive file.

even though I've confirmed that it's a valid archive file and it autogrades correctly. This should be given high priority because the 122 and 110 TAs won't be able to grade the assignments.

**Comment by dlbucci** [comment]
Is this all archives (tar included) or just tgz files?

**Comment by droh** [comment]
It works for .tar files.

-- David O'Hallaron
-- Prof of CS and ECE, Carnegie Mellon University
-- GHC 7517, x8-8199
-- http://www.cs.cmu.edu/~droh
