### ISSUE TITLE
Upper-right User Button strobes when clicked

### ISSUE THREAD

**Issue by TheodorJ** [autolab/Autolab#949]
To replicate:

Go to an assessment's Statistics page --> Click on your username at the top-right corner of the screen. The drop-down menu flashes for a half-second before disappearing.

**Comment by devanshk** [comment]
This happens because we're loading multiple versions of Materialize on this page, and they both have watchers on the button click. Whichever gets there first tries to open the menu, and the later one tries to close it.

**Comment by damianhxy** [comment]
Closing this with #1535 that removes jquery and materialize (which #957 would have done).
