### ISSUE TITLE
Automatically picking PDF

### ISSUE THREAD

**Issue by KLaschinger** [autolab/Autolab#951]
I am a student that used Autolab at Univ at Buffalo, and I recently had a written homework where I submitted a text file that Autolab changed the extension over to .pdf so I wasn't able to notice that I had submitted the wrong file. It would be nice that even if you submit a file with a different extension, to know that that extension is, even if it still only loads pdf files in the browser and any other file as a text file.  Also, if you try to "download submission" for any file that was changed to a pdf that is not formatted as a pdf, Google Chrome will throw an error"Failed to load PDF Document" and no physical download will occur.

I'm not sure if this is a bug or lack of feature and if is only a problem for the Univ at Buffalo branch.

**Comment by victorhuangwq** [comment]
There is a need to be a manner to check if the file submitted fits the expected type. Even if it is just the file extension (.tar, .pdf)
