### ISSUE TITLE
PDF Annotation resize icon displayed over New Annotation form

### ISSUE THREAD

**Issue by TheodorJ** [autolab/Autolab#952]
To replicate:

- Create a new PDF annotation with arbitrary comment
- Click on PDF, just away from top-left corner of above fresh annotation
- See that the southwest-facing arrow in bottom-left corner of fresh annotation's box is still displayed over New Annotation form

**Comment by victorhuangwq** [comment]
Issue should have been addressed in new Speedgrader upgrade. https://github.com/autolab/Autolab/releases/tag/v2.4.0
