### ISSUE TITLE
Assessment Creation Date Fields Always Use EST, but Display as Local After Creation

### ISSUE THREAD

**Issue by StevenJamesMoore** [autolab/Autolab#953]
**Issue**:
When creating an assessment, the times picked for due/open/etc. are in EST. Once it's been created, these times are then shown as local. For instance, when someone creates an assessment in Doha, they select for it to be due at 9 am (since it uses EST for creation) which translates to 5 pm Doha time.

**Ticket**:
INC0327646

**Comment by devanshk** [comment]
Addressed by #954
