### ISSUE TITLE
Install Script fails on Ubuntu 17

### ISSUE THREAD

**Issue by TheodorJ** [autolab/Autolab#959]

**Comment by DeveloperACE** [comment]
![ca5b7f72-2044-4f47-8656-8702a6f4054f](https://user-images.githubusercontent.com/17362949/35945291-8d9392e2-0c14-11e8-8669-462e956e6f13.jpeg)
![48b45fa3-44fe-4732-b297-78bc8309ba58](https://user-images.githubusercontent.com/17362949/35945292-8db30780-0c14-11e8-8f8d-2cc7f064fb63.jpeg)

**Comment by jbman223** [comment]
@DeveloperACE I know a lot has been happening with this in the past few weeks. Did this end up being a DNS issue or an Autolab issue?

**Comment by DeveloperACE** [comment]
@jbman223 it was DNS. my apologies
