### ISSUE TITLE
Nasty bug converting to new .rb files (High priority)

### ISSUE THREAD

**Issue by droh** [autolab/Autolab#97]
I tried to set up 213 in Autolab today and ran into a really nasty problem that will affect Kosbie as well as soon as he starts trying to install assessments: If an instructor has a mistake in the .rb files (e.g., forgets to update the new listOptions format), the assessment will install with no error messages, but trying to visit it DKs. Worse, there is no way out for the instructor. Since the lab can't be visited, the instructor has no way to reload the config file or delete the assessment and start over. To escape this trap, I had to manually edit the cached config files in /opt/autolab/build/Autolab/courseConfig, which of course instructors like Kosbie won't be able to do. 

I believe the solution for this is for Autolab to refuse to install an assessment if the .rb file has a error. 

Kosbie will run into this soon, and I think a dev should meet with him 1:1 to help him through the process.

**Comment by andrewwuan** [comment]
Accessing assessment reload link (manually type the link) also fixes the problem. How does adding "reload course config" and "reload assessment config" links to DK page sound to you?

**Comment by droh** [comment]
Sounds good. We can't expect users to type the direct link.

On Monday, January 19, 2015, An Wu <notifications@github.com> wrote:

> Accessing assessment reload link (manually type the link) also fixes the
> problem. How does adding "reload course config" and "reload assessment
> config" links to DK page sound to you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autolab/Autolab/issues/97#issuecomment-70577874>.
>


-- 
Sent from my iPhone.

**Comment by robsimmons** [comment]
Is there a practical reason why the click on "reload assessment config" or "reload course config" couldn't notice the error before deleting the cached copy?

**Comment by droh** [comment]
Correct me if I'm wrong devs, but I think the issue is that we can only detect syntax at reload config time. Runtime errors that occur when the overloaded functions get called can only be detected at runtime.
