### ISSUE TITLE
tango_client should retry on certain errors

### ISSUE THREAD

**Issue by cg2v** [autolab/Autolab#983]
Our deployment is having an as-yet unidentified problem with networking between autolab and tango (or it could be that tango is too busy and is not accepting all connections). Whatever the cause and resolution of that issue is, the fact is that networks are not 100% reliable in the real world, and autolab should attempt to deal with that.

I would recommend that tango_client.rb retry http operations on certain exceptions. At the very least, Timeout::Error, Errno::ECONNRESET, Errno::ECONNABORTED, Errno::EPIPE should be tried a few times, and it usually makes sense to sleep a few seconds between attempts.

**Comment by zyx-billy** [comment]
Yes, the logs for 122 from last night shows a bunch of ECONNRESETs (for open, upload, and addJob requests). It's interesting why this wasn't much of a problem before.
I've created a fix for this in branch `tango_client_retry`. I'm not 100% sure how the production server processes concurrent requests though. Would simply sleeping the thread be the best way to delay work?

**Comment by cg2v** [comment]
The production server uses apache and passenger. There should be plenty of threads available, so sleeping in the request isn't a big deal.

**Comment by zyx-billy** [comment]
OK sounds good. The #985 fix would work then. The only problem is the client won't get a response until we're done retrying, which could take an extra couple of seconds worst case. Hopefully this isn't too bad in practice, or we might want to throw in a loading screen for this (or make some bigger changes to the backend workflow).
