### ISSUE TITLE
Error : Authentication plugin "caching_sha2_password" cannot be loadded

### ISSUE THREAD

**Issue by baeharam** [autolab/Autolab#990]
I installed Autolab by One-Click installation, but error occurred during installation.
![autolab_error](https://user-images.githubusercontent.com/35518072/40061458-f4d8d0e0-5893-11e8-903a-f25e4b7b94d4.png)
How can I manage this problem?

**Comment by ronzalo** [comment]
I had the same problem, changing the mysql image to mysql:5.7 on docker-compose.yml solves it for now

**Comment by baeharam** [comment]
@ronzalo  I changed mysql image to mysql:5.7 but, it occurs other error.
![autolab_error2](https://user-images.githubusercontent.com/35518072/40107284-cfccd27a-5932-11e8-86f1-bf6209bd9dd5.png)

**Comment by ronzalo** [comment]
@baeharam you have to remove the volumes before changing the mysql versions.

```
docker-compose rm
docker volume rm list_of_your_volumes
docker-compose up

```

**Comment by baeharam** [comment]
@ronzalo  I changed mysql to mysql:5.7 which you said, but I cannot start that image. What's wrong?
![1](https://user-images.githubusercontent.com/35518072/40267963-52b71f78-5ba0-11e8-9d41-df13deed5344.png)
![2](https://user-images.githubusercontent.com/35518072/40267965-5785838c-5ba0-11e8-9c8a-593ae9166026.png)

**Comment by baeharam** [comment]
@devanshk Thank you for your upgrade, but it is still not working... I removed all docker files referencing this [stackoverflow post](https://stackoverflow.com/a/44760775) but what I got during installation is like below.
![screenshot from 2018-05-24 20 21 43](https://user-images.githubusercontent.com/35518072/40482514-ac1f2a40-5f44-11e8-8d2b-1bdeaeb85f84.png)

**Comment by ArchitParnami** [comment]
@baeharam I had a similar issue. I made it work by adding the password in ./local/Autolab/config/database-docker.yml file. Put your password in single quotes. For ex: 'password'.  I am not sure if this is the right approach but it worked for me.

**Comment by baeharam** [comment]
@ArchitParnami Thank you, I succeeded to install Autolab, but I have a problem about local landing page, I cannot read homework4 or other pages.
![screenshot from 2018-05-25 20 43 02](https://user-images.githubusercontent.com/35518072/40542761-042e0da6-6011-11e8-8047-d96682a39043.png)

**Comment by ArchitParnami** [comment]
@baeharam I have the same issue, but if when i click on "Reload Assessment Config", the homework page reloads and I can see the homework. Also its not an issue if you create a new course and then create new homework.

**Comment by baeharam** [comment]
@ArchitParnami  I solved it, Thx! But, how can I submit my homework as a student in local Autolab? In database, there is only administrator id and I cannot sign in because of authentication of email but local.
How can I do?

**Comment by kakalotto** [comment]
@baeharam , you click on Manage course > Act on user.

BTW, everything that @ArchitParnami  has been correct and been gold so far in this thread, much appreciated.  I had all of the same issues.
