### ISSUE TITLE
sendmail dependency for one click autolab install

### ISSUE THREAD

**Issue by kakalotto** [autolab/Autolab#994]
Should the install script install sendmail as a dependency?

Starting local_db_1    ... done
Starting local_tango_1 ... done
Creating Course AutoPopulated and config file
Creating Assessments
Creating Problems
Fast-creating Users
**sh: 1: /usr/sbin/sendmail: not found
sh: 1: /usr/sbin/sendmail: not found**
...
Fast-creating Submissions and Scores (might take a while)
Fast-creating AUDs
Creating configuration files
Creating Autograde Assessment
Population Successful
[6/6] Done

a

**Comment by zzhou612** [comment]
Also encountered this issue.

**Comment by Gusser93** [comment]
This sometimes breaks my setup with 
```
rake aborted!
Errno::EPIPE: Broken pipe
```

**Comment by victorhuangwq** [comment]
One click install is currently deprecated. Will close this issue soon
