### ISSUE TITLE
Unable to submit file for Autograding

### ISSUE THREAD

**Issue by ArchitParnami** [autolab/Autolab#995]
Hello,

I am running a freshly installed AutoLab on my Ubuntu 16.04. I have created a new course and within the course I have created a new assessment. I have set up this assessment for Auto grading as per the documentation.  Autograding VM is autograding_image. 

Now as soon as I submit the assessment I get the following 500 internal error:
-- !ruby/exception:NoMethodError
message: 'undefined method `sendJob_AddHTMLMessages'' for #<AssessmentsController:0x000000083fc750>'

Please see the attached files.

[stack dump.txt](https://github.com/autolab/Autolab/files/2077716/stack.dump.txt)
![nomethoderror](https://user-images.githubusercontent.com/5300486/41058548-12294232-6998-11e8-9fe6-4ae018dfb8f2.png)

Thanks!

**Comment by ArchitParnami** [comment]
Update: Found the Bug/Root Cause

The reason my code does not have sendJob_AddHTMLMessages method is because the file which is suppose to have this function is out-of-date.

While browsing your online repository, I found that this function is defined in 
https://github.com/autolab/Autolab/blob/master/app/controllers/assessment/autograde.rb

However my local copy of autograde.rb does not have this function. This happens because during the one-click installation process, the install.sh script overrides the latest autograde.rb with 
https://github.com/autolab/autolab-oneclick/blob/master/cover/autograde.rb
which does not have the latest commits.

Here:
https://github.com/autolab/autolab-oneclick/blob/master/install.sh
Line 150 - 153
```
 if [ "$OPTION" == "local" ]  
    then  
      cp ../cover/autograde.rb ./Autolab/app/controllers/assessment/autograde.rb  
 fi
```

**Comment by datamove** [comment]
Hi, 
I have this 500 error on submit too with a recent install. 
@ArchitParnami , How did you work around?
Thanks!

**Comment by datamove** [comment]
The solution is

If you are to keep autograde.rb from the cover folder then need to patch 

app/controllers/assessment/handin.rb

and replace sendJob_AddHTMLMessages with autogradeSubmissions

**Comment by victorhuangwq** [comment]
One-click is currently deprecated, and will be replaced with a docker based implementation. Will close this issue.
