### ISSUE TITLE
Assignment description robustness

### ISSUE THREAD

**Issue by repmop** [autolab/Autolab#998]
It seems assignment descriptions do not support the use of utf-6+ emojis, as evidenced by this screenshot:

![image](https://user-images.githubusercontent.com/25692161/41576453-76d6618a-7355-11e8-9f50-46de04be6542.png)

(the description in question used the following emoji: 💸)

Please rectify this at once, it's of vital import!

EDIT: I would bet good money this is your issue:
https://medium.com/@adamhooper/in-mysql-never-use-utf8-use-utf8mb4-11761243e434

**Comment by damianhxy** [comment]
This is more of a deployment issue. Closing it since this should be addressed once @cg2v performs the upgrade to utf8mb4 over winter break
