### ISSUE TITLE
[Feature Request] Import CSV to Add Instructors & TAs

### ISSUE THREAD

**Issue by StevenJamesMoore** [autolab/Autolab#999]
When the list of Instructors and/or TAs gets to and past a dozen or so, it’d be nice to be able to import a single CSV instead of having to do it manually.

i.e:
johnsmith@andrew.cmu.edu, instructor
someoneelse@andrew.cmu.edu, course assistant

**Comment by damianhxy** [comment]
Resolved by #1640
